### ISSUE TITLE
[BUG]In windows ,I can not save outlines as.zip archive of ROI files for imajej

### ISSUE THREAD

**Issue by bobonannan** [MouseLand/cellpose#1006]
GUI_INFO: normalization checked: computing saturation levels (and optionally filtered image)
{'lowhigh': None, 'percentile': [1.0, 99.0], 'normalize': True, 'norm3D': False, 'sharpen_radius': 0, 'smooth_radius': 0, 'tile_norm_blocksize': 0, 'tile_norm_smooth3D': 1, 'invert': False}
[0, 255.0]
(1, 1024, 1024, 1)
GUI_INFO: 4532 masks found
GUI_INFO: creating cellcolors and drawing masks
GUI_INFO: loaded in previous changes
GUI_INFO: saving 4532 ImageJ ROIs to .zip archive.
2024-09-03 17:44:35,645 [WARNING] Multiprocessing is disabled for Windows
Traceback (most recent call last):
  File "D:\anaconda\envs\cellpose\lib\site-packages\cellpose\gui\menus.py", line 62, in <lambda>
    parent.saveROIs.triggered.connect(lambda: io._save_rois(parent))
  File "D:\anaconda\envs\cellpose\lib\site-packages\cellpose\gui\io.py", line 590, in _save_rois
    save_rois(parent.cellpix[0], parent.filename)
  File "D:\anaconda\envs\cellpose\lib\site-packages\cellpose\io.py", line 592, in save_rois
    rois = [ImagejRoi.frompoints(outline) for outline in outlines]
  File "D:\anaconda\envs\cellpose\lib\site-packages\cellpose\io.py", line 592, in <listcomp>
    rois = [ImagejRoi.frompoints(outline) for outline in outlines]
  File "D:\anaconda\envs\cellpose\lib\site-packages\roifile\roifile.py", line 455, in frompoints
    left_top = coords.min(axis=0)
  File "D:\anaconda\envs\cellpose\lib\site-packages\numpy\core\_methods.py", line 45, in _amin
    return umr_minimum(a, axis, None, out, keepdims, initial, where)
ValueError: zero-size array to reduction operation minimum which has no identity

I segment 4532 mask ,but I want get cell area in imajej ,but i can not save it

**Comment by carsen-stringer** [comment]
I think this might be fixed now, try installing the latest version `pip install git+https://github.com/mouseland/cellpose.git`

**Comment by carsen-stringer** [comment]
closing for now, will reopen if it's not working

**Comment by WanzeChen** [comment]
hi,

I have installed the latest version (both V3.1.1.1. and V3.1.1.2) but still have a similar issue. When the image is small and ROI number is small (a few hundred), it works well to save the outlines as.zip archive. However, when the image is large (10000 X 10000 pixels) and has thousands of ROIs, it then gets stuck after a message "[WARNING] Multiprocessing is disabled for Windows" both when running in the command line or GUI. 

Here is the information about my environment and the error messages: 

(cellpose_test) PS C:\Users\dell> python -m cellpose
2025-02-24 19:27:44,255 [INFO] WRITING LOG OUTPUT TO C:\Users\dell\.cellpose\run.log
2025-02-24 19:27:44,255 [INFO]
cellpose version:       3.1.1.1
platform:               win32
python version:         3.10.16
torch version:          2.5.1
2025-02-24 19:27:45,382 [INFO] ** TORCH CUDA version installed and working. **
GUI_INFO: loading image: G:/Wzchen/HK-ti2/INPUT3/positive_image_9block.tif
GUI_INFO: image shape: (10640, 10448, 1)
GUI_INFO: normalization checked: computing saturation levels (and optionally filtered image)
{'lowhigh': None, 'percentile': [1.0, 99.0], 'normalize': True, 'norm3D': True, 'sharpen_radius': 0, 'smooth_radius': 0, 'tile_norm_blocksize': 0, 'tile_norm_smooth3D': 1, 'invert': False}
[0, 255.0]
2025-02-24 17:53:44,474 [INFO] ** TORCH CUDA version installed and working. **
2025-02-24 17:53:44,474 [INFO] >>>> using GPU (CUDA)
2025-02-24 17:53:44,475 [INFO] >> cyto3 << model set to be used
2025-02-24 17:53:44,564 [INFO] >>>> loading model C:\Users\dell\.cellpose\models\cyto3
2025-02-24 17:53:44,729 [INFO] >>>> model diam_mean =  30.000 (ROIs rescaled to this size during training)
{'lowhigh': None, 'percentile': [1.0, 99.0], 'normalize': True, 'norm3D': True, 'sharpen_radius': 0, 'smooth_radius': 0, 'tile_norm_blocksize': 0, 'tile_norm_smooth3D': 1, 'invert': False}
2025-02-24 17:53:44,846 [INFO] channels set to [0, 0]
2025-02-24 17:53:44,846 [INFO] ~~~ FINDING MASKS ~~~
2025-02-24 17:58:14,411 [INFO] >>>> TOTAL TIME 269.56 sec
2025-02-24 17:58:17,778 [INFO] 6980 cells found with model in 276.076 sec
GUI_INFO: 6980 masks found
GUI_INFO: creating cellcolors and drawing masks
GUI_INFO: saving 6980 ImageJ ROIs to .zip archive.
2025-02-24 17:58:35,696 [WARNING] Multiprocessing is disabled for Windows
Traceback (most recent call last):
  File "D:\software\anaconda3\envs\cellpose_test\lib\site-packages\cellpose\gui\menus.py", line 62, in <lambda>
    parent.saveROIs.triggered.connect(lambda: io._save_rois(parent))
  File "D:\software\anaconda3\envs\cellpose_test\lib\site-packages\cellpose\gui\io.py", line 602, in _save_rois
    save_rois(parent.cellpix[0], parent.filename)
  File "D:\software\anaconda3\envs\cellpose_test\lib\site-packages\cellpose\io.py", line 591, in save_rois
    outlines = utils.outlines_list(masks, multiprocessing=multiprocessing)
  File "D:\software\anaconda3\envs\cellpose_test\lib\site-packages\cellpose\utils.py", line 249, in outlines_list
    return outlines_list_single(masks)
  File "D:\software\anaconda3\envs\cellpose_test\lib\site-packages\cellpose\utils.py", line 266, in outlines_list_single
    contours = cv2.findContours(mn.astype(np.uint8), mode=cv2.RETR_EXTERNAL,
KeyboardInterrupt

Thank you!
