### ISSUE TITLE
[BUG] Error saving flows and cellprob tif image

### ISSUE THREAD

**Issue by derekthirstrup** [MouseLand/cellpose#1037]
**Describe the bug**
Saving flows and cellprob image of composite z stack does not work.

**To Reproduce**
Steps to reproduce the behavior: CtrlF or selecting option in menu yields error.

Traceback (most recent call last):
  File "C:\Users\derekt\.conda\envs\cellpose3.1.0\Lib\site-packages\cellpose\gui\menus.py", line 68, in <lambda>
    parent.saveFlows.triggered.connect(lambda: io._save_flows(parent))
                                               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\derekt\.conda\envs\cellpose3.1.0\Lib\site-packages\cellpose\gui\io.py", line 581, in _save_flows
    imsave(base + "_cp_flows.tif", parent.flows[4][:-1])
                                   ~~~~~~~~~~~~^^^
IndexError: list index out of range

**Comment by derekthirstrup** [comment]
I suspect this is related to issue 1038.  I will check if the gui mode still yields this error with the dynamics.py bugfix version I just pushed and get back to you if the issue is resolved.

**Comment by carsen-stringer** [comment]
let me know if this still isn't working, closing for now
