### ISSUE TITLE
[BUG] error when --diameter is set to 0.

### ISSUE THREAD

**Issue by jazberna1** [MouseLand/cellpose#1072]
**Describe the bug**
Hi, I get error when I run cellpose on the CLI setting `--diameter 0.` so the diameter gets estimated. I don't get the error when I supply a value for the diameter. 

**To Reproduce**
This is the commad I am running 
```
python -m cellpose --Zstack --verbose
--diameter 0.
--image_path /jorge/outdir/image.tif
--use_gpu
--savedir /jorge/outdir
--save_tif
--no_npy
--pretrained_model nuclei
```

**My versions and OS:**
cellpose version:       3.1.0
platform:               win32
python version:         3.10.15
torch version:          2.5.1+cu118

**Run log**
This is the full traceback
```
Traceback (most recent call last):
  File "C:\Users\malieva\miniconda3\envs\cellpose\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\malieva\miniconda3\envs\cellpose\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\malieva\miniconda3\envs\cellpose\lib\site-packages\cellpose\__main__.py", line 358, in <module>
    main()
  File "C:\Users\malieva\miniconda3\envs\cellpose\lib\site-packages\cellpose\__main__.py", line 205, in main
    out = model.eval(
  File "C:\Users\malieva\miniconda3\envs\cellpose\lib\site-packages\cellpose\models.py", line 187, in eval
    diams, _ = self.sz.eval(x, channels=channels, channel_axis=channel_axis,
  File "C:\Users\malieva\miniconda3\envs\cellpose\lib\site-packages\cellpose\models.py", line 773, in eval
    diam_style = self.diam_mean if (diam_style == 0 or
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

**Comment by carsen-stringer** [comment]
Ah yes I think this is because your data is a z-stack and size estimation doesn't work on a z-stack, is your data a z-stack not single plane? "--Zstack" is for opening the GUI, it does not enable 3D processing, you want to include "--do_3D" or a nonzero "--stitch_threshold". and you want to specify the diameter manually. let me know if that doesn't work.
