### ISSUE TITLE
Resize- Error in completing cellpose segmentation

### ISSUE THREAD

**Issue by athulrv** [MouseLand/cellpose#133]
I have the latest version cellpose running on cuda. The output image seems to be empty when i open it in image j. 

Traceback (most recent call last):
  File "/home/snz/anaconda3/envs/cellpose/lib/python3.7/site-packages/cellpose/gui.py", line 1288, in compute_model
    interpolation=cv2.INTER_NEAREST)
  File "/home/snz/anaconda3/envs/cellpose/lib/python3.7/site-packages/cellpose/transforms.py", line 422, in resize_image
    imgs = cv2.resize(img0, (Lx, Ly), interpolation=interpolation)
cv2.error: OpenCV(4.4.0) /tmp/pip-req-build-2mquh264/opencv/modules/imgproc/src/resize.cpp:3572: error: (-215:Assertion failed) !dsize.empty() in function 'resize'

![cellpose error_v2](https://user-images.githubusercontent.com/49643312/96264041-0eb9db00-0fc4-11eb-91a1-f5c4df6612ab.png)

**Comment by alxndrkalinin** [comment]
@athulrv I have the same problem – have you figured out how to make it work?

**Comment by carsen-stringer** [comment]
can you try the latest github version of cellpose please? I think this has been fixed

**Comment by carsen-stringer** [comment]
I'm closing this issue due to inactivity, please comment if it's not resolved
