### ISSUE TITLE
Latest github version, --use_gpu broken 

### ISSUE THREAD

**Issue by kevinjohncutler** [MouseLand/cellpose#146]
When using the flag, it now gives:
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/kcutler/cellpose/cellpose/__main__.py", line 265, in <module>
    main()
  File "/home/kcutler/cellpose/cellpose/__main__.py", line 114, in main
    use_gpu = utils.use_gpu()
AttributeError: module 'cellpose.utils' has no attribute 'use_gpu'
```
Without the flag, of course it defaults to CPU.

**Comment by carsen-stringer** [comment]
oops just fixed this

**Comment by alimaram** [comment]
This problem seems to still exist when running Cellpose from the google colab notebook.  I'm getting the same error as above (AttributeError: module 'cellpose.utils' has no attribute 'use_gpu')
