### ISSUE TITLE
AttributeError: module 'cffi' has no attribute 'FFI'

### ISSUE THREAD

**Issue by fanweiya** [MouseLand/cellpose#147]
```
Traceback (most recent call last):
  File "D:\Program Files\anaconda\envs\cellpose\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\Program Files\anaconda\envs\cellpose\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Program Files\anaconda\envs\cellpose\lib\site-packages\cellpose\__main__.py", line 6, in <module>
    from . import utils, models, io
  File "D:\Program Files\anaconda\envs\cellpose\lib\site-packages\cellpose\utils.py", line 11, in <module>
    from . import metrics
  File "D:\Program Files\anaconda\envs\cellpose\lib\site-packages\cellpose\metrics.py", line 2, in <module>
    from . import utils, dynamics
  File "D:\Program Files\anaconda\envs\cellpose\lib\site-packages\cellpose\dynamics.py", line 12, in <module>
    @njit('(float64[:], int32[:], int32[:], int32, int32, int32, int32)', nogil=True)
  File "D:\Program Files\anaconda\envs\cellpose\lib\site-packages\numba\core\decorators.py", line 218, in wrapper
    disp.compile(sig)
  File "D:\Program Files\anaconda\envs\cellpose\lib\site-packages\numba\core\compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "D:\Program Files\anaconda\envs\cellpose\lib\site-packages\numba\core\dispatcher.py", line 819, in compile
    cres = self._compiler.compile(args, return_type)
  File "D:\Program Files\anaconda\envs\cellpose\lib\site-packages\numba\core\dispatcher.py", line 78, in compile
    status, retval = self._compile_cached(args, return_type)
  File "D:\Program Files\anaconda\envs\cellpose\lib\site-packages\numba\core\dispatcher.py", line 92, in _compile_cached
    retval = self._compile_core(args, return_type)
  File "D:\Program Files\anaconda\envs\cellpose\lib\site-packages\numba\core\dispatcher.py", line 110, in _compile_core
    pipeline_class=self.pipeline_class)
  File "D:\Program Files\anaconda\envs\cellpose\lib\site-packages\numba\core\compiler.py", line 626, in compile_extra
    args, return_type, flags, locals)
  File "D:\Program Files\anaconda\envs\cellpose\lib\site-packages\numba\core\compiler.py", line 312, in __init__
    typingctx.refresh()
  File "D:\Program Files\anaconda\envs\cellpose\lib\site-packages\numba\core\typing\context.py", line 156, in refresh
    self.load_additional_registries()
  File "D:\Program Files\anaconda\envs\cellpose\lib\site-packages\numba\core\typing\context.py", line 687, in load_additional_registries
    from . import (
  File "D:\Program Files\anaconda\envs\cellpose\lib\site-packages\numba\core\typing\cffi_utils.py", line 19, in <module>
    ffi = cffi.FFI()
AttributeError: module 'cffi' has no attribute 'FFI'
```

**Comment by carsen-stringer** [comment]
I'm not sure how to fix this but can you try
```
pip install cffi --upgrade
```
and/or
```
conda install cffi
```
