### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'batch_size'

### ISSUE THREAD

**Issue by LeeLMarshall** [MouseLand/cellpose#153]
I used the command line version and it works perfectly using default models
python -m cellpose 
            --dir TH_inverted 
            --pretrained_model cyto 
            --chan 0 
            --save_tif 
            --use_gpu 
            --diameter 50

I was able to train my own model
python -m cellpose 
            --train 
            --dir TH_train 
            --pretrained_model cyto 
            --chan 0 
            --use_gpu 
            --n_epochs 500

But when I come to run samples using my trained model
python -m cellpose 
            --dir TH_ownmodel 
            --pretrained_model TH_train/models/cellpose_residual_on_style_on_concatenation_off_TH_train_2020_11_25_21_28_42.625288             
            --chan 0 
            --save_tif 
            --use_gpu 

Can I please get some help with this error

matplotlib not installed
** CUDA version installed and working. **
>>>> using GPU
Traceback (most recent call last):
  File "/home/lee.marshall/bras_secondary/Lee/anaconda3/envs/cellpose/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/lee.marshall/bras_secondary/Lee/anaconda3/envs/cellpose/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/lee.marshall/bras_secondary/Lee/anaconda3/envs/cellpose/lib/python3.7/site-packages/cellpose/__main__.py", line 261, in <module>
    main()
  File "/home/lee.marshall/bras_secondary/Lee/anaconda3/envs/cellpose/lib/python3.7/site-packages/cellpose/__main__.py", line 159, in main
    batch_size=args.batch_size)
TypeError: __init__() got an unexpected keyword argument 'batch_size'

**Comment by carsen-stringer** [comment]
this has been fixed now, I will make a new pip with some fixes for running pretrained models soon
