### ISSUE TITLE
Image cannot be opened in gui

### ISSUE THREAD

**Issue by IrenXu** [MouseLand/cellpose#185]
Hi, when I try to open my tiff image in the gui, it says there is typeerror
(cancer_tutorial) C:\Users\DELL>cellpose
** TORCH CUDA version installed and working. **
D:/Yilin/cancer_20201215_slip2_area1_long_acq_corr_long_acq_blue_0.0296_green_0.0765_heated_to_37_1/cancer_20201215_slip2_area1_long_acq_corr_long_acq_blue_0.0296_green_0.0765_heated_to_37_1_overlay_2.tif
1000 (464, 4, 421)
removed all cells
Traceback (most recent call last):
  File "c:\users\dell\anaconda3\envs\cancer_tutorial\lib\site-packages\pyqtgraph\graphicsItems\ImageItem.py", line 439, in paint
    self.render()
  File "c:\users\dell\anaconda3\envs\cancer_tutorial\lib\site-packages\pyqtgraph\graphicsItems\ImageItem.py", line 431, in render
    argb, alpha = fn.makeARGB(image, lut=lut, levels=levels)
  File "c:\users\dell\anaconda3\envs\cancer_tutorial\lib\site-packages\pyqtgraph\functions.py", line 1066, in makeARGB
    raise TypeError("data.shape[2] must be <= 4")
TypeError: data.shape[2] must be <= 4
Traceback (most recent call last):
  File "c:\users\dell\anaconda3\envs\cancer_tutorial\lib\site-packages\pyqtgraph\graphicsItems\ImageItem.py", line 439, in paint
    self.render()
  File "c:\users\dell\anaconda3\envs\cancer_tutorial\lib\site-packages\pyqtgraph\graphicsItems\ImageItem.py", line 431, in render
    argb, alpha = fn.makeARGB(image, lut=lut, levels=levels)
  File "c:\users\dell\anaconda3\envs\cancer_tutorial\lib\site-packages\pyqtgraph\functions.py", line 1066, in makeARGB
    raise TypeError("data.shape[2] must be <= 4")
TypeError: data.shape[2] must be <= 4
Traceback (most recent call last):
  File "c:\users\dell\anaconda3\envs\cancer_tutorial\lib\site-packages\pyqtgraph\graphicsItems\ImageItem.py", line 439, in paint
    self.render()
  File "c:\users\dell\anaconda3\envs\cancer_tutorial\lib\site-packages\pyqtgraph\graphicsItems\ImageItem.py", line 431, in render
    argb, alpha = fn.makeARGB(image, lut=lut, levels=levels)
  File "c:\users\dell\anaconda3\envs\cancer_tutorial\lib\site-packages\pyqtgraph\functions.py", line 1066, in makeARGB
    raise TypeError("data.shape[2] must be <= 4")
TypeError: data.shape[2] must be <= 4

So what the reason might be?

**Comment by carsen-stringer** [comment]
apologies for the vague error message, the cellpose GUI only supports images with 3 color channels, please choose the relevant channels for segmentation and resave the tiff with those channels, or run cellpose on the command line or in a notebook
