### ISSUE TITLE
SizeModel training fails when GPU training is enabled

### ISSUE THREAD

**Issue by gkossakowski** [MouseLand/cellpose#195]
Hi,

SizeModel training crashes with:
```
Traceback (most recent call last):
  File "/home/gkk/miniconda3/envs/cellpose/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/gkk/miniconda3/envs/cellpose/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/gkk/coding/cellpose/cellpose/__main__.py", line 258, in <module>
    main()
  File "/home/gkk/coding/cellpose/cellpose/__main__.py", line 244, in main
    sz_model.train(images, labels, test_images, test_labels, channels=channels, batch_size=args.batch_size)
  File "/home/gkk/coding/cellpose/cellpose/models.py", line 846, in train
    feat = self.cp.network(imgi)[-1]
  File "/home/gkk/coding/cellpose/cellpose/core.py", line 386, in network
    self.net = mkldnn_utils.to_mkldnn(self.net)
  File "/home/gkk/miniconda3/envs/cellpose/lib/python3.7/site-packages/torch/utils/mkldnn.py", line 202, in to_mkldnn
    return m_fn_rec(module)
  File "/home/gkk/miniconda3/envs/cellpose/lib/python3.7/site-packages/torch/utils/mkldnn.py", line 199, in m_fn_rec
    setattr(new_m, name, m_fn_rec(sub_m))
  File "/home/gkk/miniconda3/envs/cellpose/lib/python3.7/site-packages/torch/utils/mkldnn.py", line 199, in m_fn_rec
    setattr(new_m, name, m_fn_rec(sub_m))
  File "/home/gkk/miniconda3/envs/cellpose/lib/python3.7/site-packages/torch/utils/mkldnn.py", line 199, in m_fn_rec
    setattr(new_m, name, m_fn_rec(sub_m))
  [Previous line repeated 3 more times]
  File "/home/gkk/miniconda3/envs/cellpose/lib/python3.7/site-packages/torch/utils/mkldnn.py", line 197, in m_fn_rec
    new_m = m_fn(m)
  File "/home/gkk/miniconda3/envs/cellpose/lib/python3.7/site-packages/torch/utils/mkldnn.py", line 192, in m_fn
    return MkldnnBatchNorm(m)
  File "/home/gkk/miniconda3/envs/cellpose/lib/python3.7/site-packages/torch/jit/_script.py", line 196, in init_then_script
    original_init(self, *args, **kwargs)
  File "/home/gkk/miniconda3/envs/cellpose/lib/python3.7/site-packages/torch/utils/mkldnn.py", line 145, in __init__
    self.register_buffer('weight', dense_module.weight.to_mkldnn())
RuntimeError: Could not run 'aten::to_mkldnn' with arguments from the 'CUDA' backend. 'aten::to_mkldnn' is only available for these backends: [CPU, BackendSelect, Named, AutogradOther, AutogradCPU, AutogradCUDA, AutogradXLA, AutogradPrivateUse1, AutogradPrivateUse2, AutogradPrivateUse3, Tracer, Autocast, Batched, VmapMode].
```

I believe the problem is that the main Cellpose model is trained on GPU but then SizeModel wants to invoke it from CPU (with MKL enabled). I haven't wrapped my head around the code to tell which place got the device assignment wrong (Cellpose training or SizeModel training).

I'm using the latest version of Cellpose from GitHub.

**Comment by carsen-stringer** [comment]
should be fixed in latest version
