### ISSUE TITLE
GUI Installation Issue

### ISSUE THREAD

**Issue by borovij** [MouseLand/cellpose#213]
Hello! Our lab is having some trouble installing cellpose on our lab computers, and after reading previous issues posted regarding installation errors, I did not see any posts about the specific error we are having. Installation and activation of cellpose were smooth on our desktops, which run Windows 10, but once we run the command 'python -m cellpose' we get the following error messages:

(base) C:\Users\borovij>conda activate cellpose

(cellpose) C:\Users\borovij>python -m cellpose
downloading logo
Traceback (most recent call last):
  File "C:\Users\borovij\Anaconda3\envs\cellpose\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\borovij\Anaconda3\envs\cellpose\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\borovij\Anaconda3\envs\cellpose\lib\site-packages\cellpose\__main__.py", line 258, in <module>
    main()
  File "C:\Users\borovij\Anaconda3\envs\cellpose\lib\site-packages\cellpose\__main__.py", line 99, in main
    gui.run()
  File "C:\Users\borovij\Anaconda3\envs\cellpose\lib\site-packages\cellpose\gui.py", line 120, in run
    utils.download_url_to_file('http://www.cellpose.org/static/images/cellpose_transparent.png', icon_path, progress=True)
  File "C:\Users\borovij\Anaconda3\envs\cellpose\lib\site-packages\cellpose\utils.py", line 37, in download_url_to_file
    u = urlopen(url)
  File "C:\Users\borovij\Anaconda3\envs\cellpose\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\borovij\Anaconda3\envs\cellpose\lib\urllib\request.py", line 531, in open
    response = meth(req, response)
  File "C:\Users\borovij\Anaconda3\envs\cellpose\lib\urllib\request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Users\borovij\Anaconda3\envs\cellpose\lib\urllib\request.py", line 563, in error
    result = self._call_chain(*args)
  File "C:\Users\borovij\Anaconda3\envs\cellpose\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "C:\Users\borovij\Anaconda3\envs\cellpose\lib\urllib\request.py", line 755, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "C:\Users\borovij\Anaconda3\envs\cellpose\lib\urllib\request.py", line 531, in open
    response = meth(req, response)
  File "C:\Users\borovij\Anaconda3\envs\cellpose\lib\urllib\request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Users\borovij\Anaconda3\envs\cellpose\lib\urllib\request.py", line 569, in error
    return self._call_chain(*args)
  File "C:\Users\borovij\Anaconda3\envs\cellpose\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "C:\Users\borovij\Anaconda3\envs\cellpose\lib\urllib\request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 401: Unauthorized

Any insight as to what the cause of this error may be?
Thanks!

**Comment by carsen-stringer** [comment]
sorry about that, the URL needs to be an HTTPS instead of an HTTP. others have had this issue, I'm not sure why it happens to some people but not others. It is fixed in the github version of cellpose, you can clone the repo and install the github version from the repo folder with `pip install -e .`
