### ISSUE TITLE
issues with installation on mac

### ISSUE THREAD

**Issue by haniyyahs** [MouseLand/cellpose#222]
Hello, I recently tried to uninstall and reinstall anaconda on my computer as I was having trouble getting cellpose to work. I have a mac and I downloaded anaconda for python 3.7. When I do the "conda env create -f environment.yml" I get an error. I couldn't download the environment.yml file from github as I didn't see the option, so I copy/pasted the text into a TextEdit file on my computer and changed the extension name. I have included the error that I got in the terminal below, in case that would be helpful. 
I also tried using the 'pip install cellpose[gui]' but this didn't work either. 
I'm new to using the terminal and environments like anaconda so I'd appreciate any help with this! I tried using the google colab option too but ran into similar issues when I wanted to open up the files saved using cellpose that way. 

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/Users/haniyyah/anaconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "/Users/haniyyah/anaconda3/lib/python3.7/site-packages/conda_env/cli/main.py", line 80, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/Users/haniyyah/anaconda3/lib/python3.7/site-packages/conda_env/cli/main_create.py", line 80, in execute
        directory=os.getcwd())
      File "/Users/haniyyah/anaconda3/lib/python3.7/site-packages/conda_env/specs/__init__.py", line 40, in detect
        if spec.can_handle():
      File "/Users/haniyyah/anaconda3/lib/python3.7/site-packages/conda_env/specs/yaml_file.py", line 18, in can_handle
        self._environment = env.from_file(self.filename)
      File "/Users/haniyyah/anaconda3/lib/python3.7/site-packages/conda_env/env.py", line 151, in from_file
        return from_yaml(yamlstr, filename=filename)
      File "/Users/haniyyah/anaconda3/lib/python3.7/site-packages/conda_env/env.py", line 136, in from_yaml
        data = yaml_load_standard(yamlstr)
      File "/Users/haniyyah/anaconda3/lib/python3.7/site-packages/conda/common/serialize.py", line 76, in yaml_load_standard
        return yaml.load(string, Loader=yaml.Loader, version="1.2")
      File "/Users/haniyyah/anaconda3/lib/python3.7/site-packages/ruamel_yaml/main.py", line 935, in load
        return loader._constructor.get_single_data()
      File "/Users/haniyyah/anaconda3/lib/python3.7/site-packages/ruamel_yaml/constructor.py", line 109, in get_single_data
        node = self.composer.get_single_node()
      File "/Users/haniyyah/anaconda3/lib/python3.7/site-packages/ruamel_yaml/composer.py", line 78, in get_single_node
        document = self.compose_document()
      File "/Users/haniyyah/anaconda3/lib/python3.7/site-packages/ruamel_yaml/composer.py", line 101, in compose_document
        node = self.compose_node(None, None)
      File "/Users/haniyyah/anaconda3/lib/python3.7/site-packages/ruamel_yaml/composer.py", line 138, in compose_node
        node = self.compose_mapping_node(anchor)
      File "/Users/haniyyah/anaconda3/lib/python3.7/site-packages/ruamel_yaml/composer.py", line 211, in compose_mapping_node
        while not self.parser.check_event(MappingEndEvent):
      File "/Users/haniyyah/anaconda3/lib/python3.7/site-packages/ruamel_yaml/parser.py", line 141, in check_event
        self.current_event = self.state()
      File "/Users/haniyyah/anaconda3/lib/python3.7/site-packages/ruamel_yaml/parser.py", line 719, in parse_flow_mapping_key
        token.start_mark,
    ruamel_yaml.parser.ParserError: while parsing a flow mapping
      in "<unicode string>", line 1, column 1:
        {\rtf1\ansi\ansicpg1252\cocoartf2513
        ^ (line: 1)
    expected ',' or '}', but got '{'
      in "<unicode string>", line 2, column 34:
        \cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fmodern\fcharset0 C ... 
                                         ^ (line: 2)

`$ /Users/haniyyah/anaconda3/bin/conda-env create -f environment.yml`

  environment variables:
                 CIO_TEST=<not set>
  CONDA_AUTO_UPDATE_CONDA=false
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=/Users/haniyyah/anaconda3/bin/conda
             CONDA_PREFIX=/Users/haniyyah/anaconda3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=/Users/haniyyah/anaconda3/bin/python
               CONDA_ROOT=/Users/haniyyah/anaconda3
              CONDA_SHLVL=1
                     PATH=/Users/haniyyah/anaconda3/bin:/Users/haniyyah/anaconda3/bin:/Users/han
                          iyyah/anaconda3/condabin:/Library/Frameworks/Python.framework/Versions
                          /3.7/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : base
    active env location : /Users/haniyyah/anaconda3
            shell level : 1
       user config file : /Users/haniyyah/.condarc
 populated config files : /Users/haniyyah/.condarc
          conda version : 4.8.2
    conda-build version : 3.18.11
         python version : 3.7.6.final.0
       virtual packages : __osx=10.15.7
       base environment : /Users/haniyyah/anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/haniyyah/anaconda3/pkgs
                          /Users/haniyyah/.conda/pkgs
       envs directories : /Users/haniyyah/anaconda3/envs
                          /Users/haniyyah/.conda/envs
               platform : osx-64
             user-agent : conda/4.8.2 requests/2.22.0 CPython/3.7.6 Darwin/19.6.0 OSX/10.15.7
                UID:GID : 501:20
             netrc file : None
           offline mode : False

An unexpected error has occurred. Conda has prepared the above report.

**Comment by carsen-stringer** [comment]
It looks like the text file is not the right format? you can download directly from here: https://raw.githubusercontent.com/MouseLand/cellpose/master/environment.yml or you can download the whole repo from github with git clone or download zip

**Comment by haniyyahs** [comment]
Okay, I did that and it worked, and I followed the steps for local installation after redownloading the environment file directly, but now when I run 'python -m cellpose' I get the following: "/anaconda3/envs/cellpose/bin/python: No module named cellpose." Do you know what I might be doing wrong at this step of the installation process? Thank you so much for your help!

**Comment by haniyyahs** [comment]
I got it work thanks!
