### ISSUE TITLE
Error in windows

### ISSUE THREAD

**Issue by sumankhan19** [MouseLand/cellpose#234]
Hi guys. I am having trouble in running cellpose in window 10. The error I receive is:

python -m cellpose
Traceback (most recent call last):
  File "C:\Users\admin.PC-C632F022\.conda\envs\cellpose\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\admin.PC-C632F022\.conda\envs\cellpose\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\admin.PC-C632F022\.conda\envs\cellpose\lib\site-packages\cellpose\__main__.py", line 7, in <module>
    from cellpose import utils, models, io
  File "C:\Users\admin.PC-C632F022\.conda\envs\cellpose\lib\site-packages\cellpose\utils.py", line 6, in <module>
    from scipy.ndimage import find_objects, gaussian_filter, generate_binary_structure, label, maximum_filter1d, binary_fill_holes
  File "C:\Users\admin.PC-C632F022\.conda\envs\cellpose\lib\site-packages\scipy\__init__.py", line 130, in <module>
    from . import _distributor_init
  File "C:\Users\admin.PC-C632F022\.conda\envs\cellpose\lib\site-packages\scipy\_distributor_init.py", line 61, in <module>
    WinDLL(os.path.abspath(filename))
  File "C:\Users\admin.PC-C632F022\.conda\envs\cellpose\lib\ctypes\__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found

I tried to google, but no avail. Kindly help

**Comment by carsen-stringer** [comment]
hmm looks like you may need to upgrade or downgrade scipy? https://github.com/ultralytics/yolov5/issues/241

Going to close for now, this looks like a scipy problem, but please let me know if it's still a problem
