### ISSUE TITLE
AttributeError: module 'torch.backends' has no attribute 'mkldnn' 

### ISSUE THREAD

**Issue by zylittlep** [MouseLand/cellpose#239]
Dear @carsen-stringer ,
I'm trying to use cellpose locally,  system is:
macOS High Sierra 10.13.6. 
Python 3.7
When I do 'run segmentation', I got error messages as follows:
using CPU
Running test snippet to check if MKL-DNN working
see https://pytorch.org/docs/stable/backends.html?highlight=mkl
Traceback (most recent call last):
  File "/Users/yangzheng/opt/anaconda3/envs/cellpose/lib/python3.7/site-packages/cellpose/gui.py", line 1307, in compute_model
    self.initialize_model()
  File "/Users/yangzheng/opt/anaconda3/envs/cellpose/lib/python3.7/site-packages/cellpose/gui.py", line 1264, in initialize_model
    model_type=self.current_model)
  File "/Users/yangzheng/opt/anaconda3/envs/cellpose/lib/python3.7/site-packages/cellpose/models.py", line 113, in __init__
    diam_mean=self.diam_mean, torch=self.torch)
  File "/Users/yangzheng/opt/anaconda3/envs/cellpose/lib/python3.7/site-packages/cellpose/models.py", line 344, in __init__
    nclasses=nclasses, torch=torch)
  File "/Users/yangzheng/opt/anaconda3/envs/cellpose/lib/python3.7/site-packages/cellpose/core.py", line 185, in __init__
    self.mkldnn = check_mkl(self.torch)
  File "/Users/yangzheng/opt/anaconda3/envs/cellpose/lib/python3.7/site-packages/cellpose/core.py", line 96, in check_mkl
    mkl_enabled = torch.backends.mkldnn.is_available()
AttributeError: module 'torch.backends' has no attribute 'mkldnn'

Could anyone help with this, please? Thank you.

**Comment by zylittlep** [comment]
Problem solved by installing pytorch for CPU, as in https://anaconda.org/conda-forge/pytorch-cpu
