### ISSUE TITLE
Using GPU version of mxnet

### ISSUE THREAD

**Issue by saskra** [MouseLand/cellpose#248]
As I could not use torch on GPU (https://github.com/MouseLand/cellpose/issues/211) I wanted to test mxnet with GPU but I got this message:

```bash
(cellpose) saskra@a:~/PycharmProjects/cellpose$ python -m cellpose --train --dir /downsized/mixed/ --chan 0 --train_size --use_gpu --img_filter _img --mxnet
MXNET CUDA version not installed/working.
>>>> using CPU
```

After installing mxnet_cu102 I got this error:

````bash
(cellpose) saskra@a:~/PycharmProjects/cellpose$ python -m cellpose --train --dir /downsized/mixed/ --chan 0 --train_size --use_gpu --img_filter _img --mxnet
Traceback (most recent call last):
  File "/home/saskra/PycharmProjects/cellpose/cellpose/core.py", line 61, in _use_gpu_mxnet
    _ = mx.ndarray.array([1, 2, 3], ctx=mx.gpu(gpu_number))
NameError: name 'mx' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/saskra/anaconda3/envs/cellpose/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/saskra/anaconda3/envs/cellpose/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/saskra/PycharmProjects/cellpose/cellpose/__main__.py", line 264, in <module>
    main()
  File "/home/saskra/PycharmProjects/cellpose/cellpose/__main__.py", line 118, in main
    device, gpu = models.assign_device((not args.mxnet), args.use_gpu)
  File "/home/saskra/PycharmProjects/cellpose/cellpose/core.py", line 79, in assign_device
    if gpu and use_gpu(istorch=istorch):
  File "/home/saskra/PycharmProjects/cellpose/cellpose/core.py", line 57, in use_gpu
    return _use_gpu_mxnet(gpu_number)
  File "/home/saskra/PycharmProjects/cellpose/cellpose/core.py", line 64, in _use_gpu_mxnet
    except mx.MXNetError:
NameError: name 'mx' is not defined
````

When forcing "import mxnet as mx" I get this error, although cudnn is installed:

```bash
(cellpose-gpu) saskra@a:~/PycharmProjects/cellpose$ python -m cellpose --train --dir /downsized/mixed/ --chan 0 --train_size --use_gpu --img_filter _img --mxnet --pretrained_model cyto
Traceback (most recent call last):
  File "/home/saskra/anaconda3/envs/cellpose-gpu/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/saskra/anaconda3/envs/cellpose-gpu/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/saskra/PycharmProjects/cellpose/cellpose/__main__.py", line 9, in <module>
    from cellpose import utils, models, io
  File "/home/saskra/PycharmProjects/cellpose/cellpose/models.py", line 10, in <module>
    from . import transforms, dynamics, utils, plot, metrics, core
  File "/home/saskra/PycharmProjects/cellpose/cellpose/core.py", line 13, in <module>
    from mxnet import gluon, nd
  File "/home/saskra/anaconda3/envs/cellpose-gpu/lib/python3.7/site-packages/mxnet/__init__.py", line 23, in <module>
    from .context import Context, current_context, cpu, gpu, cpu_pinned
  File "/home/saskra/anaconda3/envs/cellpose-gpu/lib/python3.7/site-packages/mxnet/context.py", line 23, in <module>
    from .base import classproperty, with_metaclass, _MXClassPropertyMetaClass
  File "/home/saskra/anaconda3/envs/cellpose-gpu/lib/python3.7/site-packages/mxnet/base.py", line 351, in <module>
    _LIB = _load_lib()
  File "/home/saskra/anaconda3/envs/cellpose-gpu/lib/python3.7/site-packages/mxnet/base.py", line 342, in _load_lib
    lib = ctypes.CDLL(lib_path[0], ctypes.RTLD_LOCAL)
  File "/home/saskra/anaconda3/envs/cellpose-gpu/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libcudnn.so.8: cannot open shared object file: No such file or directory
```

Any help would be appreciated! :-)

**Comment by kevinjohncutler** [comment]
Sorry to see you're having problems. My best guess is that you don't have the right CUDA dependencies installed (also related to your posts in #211). I had to reinstall ubuntu on my machine at least twice to get it right... 10.2 is what I ended up using. Apparently drivers are backwards-compatible, but you want to stay about a year behind the latest CUDA release.

**Comment by saskra** [comment]
I have installed CUDA 10.2 in this environment via conda. Unfortunately, I cannot change the OS or graphics cards driver as too many other projects are depending on them. The only chance might be something like a Docker container. But even then I needed to know the exact configuration.

**Comment by carsen-stringer** [comment]
Hmm there may be settings you need to change in your bashrc? Do you have the CUDA libraries added to your PATH and LD_LIBRARY_PATH?

**Comment by saskra** [comment]
I always install CUDA only via Conda, because I need different versions in different projects. So the bashrc, PATH etc. should not play a role in my opinion.

**Comment by carsen-stringer** [comment]
There are two backends for cellpose: mxnet and torch. the default is torch, maybe it's recognizing it for torch?

have you tried also installing cudnn with conda? I don't have much advice here, I've always installed cuda outside conda when working with mxnet

**Comment by saskra** [comment]
Yes, maybe it is only recognised for torch, but that would also be strange. I have installed Cudnn via conda. However, I will test the training using torch again with the latest source code version here from the repository as soon as I have the resources free. If that works, I wouldn't need mxnet at all.

**Comment by carsen-stringer** [comment]
I don't think it would be so strange, torch may be detecting the cudatoolkit and setting the paths correctly. You could also try the advice here for mxnet: https://github.com/MouseLand/cellpose/issues/56

I'm going to close this issue for now
