### ISSUE TITLE
Error when running CellPose

### ISSUE THREAD

**Issue by tischi** [MouseLand/cellpose#253]
Hi!

We got this error:

```
Traceback (most recent call last):
  File "/g/funcgen/galaxy-production/tools/cellpose_segmentation/0.6/cp_segmentation.py", line 94, in <module>
    main(args.inputs, args.img_path, args.img_format, args.output_dir)
  File "/g/funcgen/galaxy-production/tools/cellpose_segmentation/0.6/cp_segmentation.py", line 57, in main
    **options)
  File "/g/funcgen/galaxy-production/database/dependencies/_conda/envs/mulled-v1-a3d8e3d2223f740ae00d18494ade7b9bef6e0c49ca4e41a5d033b2a48d633f57/lib/python3.7/site-packages/cellpose/models.py", line 282, in eval
    stitch_threshold=stitch_threshold)
  File "/g/funcgen/galaxy-production/database/dependencies/_conda/envs/mulled-v1-a3d8e3d2223f740ae00d18494ade7b9bef6e0c49ca4e41a5d033b2a48d633f57/lib/python3.7/site-packages/cellpose/models.py", line 542, in eval
    flow = np.array([dx_to_circ(dP[1:,i]) for i in range(dP.shape[1])])
  File "/g/funcgen/galaxy-production/database/dependencies/_conda/envs/mulled-v1-a3d8e3d2223f740ae00d18494ade7b9bef6e0c49ca4e41a5d033b2a48d633f57/lib/python3.7/site-packages/cellpose/models.py", line 542, in <listcomp>
    flow = np.array([dx_to_circ(dP[1:,i]) for i in range(dP.shape[1])])
  File "/g/funcgen/galaxy-production/database/dependencies/_conda/envs/mulled-v1-a3d8e3d2223f740ae00d18494ade7b9bef6e0c49ca4e41a5d033b2a48d633f57/lib/python3.7/site-packages/cellpose/models.py", line 64, in dx_to_circ
    flow = (utils.hsv_to_rgb(HSV)*255).astype(np.uint8)
  File "/g/funcgen/galaxy-production/database/dependencies/_conda/envs/mulled-v1-a3d8e3d2223f740ae00d18494ade7b9bef6e0c49ca4e41a5d033b2a48d633f57/lib/python3.7/site-packages/cellpose/utils.py", line 23, in hsv_to_rgb
    r, g, b = hsv_to_rgb_channels(h, s, v)
  File "/g/funcgen/galaxy-production/database/dependencies/_conda/envs/mulled-v1-a3d8e3d2223f740ae00d18494ade7b9bef6e0c49ca4e41a5d033b2a48d633f57/lib/python3.7/site-packages/numpy/lib/function_base.py", line 2108, in __call__
    return self._vectorize_call(func=func, args=vargs)
  File "/g/funcgen/galaxy-production/database/dependencies/_conda/envs/mulled-v1-a3d8e3d2223f740ae00d18494ade7b9bef6e0c49ca4e41a5d033b2a48d633f57/lib/python3.7/site-packages/numpy/lib/function_base.py", line 2186, in _vectorize_call
    ufunc, otypes = self._get_ufunc_and_otypes(func=func, args=args)
  File "/g/funcgen/galaxy-production/database/dependencies/_conda/envs/mulled-v1-a3d8e3d2223f740ae00d18494ade7b9bef6e0c49ca4e41a5d033b2a48d633f57/lib/python3.7/site-packages/numpy/lib/function_base.py", line 2146, in _get_ufunc_and_otypes
    outputs = func(*inputs)
  File "/g/funcgen/galaxy-production/database/dependencies/_conda/envs/mulled-v1-a3d8e3d2223f740ae00d18494ade7b9bef6e0c49ca4e41a5d033b2a48d633f57/lib/python3.7/colorsys.py", line 146, in hsv_to_rgb
    i = int(h*6.0) # XXX assume int() truncates!
ValueError: cannot convert float NaN to integer
```

<img width="855" alt="image" src="https://user-images.githubusercontent.com/2157566/116683215-917a1480-a9af-11eb-87e3-a961dc9fd56e.png">

<img width="325" alt="image" src="https://user-images.githubusercontent.com/2157566/116683316-afe01000-a9af-11eb-80b0-f8648aec7951.png">

Do you have an idea what the issue may have been?

**Comment by carsen-stringer** [comment]
It looks like the output flows are NaN? Who's cellpose wrapper is this? It's hard for me to tell what's going on without seeing the source code

**Comment by carsen-stringer** [comment]
closing due to inactivity but let us know if you still have issues
