### ISSUE TITLE
Counting channels & Handling empty masks

### ISSUE THREAD

**Issue by saskra** [MouseLand/cellpose#289]
I want to train on greyscale images with only one colour channel and I also have corresponding masks (see example images below) as well as the parameters that I think are appropriate - nevertheless the output is that a model would be trained on two channels. Is this just a confusing indication or is something actually going wrong? Maybe you can make the output more intuitive.

```bash
python -m cellpose --train --dir /train/ --test /test/ --chan 0 --use_gpu --img_filter _img --train_size --mask_filter _masks --save_tif --diameter 30. --look_one_level_down --pretrained_model cyto --exclude_on_edges
2021-07-07 15:38:27,125 [INFO] WRITING LOG OUTPUT TO /home/saskra/.cellpose/run.log
2021-07-07 15:38:33,481 [INFO] ** TORCH CUDA version installed and working. **
2021-07-07 15:38:33,481 [INFO] >>>> using GPU
2021-07-07 15:39:35,642 [INFO] >>>> pretrained model /home/saskra/.cellpose/models/cytotorch_0 is being used
2021-07-07 15:39:35,643 [INFO] >>>> during training rescaling images to fixed diameter of 30.0 pixels
2021-07-07 15:39:38,119 [INFO] train channels = 2
2021-07-07 15:39:39,595 [INFO] test channels = 2
2021-07-07 15:39:39,595 [INFO] NOTE: computing flows for labels (could be done before to save time)
100%|█| 378/378 [00:51<00:00,  7.27it/s]
2021-07-07 15:40:34,187 [INFO] NOTE: computing flows for labels (could be done before to save time)
100%|█| 252/252 [00:45<00:00,  5.51it/s]
2021-07-07 15:41:23,214 [INFO] >>>> training network with 2 channel input <<<<
2021-07-07 15:41:23,215 [INFO] >>>> saving every 100 epochs
2021-07-07 15:41:23,215 [INFO] >>>> median diameter = 30
2021-07-07 15:41:23,215 [INFO] >>>> LR: 0.20000, batch_size: 8, weight_decay: 0.00001
2021-07-07 15:41:23,215 [INFO] >>>> ntrain = 378
2021-07-07 15:41:23,215 [INFO] >>>> ntest = 252
2021-07-07 15:41:23,215 [INFO] (2, 480, 480)
2021-07-07 15:41:34,900 [INFO] Epoch 0, Time 11.7s, Loss 3.5584, Loss Test 4.5683, LR 0.0000
```

![small_WT_M2_1_10_img](https://user-images.githubusercontent.com/12963485/124771618-8f967980-df3b-11eb-9d05-147b727e1c9c.png)
![small_WT_M2_1_10_masks](https://user-images.githubusercontent.com/12963485/124771945-dbe1b980-df3b-11eb-976c-f742fe96d448.png)

**Comment by saskra** [comment]
By the way, if I let it go on, this is what happens:

```shell
python -m cellpose --train --dir /train/ --test /test/ --chan 0 --use_gpu --img_filter _img --train_size --mask_filter _masks --save_tif --diameter 30. --look_one_level_down --pretrained_model cyto --exclude_on_edges --n_epochs 5
2021-07-07 16:48:43,435 [INFO] WRITING LOG OUTPUT TO /home/saskra/.cellpose/run.log
2021-07-07 16:48:49,193 [INFO] ** TORCH CUDA version installed and working. **
2021-07-07 16:48:49,193 [INFO] >>>> using GPU
2021-07-07 16:48:51,704 [INFO] >>>> pretrained model /home/saskra/.cellpose/models/cytotorch_0 is being used
2021-07-07 16:48:51,704 [INFO] >>>> during training rescaling images to fixed diameter of 30.0 pixels
2021-07-07 16:48:54,134 [INFO] train channels = 2
2021-07-07 16:48:55,546 [INFO] test channels = 2
2021-07-07 16:48:55,546 [INFO] flows precomputed
2021-07-07 16:48:56,634 [INFO] flows precomputed
2021-07-07 16:48:59,058 [INFO] >>>> training network with 2 channel input <<<<
2021-07-07 16:48:59,058 [INFO] >>>> saving every 100 epochs
2021-07-07 16:48:59,058 [INFO] >>>> median diameter = 30
2021-07-07 16:48:59,058 [INFO] >>>> LR: 0.20000, batch_size: 8, weight_decay: 0.00001
2021-07-07 16:48:59,058 [INFO] >>>> ntrain = 378
2021-07-07 16:48:59,058 [INFO] >>>> ntest = 252
2021-07-07 16:48:59,058 [INFO] (2, 480, 480)
2021-07-07 16:49:09,119 [INFO] Epoch 0, Time 10.1s, Loss 3.5584, Loss Test 4.5683, LR 0.0000
2021-07-07 16:49:18,793 [INFO] Epoch 1, Time 19.7s, Loss 1.2256, Loss Test 1.5243, LR 0.0222
2021-07-07 16:49:18,793 [INFO] saving network parameters to /train/models/cellpose_residual_on_style_on_concatenation_off_train_2021_07_07_16_48_57.451884
2021-07-07 16:49:28,817 [INFO] Epoch 2, Time 29.8s, Loss 1.1482, Loss Test 1.5053, LR 0.0444
2021-07-07 16:49:39,183 [INFO] Epoch 3, Time 40.1s, Loss 1.1992, Loss Test 1.5153, LR 0.0667
2021-07-07 16:49:49,650 [INFO] Epoch 4, Time 50.6s, Loss 1.0746, Loss Test 1.4968, LR 0.0889
2021-07-07 16:49:49,650 [INFO] saving network parameters to /train/models/cellpose_residual_on_style_on_concatenation_off_train_2021_07_07_16_48_57.451884
2021-07-07 16:49:49,737 [INFO] >>>> model trained and saved to /train/models/cellpose_residual_on_style_on_concatenation_off_train_2021_07_07_16_48_57.451884
2021-07-07 16:49:53,300 [INFO] train channels = 2
2021-07-07 16:49:55,581 [INFO] test channels = 2
Traceback (most recent call last):
  File "/home/saskra/anaconda3/envs/cellpose/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/saskra/anaconda3/envs/cellpose/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/saskra/PycharmProjects/cellpose/cellpose/__main__.py", line 300, in <module>
    main()
  File "/home/saskra/PycharmProjects/cellpose/cellpose/__main__.py", line 286, in main
    sz_model.train(images, labels, test_images, test_labels, channels=channels, batch_size=args.batch_size)
  File "/home/saskra/PycharmProjects/cellpose/cellpose/models.py", line 939, in train
    del train_data[i]
IndexError: list assignment index out of range

```

**Comment by saskra** [comment]
PS: The crash seems to be related to empty masks.

**Comment by carsen-stringer** [comment]
re: channels, yeah it's a bit weird it will always use two channels, unless you use the `--all_channels` flag. I would be wary of using this though as it's not very well tested. But it's fine to use two channels and have an empty one.

hmm what do you mean by empty masks?

**Comment by saskra** [comment]
> hmm what do you mean by empty masks?

When I split my 3D image into individual layers, this also creates 2D images that do not contain cells, and this seems to be problematic for the program.
