### ISSUE TITLE
Train on 3D?

### ISSUE THREAD

**Issue by saskra** [MouseLand/cellpose#290]
You can't train Cellpose on 3D images, can you? If not, I would recommend an informative warning about this, the outputs below rather confused me at first. I was hoping for 3D training because I have to apply the parameter "--exclude_on_edges" as I don't have any masks for truncated objects in my dataset - and of course in 2D it is impossible to tell if an object touches an edge in 3D.

```shell
python -m cellpose --train --dir /train/ --chan 0 --use_gpu --img_filter _img_stacked --mask_filter _masks_stacked --save_tif --diameter 30. --look_one_level_down --pretrained_model cyto --exclude_on_edges --do_3D
2021-07-09 09:51:51,096 [INFO] WRITING LOG OUTPUT TO /home/saskra/.cellpose/run.log
2021-07-09 09:51:56,928 [INFO] ** TORCH CUDA version installed and working. **
2021-07-09 09:51:56,928 [INFO] >>>> using GPU
2021-07-09 09:51:57,158 [INFO] >>>> pretrained model /home/saskra/.cellpose/models/cytotorch_0 is being used
2021-07-09 09:51:57,158 [INFO] >>>> during training rescaling images to fixed diameter of 30.0 pixels
2021-07-09 09:51:57,510 [INFO] train channels = 2
2021-07-09 09:51:57,510 [INFO] NOTE: test data not provided OR labels incorrect OR not same number of channels as train data
2021-07-09 09:51:57,511 [INFO] flows precomputed
2021-07-09 09:51:57,737 [INFO] >>>> training network with 2 channel input <<<<
2021-07-09 09:51:57,737 [INFO] >>>> saving every 100 epochs
2021-07-09 09:51:57,737 [INFO] >>>> median diameter = 30
2021-07-09 09:51:57,737 [INFO] >>>> LR: 0.20000, batch_size: 8, weight_decay: 0.00001
2021-07-09 09:51:57,737 [INFO] >>>> ntrain = 22
2021-07-09 09:51:57,737 [INFO] (2, 480, 480)
Traceback (most recent call last):
  File "/home/saskra/anaconda3/envs/cellpose/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/saskra/anaconda3/envs/cellpose/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/saskra/PycharmProjects/cellpose/cellpose/__main__.py", line 307, in <module>
    main()
  File "/home/saskra/PycharmProjects/cellpose/cellpose/__main__.py", line 286, in main
    batch_size=args.batch_size)
  File "/home/saskra/PycharmProjects/cellpose/cellpose/models.py", line 720, in train
    learning_rate, n_epochs, momentum, weight_decay, batch_size, rescale)
  File "/home/saskra/PycharmProjects/cellpose/cellpose/core.py", line 900, in _train_net
    train_loss = self._train_step(imgi, lbl)
  File "/home/saskra/PycharmProjects/cellpose/cellpose/core.py", line 763, in _train_step
    loss = self.loss_fn(lbl,y)
  File "/home/saskra/PycharmProjects/cellpose/cellpose/models.py", line 633, in loss_fn
    loss = self.criterion(y[:,:2] , veci) 
  File "/home/saskra/anaconda3/envs/cellpose/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/saskra/anaconda3/envs/cellpose/lib/python3.7/site-packages/torch/nn/modules/loss.py", line 446, in forward
    return F.mse_loss(input, target, reduction=self.reduction)
  File "/home/saskra/anaconda3/envs/cellpose/lib/python3.7/site-packages/torch/nn/functional.py", line 2659, in mse_loss
    expanded_input, expanded_target = torch.broadcast_tensors(input, target)
  File "/home/saskra/anaconda3/envs/cellpose/lib/python3.7/site-packages/torch/functional.py", line 71, in broadcast_tensors
    return _VF.broadcast_tensors(tensors)  # type: ignore
RuntimeError: The size of tensor a (2) must match the size of tensor b (19) at non-singleton dimension 1
```

**Comment by carsen-stringer** [comment]
no you cannot train cellpose on 3D, you can train on 2D slices and then the model will use slice estimations of flows to create a 3D prediction, see info in the paper here: https://www.nature.com/articles/s41592-020-01018-x
