### ISSUE TITLE
Error trying to segment with trained model

### ISSUE THREAD

**Issue by kernco** [MouseLand/cellpose#301]
I'm trying to use a model I've trained on my own data, but I'm getting an error. This is the command I used to train the model:

`$ python -m cellpose --train --train_size --dir train_data --pretrained_model None --chan 1 --chan2 2`

And this is the command and output trying to segment a couple images with it:

```
$ python -m cellpose --dir test/ --pretrained_model train_data/models/cellpose_residual_on_style_on_concatenation_off_train_data_2021_07_16_10_57_23.505527 --chan 1 --chan2 2 --save_png
>>>> using CPU
>>>> using diameter 30.00 for all images
>>>> running cellpose on 2 images using chan_to_seg RED and chan (opt) GREEN
parsing model string to get cellpose options
Running test snippet to check if MKL-DNN working
see https://pytorch.org/docs/stable/backends.html?highlight=mkl
** MKL version working - CPU version is sped up. **
  0%|                                                                                    | 0/2 [00:00<?, ?it/s]time spent: running network 12.20s; flow+mask computation 14.36
  0%|                                                                                    | 0/2 [00:27<?, ?it/s]
Traceback (most recent call last):
  File "/home/jckern/anaconda3/envs/cellpose/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/jckern/anaconda3/envs/cellpose/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/jckern/anaconda3/envs/cellpose/lib/python3.7/site-packages/cellpose/__main__.py", line 252, in <module>
    main()
  File "/home/jckern/anaconda3/envs/cellpose/lib/python3.7/site-packages/cellpose/__main__.py", line 159, in main
    interp=(not args.no_interp))
ValueError: not enough values to unpack (expected 4, got 3)
```

There were no errors during training, so I'm not sure what the problem is.

**Comment by carsen-stringer** [comment]
I think this is an error from the old version of the code, can you try updating? `pip install cellpose --upgrade` going to close for now, let me know if it's still not working
