### ISSUE TITLE
Training nuclei segmentation in 3D

### ISSUE THREAD

**Issue by gusqgm** [MouseLand/cellpose#309]
Hi,

I have a couple of nuclei annotated in 3D and saved as tiff stacks and wanted to train CellPose on them from scratch. The stacks have different shapes, but all have quite high anisotropy - factor of nearly 7.7 from XY to Z.

Because of the anisotrpy I was trying first to avoid the augmentation step and was running the training with the `--fast_mode` option. Still, it seems that cellpose is trying to perform transformations to the data and then running into problems. Am I missing something here?

```
(cellpose) user@localMachine:/cellpose$ python -m cellpose --train --use_gpu --fast_mode --dir /Cellpose_Test/Training/ --chan 0 --mask_filter _mask --pretrained_model None --n_epochs 1000 --do_3D
2021-08-05 11:03:44,575 [INFO] WRITING LOG OUTPUT TO user/.cellpose/run.log
2021-08-05 11:03:46,469 [INFO] ** TORCH CUDA version installed and working. **
2021-08-05 11:03:46,469 [INFO] >>>> using GPU
2021-08-05 11:03:51,108 [INFO] >>>> training from scratch
2021-08-05 11:03:51,109 [INFO] >>>> during training rescaling images to fixed diameter of 30.0 pixels
2021-08-05 11:03:51,926 [INFO] train channels = 2
2021-08-05 11:03:51,926 [INFO] NOTE: test data not provided OR labels incorrect OR not same number of channels as train data
2021-08-05 11:03:51,926 [INFO] flows precomputed
user/miniconda3/envs/cellpose/lib/python3.7/site-packages/numpy/core/fromnumeric.py:3373: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
user/miniconda3/envs/cellpose/lib/python3.7/site-packages/numpy/core/_methods.py:170: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
2021-08-05 11:03:52,388 [INFO] >>>> training network with 2 channel input <<<<
2021-08-05 11:03:52,388 [INFO] >>>> saving every 100 epochs
2021-08-05 11:03:52,388 [INFO] >>>> median diameter = 30
2021-08-05 11:03:52,388 [INFO] >>>> LR: 0.20000, batch_size: 8, weight_decay: 0.00001
2021-08-05 11:03:52,388 [INFO] >>>> ntrain = 52
2021-08-05 11:03:52,388 [INFO] (2, 333, 331)
Traceback (most recent call last):
  File "/user/miniconda3/envs/cellpose/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/user/miniconda3/envs/cellpose/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/user/Code/Python/cellpose/cellpose/__main__.py", line 304, in <module>
    main()
  File "/user/Code/Python/cellpose/cellpose/__main__.py", line 283, in main
    batch_size=args.batch_size)
  File "/user/Code/Python/cellpose/cellpose/models.py", line 720, in train
    learning_rate, n_epochs, momentum, weight_decay, batch_size, rescale)
  File "/user/Code/Python/cellpose/cellpose/core.py", line 897, in _train_net
    rescale=rsc, scale_range=scale_range, unet=self.unet)
  File "/user/Code/Python/cellpose/cellpose/transforms.py", line 694, in random_rotate_and_resize
    lbl[n,k] = cv2.warpAffine(labels[k], M, (xy[1],xy[0]), flags=cv2.INTER_LINEAR)
IndexError: index 45 is out of bounds for axis 0 with size 45
```

Any help greatly appreciated, thank you!

**Comment by carsen-stringer** [comment]
hey @gusqgm you cannot train cellpose on 3D data, only on 2D slices, then it generalizes to 3D, see details in the paper: https://www.nature.com/articles/s41592-020-01018-x
