### ISSUE TITLE
[INFO] WRITING LOG OUTPUT TO /Users/yangzixuan/.cellpose/run.log

### ISSUE THREAD

**Issue by yzx19981008** [MouseLand/cellpose#329]
My computer is a MAC, and when I wanted to use the GUI of Cellpose, I typed Python -m cellpose, but it prompted me [INFO] WRITING LOG OUTPUT TO /Users/yangzixuan/.cellpose/run.log

My Python is 3.6.2
And prompts me to install cellpose[GUI] successfully.

`(cell) yangzixuan@yzxMacmini cellpose-master % python -m cellpose
2021-09-17 13:44:05,552 [INFO] WRITING LOG OUTPUT TO /Users/yangzixuan/.cellpose/run.log
Traceback (most recent call last):
  File "/Users/yangzixuan/opt/anaconda3/envs/cell/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/Users/yangzixuan/opt/anaconda3/envs/cell/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Users/yangzixuan/opt/anaconda3/envs/cell/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Users/yangzixuan/opt/anaconda3/envs/cell/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Users/yangzixuan/opt/anaconda3/envs/cell/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/Users/yangzixuan/opt/anaconda3/envs/cell/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/Users/yangzixuan/opt/anaconda3/envs/cell/lib/python3.6/http/client.py", line 1400, in connect
    server_hostname=server_hostname)
  File "/Users/yangzixuan/opt/anaconda3/envs/cell/lib/python3.6/ssl.py", line 401, in wrap_socket
    _context=self, _session=session)
  File "/Users/yangzixuan/opt/anaconda3/envs/cell/lib/python3.6/ssl.py", line 808, in __init__
    self.do_handshake()
  File "/Users/yangzixuan/opt/anaconda3/envs/cell/lib/python3.6/ssl.py", line 1061, in do_handshake
    self._sslobj.do_handshake()
  File "/Users/yangzixuan/opt/anaconda3/envs/cell/lib/python3.6/ssl.py", line 683, in do_handshake
    self._sslobj.do_handshake()
TimeoutError: [Errno 60] Operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yangzixuan/opt/anaconda3/envs/cell/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/yangzixuan/opt/anaconda3/envs/cell/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/yangzixuan/project/u-net/cellpose-master/cellpose/__main__.py", line 305, in <module>
    main()
  File "/Users/yangzixuan/project/u-net/cellpose-master/cellpose/__main__.py", line 117, in main
    gui.run()
  File "/Users/yangzixuan/project/u-net/cellpose-master/cellpose/gui/gui.py", line 128, in run
    download_url_to_file('https://github.com/MouseLand/cellpose/raw/master/docs/_static/cellpose_gui.png', guip_path, progress=True)
  File "/Users/yangzixuan/project/u-net/cellpose-master/cellpose/utils.py", line 55, in download_url_to_file
    u = urlopen(url)
  File "/Users/yangzixuan/opt/anaconda3/envs/cell/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/Users/yangzixuan/opt/anaconda3/envs/cell/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/Users/yangzixuan/opt/anaconda3/envs/cell/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/Users/yangzixuan/opt/anaconda3/envs/cell/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/Users/yangzixuan/opt/anaconda3/envs/cell/lib/python3.6/urllib/request.py", line 1361, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/Users/yangzixuan/opt/anaconda3/envs/cell/lib/python3.6/urllib/request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 60] Operation timed out>`

**Comment by qixinbo** [comment]
The model file is stored outside of China, so it has a connection error.
You may use a web proxy to access these files.

**Comment by yzx19981008** [comment]
thanks
