### ISSUE TITLE
IndexError: list index out of range in original_random_rotate_and_resize

### ISSUE THREAD

**Issue by saskra** [MouseLand/cellpose#332]
Since training on my own data didn't work, I wanted to re-train your model again with the latest Github code version and your data set as described in the readme to test if it's just my data responsible: https://github.com/MouseLand/cellpose/blob/master/docs/train.rst#L57

Unfortunately, I get this error message when I do this, which I remember was not the case with the old version a few weeks ago:

```bash
python -m cellpose --train --train_size --use_gpu --dir cellpose_dataset/train/ --test_dir cellpose_dataset/test/ --img_filter _img --pretrained_model None --chan 2 --chan2 1
2021-09-21 10:38:58,945 [INFO] WRITING LOG OUTPUT TO /home/saskra/.cellpose/run.log
2021-09-21 10:39:04,678 [INFO] ** TORCH CUDA version installed and working. **
2021-09-21 10:39:04,678 [INFO] >>>> using GPU
2021-09-21 10:39:10,881 [INFO] >>>> training from scratch
2021-09-21 10:39:10,881 [INFO] >>>> during training rescaling images to fixed diameter of 30.0 pixels
Training with rescale =  True
/home/saskra/PycharmProjects/cellpose/cellpose/transforms.py:366: UserWarning: 'chan2 (opt)' has value range of ZERO, can instead set chan2 to 0
  warnings.warn("'chan2 (opt)' has value range of ZERO, can instead set chan2 to 0")
2021-09-21 10:39:13,507 [INFO] train channels = 2
2021-09-21 10:39:13,788 [INFO] test channels = 2
2021-09-21 10:39:13,788 [INFO] flows precomputed
2021-09-21 10:39:14,605 [INFO] flows precomputed
>>> Using RAdam optimizer
2021-09-21 10:39:16,632 [INFO] >>>> training network with 2 channel input <<<<
2021-09-21 10:39:16,633 [INFO] >>>> saving every 100 epochs
2021-09-21 10:39:16,633 [INFO] >>>> median diameter = 30
2021-09-21 10:39:16,633 [INFO] >>>> LR: 0.20000, batch_size: 8, weight_decay: 0.00001
2021-09-21 10:39:16,633 [INFO] >>>> ntrain = 540
2021-09-21 10:39:16,633 [INFO] >>>> rescale is 1
2021-09-21 10:39:16,633 [INFO] >>>> ntest = 68
2021-09-21 10:39:16,633 [INFO] (2, 383, 512)
Traceback (most recent call last):
  File "/home/saskra/anaconda3/envs/cellpose/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/saskra/anaconda3/envs/cellpose/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/saskra/PycharmProjects/cellpose/cellpose/__main__.py", line 383, in <module>
    main()
  File "/home/saskra/PycharmProjects/cellpose/cellpose/__main__.py", line 356, in main
    cpmodel_path = model.train(images, labels, train_files=image_names,
  File "/home/saskra/PycharmProjects/cellpose/cellpose/models.py", line 912, in train
    model_path = self._train_net(train_data, train_flows, 
  File "/home/saskra/PycharmProjects/cellpose/cellpose/core.py", line 903, in _train_net
    imgi, lbl, scale = transforms.random_rotate_and_resize(
  File "/home/saskra/PycharmProjects/cellpose/cellpose/transforms.py", line 654, in random_rotate_and_resize
    return original_random_rotate_and_resize(X, Y=[Y[i][1:] for i in inds], scale_range=scale_range, xy=xy,
  File "/home/saskra/PycharmProjects/cellpose/cellpose/transforms.py", line 654, in <listcomp>
    return original_random_rotate_and_resize(X, Y=[Y[i][1:] for i in inds], scale_range=scale_range, xy=xy,
IndexError: list index out of range
```

And in fact X and Y are lists with only 8 entries, while this is the content of inds: [ 71 391 493 233 140 446 495 239]

**Comment by saskra** [comment]
I have rewritten this line https://github.com/MouseLand/cellpose/blob/ec859343f61988806093d65d0d6172f22596e9e7/cellpose/transforms.py#L654 like this 
```python 
return original_random_rotate_and_resize(X, Y=[Y[i][1:] for i in range(len(Y))], scale_range=scale_range, xy=xy,
```
and now the training starts.
