### ISSUE TITLE
ImportError: _arpack DLL load failed

### ISSUE THREAD

**Issue by ofrag** [MouseLand/cellpose#36]
HI,

I'm trying to install cellpose.
I followed the instructions to install using conda and environment.yml file 
when trying to run
  python -m cellspoe

i get the ImportError for _arpack, see below.

any advise would be appreciated
Thanks
Ofra
 

(cellpose) E:\Ofra_Sync\GitHub\cellpose>python -m cellpose
Traceback (most recent call last):
  File "C:\Users\ofrag\Anaconda3\envs\cellpose\lib\runpy.py", line 193, in _run_
module_as_main
    "__main__", mod_spec)
  File "C:\Users\ofrag\Anaconda3\envs\cellpose\lib\runpy.py", line 85, in _run_c
ode
    exec(code, run_globals)
  File "E:\Ofra_Sync\GitHub\cellpose\cellpose\__main__.py", line 7, in <module>
    from cellpose import utils, models, gui
  File "E:\Ofra_Sync\GitHub\cellpose\cellpose\utils.py", line 10, in <module>
    from cellpose import plot
  File "E:\Ofra_Sync\GitHub\cellpose\cellpose\plot.py", line 9, in <module>
    from skimage.segmentation import find_boundaries
  File "C:\Users\ofrag\Anaconda3\envs\cellpose\lib\site-packages\skimage\segment
ation\__init__.py", line 1, in <module>
    from .random_walker_segmentation import random_walker
  File "C:\Users\ofrag\Anaconda3\envs\cellpose\lib\site-packages\skimage\segment
ation\random_walker_segmentation.py", line 43, in <module>
    from ..filters import rank_order
  File "C:\Users\ofrag\Anaconda3\envs\cellpose\lib\site-packages\skimage\filters
\__init__.py", line 3, in <module>
    from .edges import (sobel, sobel_h, sobel_v,
  File "C:\Users\ofrag\Anaconda3\envs\cellpose\lib\site-packages\skimage\filters
\edges.py", line 17, in <module>
    from ..restoration.uft import laplacian
  File "C:\Users\ofrag\Anaconda3\envs\cellpose\lib\site-packages\skimage\restora
tion\__init__.py", line 5, in <module>
    from .deconvolution import wiener, unsupervised_wiener, richardson_lucy
  File "C:\Users\ofrag\Anaconda3\envs\cellpose\lib\site-packages\skimage\restora
tion\deconvolution.py", line 6, in <module>
    from scipy.signal import fftconvolve, convolve
  File "C:\Users\ofrag\Anaconda3\envs\cellpose\lib\site-packages\scipy\signal\__
init__.py", line 322, in <module>
    from .filter_design import *
  File "C:\Users\ofrag\Anaconda3\envs\cellpose\lib\site-packages\scipy\signal\fi
lter_design.py", line 18, in <module>
    from scipy import special, optimize, fftpack
  File "C:\Users\ofrag\Anaconda3\envs\cellpose\lib\site-packages\scipy\optimize\
__init__.py", line 387, in <module>
    from ._minimize import *
  File "C:\Users\ofrag\Anaconda3\envs\cellpose\lib\site-packages\scipy\optimize\
_minimize.py", line 30, in <module>
    from ._trustregion_constr import _minimize_trustregion_constr
  File "C:\Users\ofrag\Anaconda3\envs\cellpose\lib\site-packages\scipy\optimize\
_trustregion_constr\__init__.py", line 4, in <module>
    from .minimize_trustregion_constr import _minimize_trustregion_constr
  File "C:\Users\ofrag\Anaconda3\envs\cellpose\lib\site-packages\scipy\optimize\
_trustregion_constr\minimize_trustregion_constr.py", line 4, in <module>
    from scipy.sparse.linalg import LinearOperator
  File "C:\Users\ofrag\Anaconda3\envs\cellpose\lib\site-packages\scipy\sparse\li
nalg\__init__.py", line 117, in <module>
    from .eigen import *
  File "C:\Users\ofrag\Anaconda3\envs\cellpose\lib\site-packages\scipy\sparse\li
nalg\eigen\__init__.py", line 11, in <module>
    from .arpack import *
  File "C:\Users\ofrag\Anaconda3\envs\cellpose\lib\site-packages\scipy\sparse\li
nalg\eigen\arpack\__init__.py", line 22, in <module>
    from .arpack import *
  File "C:\Users\ofrag\Anaconda3\envs\cellpose\lib\site-packages\scipy\sparse\li
nalg\eigen\arpack\arpack.py", line 45, in <module>
    from . import _arpack
ImportError: DLL load failed: The specified procedure could not be found.

**Comment by ofrag** [comment]
reinstall scipy solved the issue

pip uninstall scipy
pip install scipy

**Comment by carsen-stringer** [comment]
i've added this info to the docs, thanks for figuring out a solution!
