### ISSUE TITLE
IndexError, fresh cellpose 0.7.2 + python=3.7

### ISSUE THREAD

**Issue by Mrc010** [MouseLand/cellpose#376]
I keep on getting this error when using the gui:

```
2021-11-18 20:08:36,685 [INFO] ** TORCH CUDA version installed and working. **
2021-11-18 20:08:36,685 [INFO] >>>> using GPU
2021-11-18 20:08:38,527 [WARNING] WARNING: not interp
Traceback (most recent call last):
  File "C:\Users\GeffJoldblum\miniconda3\lib\site-packages\cellpose\gui\gui.py", line 720, in calibrate_size
    diams, _ = self.model.sz.eval(self.stack[self.currentZ].copy(), invert=self.invert.isChecked(),
  File "C:\Users\GeffJoldblum\miniconda3\lib\site-packages\cellpose\models.py", line 985, in eval
    masks = self.cp.eval(x,
  File "C:\Users\GeffJoldblum\miniconda3\lib\site-packages\cellpose\models.py", line 613, in eval
    masks, styles, dP, dist, bd, p, tr = self._run_cp(x,
  File "C:\Users\GeffJoldblum\miniconda3\lib\site-packages\cellpose\models.py", line 725, in _run_cp
    masks[i], p[:,i], tr[i] = dynamics.compute_masks(dP[:,i], dist[i], bd[i],
  File "C:\Users\GeffJoldblum\miniconda3\lib\site-packages\cellpose\dynamics.py", line 892, in compute_masks
    mask = remove_bad_flow_masks(mask, flows, threshold=flow_threshold, use_gpu=use_gpu, device=device)
  File "C:\Users\GeffJoldblum\miniconda3\lib\site-packages\cellpose\dynamics.py", line 723, in remove_bad_flow_masks
    merrors, _ = metrics.flow_error(masks, flows, use_gpu, device, omni)
  File "C:\Users\GeffJoldblum\miniconda3\lib\site-packages\cellpose\metrics.py", line 283, in flow_error
    dP_masks = dynamics.masks_to_flows(maski, use_gpu=use_gpu, device=device, omni=omni)[idx]
  File "C:\Users\GeffJoldblum\miniconda3\lib\site-packages\cellpose\dynamics.py", line 374, in masks_to_flows
    mu, T = masks_to_flows_device(masks, dists=dists, device=device, omni=omni)
  File "C:\Users\GeffJoldblum\miniconda3\lib\site-packages\cellpose\dynamics.py", line 208, in masks_to_flows_gpu
    mu, T = _extend_centers_gpu(neighbors, centers, isneighbor, Ly, Lx,
  File "C:\Users\GeffJoldblum\miniconda3\lib\site-packages\cellpose\dynamics.py", line 111, in _extend_centers_gpu
    T[:, meds[:,0], meds[:,1]] += 1
IndexError: tensors used as indices must be long, byte or bool tensors
```

With the exception of `cudatoolkit=11.3`, I do everything as instructed for an installation on Windows 10.

**Comment by qixinbo** [comment]
Same error as yours. My env is `cudatoolkit=10.2.89`, also on Windows.

**Comment by kevinjohncutler** [comment]
The newest release requires Python 3.8 (I am running it on 3.8.1). Please let us know if you come across this issue for any 3.8 versions; I think up to 3.8.5 will work fine.
