### ISSUE TITLE
IndexError, fresh cellpose v0.7.2 + python=3.x

### ISSUE THREAD

**Issue by Mrc010** [MouseLand/cellpose#378]
With the exception of cudatoolkit=11.3, I do everything as instructed for an installation on Windows 10 and I get the
same issue with any version of python (3.7, 3.8.0, 3.8.1,...) - when I use the cellpose gui with any data, I get this error:
```
2021-11-19 09:46:47,088 [INFO] ** TORCH CUDA version installed and working. **
2021-11-19 09:46:47,088 [INFO] >>>> using GPU
2021-11-19 09:46:54,714 [WARNING] WARNING: not interp
Traceback (most recent call last):
  File "C:\Users\GeffJoldblum\Miniconda3\envs\cellpose\lib\site-packages\cellpose\gui\gui.py", line 720, in calibrate_size
    diams, _ = self.model.sz.eval(self.stack[self.currentZ].copy(), invert=self.invert.isChecked(),
  File "C:\Users\GeffJoldblum\Miniconda3\envs\cellpose\lib\site-packages\cellpose\models.py", line 985, in eval
    masks = self.cp.eval(x,
  File "C:\Users\GeffJoldblum\Miniconda3\envs\cellpose\lib\site-packages\cellpose\models.py", line 613, in eval
    masks, styles, dP, dist, bd, p, tr = self._run_cp(x,
  File "C:\Users\GeffJoldblum\Miniconda3\envs\cellpose\lib\site-packages\cellpose\models.py", line 725, in _run_cp
    masks[i], p[:,i], tr[i] = dynamics.compute_masks(dP[:,i], dist[i], bd[i],
  File "C:\Users\GeffJoldblum\Miniconda3\envs\cellpose\lib\site-packages\cellpose\dynamics.py", line 892, in compute_masks
    mask = remove_bad_flow_masks(mask, flows, threshold=flow_threshold, use_gpu=use_gpu, device=device)
  File "C:\Users\GeffJoldblum\Miniconda3\envs\cellpose\lib\site-packages\cellpose\dynamics.py", line 723, in remove_bad_flow_masks
    merrors, _ = metrics.flow_error(masks, flows, use_gpu, device, omni)
  File "C:\Users\GeffJoldblum\Miniconda3\envs\cellpose\lib\site-packages\cellpose\metrics.py", line 283, in flow_error
    dP_masks = dynamics.masks_to_flows(maski, use_gpu=use_gpu, device=device, omni=omni)[idx]
  File "C:\Users\GeffJoldblum\Miniconda3\envs\cellpose\lib\site-packages\cellpose\dynamics.py", line 374, in masks_to_flows
    mu, T = masks_to_flows_device(masks, dists=dists, device=device, omni=omni)
  File "C:\Users\GeffJoldblum\Miniconda3\envs\cellpose\lib\site-packages\cellpose\dynamics.py", line 208, in masks_to_flows_gpu
    mu, T = _extend_centers_gpu(neighbors, centers, isneighbor, Ly, Lx,
  File "C:\Users\GeffJoldblum\Miniconda3\envs\cellpose\lib\site-packages\cellpose\dynamics.py", line 111, in _extend_centers_gpu
    T[:, meds[:,0], meds[:,1]] += 1
IndexError: tensors used as indices must be long, byte or bool tensors
```
**I can confirm though that this error does not occur when using `pip install cellpose==0.6.5`** 
(as mentioned in #374)

**Comment by kevinjohncutler** [comment]
Applause is in order for "GeffJoldblum" haha. I've thoroughly tested the GUI in macOS and Ubuntu only, but I'll be looking into this Windows bug in the next few days. My hunch is that it is an issue with the cuda/pytorch/python versions. Are you running in a docker environment, a conda environment, or an anaconda shell?

**Comment by Mrc010** [comment]
:)
conda!

**Comment by giocard** [comment]
I get the same error (conda on Windows 10), and it does not depend on cuda, since I tried both cudatoolkit 10 and 11. 
Personally I could solve the issue by changing this line https://github.com/MouseLand/cellpose/blob/45f1a3c640efb8ca7d252712620af6f58d024c55/cellpose/dynamics.py#L104
to
`meds = torch.from_numpy(centers.astype(int)).to(torch.long).to(device)`
I hope it helps

**Comment by lacan** [comment]
Thanks @giocard for the advice. I can confirm that the error exists and that the fix works on a win10 installation using `pip install cellpose[all]` with torch 1.10 and CUDA 10.2

**Comment by sipie800** [comment]
same here win10 py38 torch11.3 cuda111

**Comment by rpsantosa** [comment]
> I get the same error (conda on Windows 10), and it does not depend on cuda, since I tried both cudatoolkit 10 and 11. Personally I could solve the issue by changing this line
> 
> https://github.com/MouseLand/cellpose/blob/45f1a3c640efb8ca7d252712620af6f58d024c55/cellpose/dynamics.py#L104
> 
> 
> to
> `meds = torch.from_numpy(centers.astype(int)).to(torch.long).to(device)`
> I hope it helps

Fixed some part, but even activating GPU ( by use_gpu = True), gpu memory loads, but everything runs on CPU.  /cuda 11.3 / pytorch 1.10/ Windows

**Comment by carsen-stringer** [comment]
thanks everyone for the debugging and the fix! this line is modified now, please  `pip install git+https://github.com/mouseland/cellpose.git`
