### ISSUE TITLE
How to train omnipose with 3D data?

### ISSUE THREAD

**Issue by gatoniel** [MouseLand/cellpose#412]
Hi,
I really like the ideas behind omnipose and cellpose and want to test the frameworks on our own data. Therefore, I want to train networks from scratch with our own 3D-Data. We have only one channel, and xyz axes.

While it is obvious how to predict on 3D with 'do_3D=True' as defined here https://github.com/MouseLand/cellpose/blob/45f1a3c640efb8ca7d252712620af6f58d024c55/cellpose/models.py#L422 
I really have trouble to find an analoguos definition for the 'train' function. I have the following code
```
from cellpose.models import CellposeModel


model = CellposeModel(
        gpu=True,
        diam_mean=0,
        omni=True,
        nclasses=4,
        nchan=1,
    )

model.train(
    X_trn, Y_trn, test_data=X_val, test_labels=Y_val,
    save_path=save_path,
    save_every=1,
    n_epochs=descr["train_epochs"],
    batch_size=descr["batch_size"],
    normalize=False,
    rescale=False,
    omni=True,
)
```
'X_trn', etc. are lists of 3d images. This produces the following output in the logs
```
2021-12-21 21:22:22,169 [INFO] >>>> training network with 64 channel input <<<<
```
Furthermore, this creates the following error
```
Traceback (most recent call last):
  File "/scicore/home/dresch0000/netter0000/drescherlab/dl-image-analysis-pipeline/.snakemake/scripts/tmpucpi3aqr.train.py", line 146, in <module>
    model.train(
  File "/scicore/home/dresch0000/netter0000/drescherlab/dl-image-analysis-pipeline/.snakemake/conda/b3c4598267cdac99d2bfe0adf7669ef4/lib/python3.9/site-packages/cellpose/models.py", line 846, in train
    model_path = self._train_net(train_data, train_flows,
  File "/scicore/home/dresch0000/netter0000/drescherlab/dl-image-analysis-pipeline/.snakemake/conda/b3c4598267cdac99d2bfe0adf7669ef4/lib/python3.9/site-packages/cellpose/core.py", line 928, in _train_net
    imgi, lbl, scale = transforms.random_rotate_and_resize(
  File "/scicore/home/dresch0000/netter0000/drescherlab/dl-image-analysis-pipeline/.snakemake/conda/b3c4598267cdac99d2bfe0adf7669ef4/lib/python3.9/site-packages/cellpose/transforms.py", line 658, in random_rotate_and_resize
    return omnipose.core.random_rotate_and_resize(X, Y=Y, scale_range=scale_range, gamma_range=gamma_range,
  File "/scicore/home/dresch0000/netter0000/drescherlab/dl-image-analysis-pipeline/.snakemake/conda/b3c4598267cdac99d2bfe0adf7669ef4/lib/python3.9/site-packages/cellpose/omnipose/core.py", line 321, in random_rotate_and_resize
    imgi[n], lbl[n], scale[n] = random_crop_warp(img, y, nt, xy, nchan, scale[n],
  File "/scicore/home/dresch0000/netter0000/drescherlab/dl-image-analysis-pipeline/.snakemake/conda/b3c4598267cdac99d2bfe0adf7669ef4/lib/python3.9/site-packages/cellpose/omnipose/core.py", line 416, in random_crop_warp
    imgi[k] = random_noise(imgi[k], mode="poisson")
  File "/scicore/home/dresch0000/netter0000/drescherlab/dl-image-analysis-pipeline/.snakemake/conda/b3c4598267cdac99d2bfe0adf7669ef4/lib/python3.9/site-packages/skimage/util/noise.py", line 192, in random_noise
    out = rng.poisson(image * vals) / float(vals)
  File "_generator.pyx", line 3067, in numpy.random._generator.Generator.poisson
  File "_common.pyx", line 824, in numpy.random._common.disc
  File "_common.pyx", line 621, in numpy.random._common.discrete_broadcast_d
  File "_common.pyx", line 350, in numpy.random._common.check_array_constraint
ValueError: lam value too large
```
However, I guess that this error is created due to the vast number of assumed channels. So when I can get Omnipose to regard these images as 3D Stacks, I guess this error will vanish.

Furtermore, if I use a list of 4d images with shape Z * N_channels * X * Y as mentioned in your documentation I get the error
```
Traceback (most recent call last):
  File "/scicore/home/dresch0000/netter0000/drescherlab/dl-image-analysis-pipeline/.snakemake/scripts/tmps7xxxk6c.train.py", line 151, in <module>
    model.train(
  File "/scicore/home/dresch0000/netter0000/drescherlab/dl-image-analysis-pipeline/.snakemake/conda/b3c4598267cdac99d2bfe0adf7669ef4/lib/python3.9/site-packages/cellpose/models.py", line 836, in train
    train_data, train_labels, test_data, test_labels, run_test = transforms.reshape_train_test(train_data, train_labels,
  File "/scicore/home/dresch0000/netter0000/drescherlab/dl-image-analysis-pipeline/.snakemake/conda/b3c4598267cdac99d2bfe0adf7669ef4/lib/python3.9/site-packages/cellpose/transforms.py", line 426, in reshape_train_test
    raise ValueError(error_message)
ValueError: training data is more than three-dimensional (should be 2D or 3D array)
```
I would really appreciate any help.

**Comment by alxndrkalinin** [comment]
See this comment: https://github.com/MouseLand/cellpose/issues/54#issuecomment-626248531

**Comment by carsen-stringer** [comment]
yes please check out that comment and the paper -- the model is never trained in 3D only with 2D slices from 3D volumes

**Comment by gatoniel** [comment]
Hey,
thank's for your responses. It might be useful to add a convenience 3D train function, that takes in 3D Volumes, slices them, and feeds them to the 2D training.

**Comment by kapoorlab** [comment]
Is it still true that cellpose can not be trained on 3D volumes? I have about 50K 3D raw + label data and I was going to make a training script like above to train a cellpose model but if it is only 2D still then I have to slice it before training.
