### ISSUE TITLE
Cellpose will not start: "No module named 'ncolor'"

### ISSUE THREAD

**Issue by znamensk** [MouseLand/cellpose#420]
Clean install in a brand new conda environment using `python -m pip install cellpose[all]`

```
Traceback (most recent call last):
  File "/Users/znamenp/opt/miniconda3/envs/cellpose/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/Users/znamenp/opt/miniconda3/envs/cellpose/lib/python3.8/runpy.py", line 144, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/Users/znamenp/opt/miniconda3/envs/cellpose/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/Users/znamenp/code/cellpose/cellpose/__init__.py", line 1, in <module>
    from .io import logger_setup
  File "/Users/znamenp/code/cellpose/cellpose/io.py", line 8, in <module>
    import ncolor
ModuleNotFoundError: No module named 'ncolor'
```

**Comment by znamensk** [comment]
Ah! Just saw it's fixed in the latest commit but must've not made it to the pip version yet.
