### ISSUE TITLE
RuntimeError: running_mean should contain 1 elements not 2

### ISSUE THREAD

**Issue by saskra** [MouseLand/cellpose#429]
This code:

```python
model = models.CellposeModel(gpu=True)
print("Size of images: " + str(len(imgs_train)) + " * " + str(imgs_train[0].shape))
print("Size of masks: " + str(len(masks_train)) + " * " + str(masks_train[0].shape))
model.train(imgs_train, masks_train, save_path=model_path)
```

Gives this output:
```shell
Size of images: 462 * (480, 480)
Size of masks: 462 * (480, 480)
100%|██████████| 462/462 [00:50<00:00,  9.23it/s]
Traceback (most recent call last):
  File "/snap/pycharm-professional/269/plugins/python/helpers/pydev/pydevd.py", line 1483, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/snap/pycharm-professional/269/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/saskra/PycharmProjects/a/run_cellpose_loocv.py", line 107, in <module>
    model.train(imgs_train, masks_train, save_path=model_path)
  File "/home/saskra/anaconda3/envs/a/lib/python3.9/site-packages/cellpose/models.py", line 855, in train
    model_path = self._train_net(train_data, train_flows, 
  File "/home/saskra/anaconda3/envs/a/lib/python3.9/site-packages/cellpose/core.py", line 928, in _train_net
    train_loss = self._train_step(imgi, lbl)
  File "/home/saskra/anaconda3/envs/a/lib/python3.9/site-packages/cellpose/core.py", line 768, in _train_step
    y = self.net(X)[0]
  File "/home/saskra/anaconda3/envs/a/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/saskra/anaconda3/envs/a/lib/python3.9/site-packages/cellpose/resnet_torch.py", line 192, in forward
    T0    = self.downsample(data)
  File "/home/saskra/anaconda3/envs/a/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/saskra/anaconda3/envs/a/lib/python3.9/site-packages/cellpose/resnet_torch.py", line 84, in forward
    xd.append(self.down[n](y))
  File "/home/saskra/anaconda3/envs/a/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/saskra/anaconda3/envs/a/lib/python3.9/site-packages/cellpose/resnet_torch.py", line 47, in forward
    x = self.proj(x) + self.conv[1](self.conv[0](x))
  File "/home/saskra/anaconda3/envs/a/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/saskra/anaconda3/envs/a/lib/python3.9/site-packages/torch/nn/modules/container.py", line 141, in forward
    input = module(input)
  File "/home/saskra/anaconda3/envs/a/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/saskra/anaconda3/envs/a/lib/python3.9/site-packages/torch/nn/modules/batchnorm.py", line 168, in forward
    return F.batch_norm(
  File "/home/saskra/anaconda3/envs/a/lib/python3.9/site-packages/torch/nn/functional.py", line 2282, in batch_norm
    return torch.batch_norm(
RuntimeError: running_mean should contain 1 elements not 2
```

What does this mean?

**Comment by carsen-stringer** [comment]
the default cellpose model is declared with `nchan=2`, so you need to run it with images with 2 channels or use the optional `channels` input during training, e.g. `channels=[0,0]` for grayscale. I've added a warning for users who don't use the channels input with the default model

**Comment by Aymen480** [comment]
Hello ,
I wanted to train a 2 channel imageset with the cellpose 3 neuirips cellpose default model but I got this error "RuntimeError: running_mean should contain 2 elements not 3".
and if I add a zero torch tensor here for the image, then the training process will have a bad effect.
Is there perhaps another way so that I can convert the image like with the Transformer or is it not worth it?
