### ISSUE TITLE
ImportError: cannot import name 'OMNI_INSTALLED' from partially initialized module 'cellpose.io'

### ISSUE THREAD

**Issue by saskra** [MouseLand/cellpose#430]
Has anything changed in the new version? I did an update and my previously working script is no longer running.

```shell
Python 3.9.7 (default, Sep 16 2021, 13:09:58) 
[GCC 7.5.0] :: Anaconda, Inc. on linux

>>> from cellpose import io, models
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/saskra/anaconda3/envs/a/lib/python3.9/site-packages/cellpose/io.py", line 9, in <module>
    from . import utils, plot, transforms
  File "/home/saskra/anaconda3/envs/a/lib/python3.9/site-packages/cellpose/utils.py", line 13, in <module>
    from . import metrics
  File "/home/saskra/anaconda3/envs/a/lib/python3.9/site-packages/cellpose/metrics.py", line 2, in <module>
    from . import utils, dynamics
  File "/home/saskra/anaconda3/envs/a/lib/python3.9/site-packages/cellpose/dynamics.py", line 16, in <module>
    from .io import OMNI_INSTALLED
ImportError: cannot import name 'OMNI_INSTALLED' from partially initialized module 'cellpose.io' (most likely due to a circular import) (/home/saskra/anaconda3/envs/a/lib/python3.9/site-packages/cellpose/io.py)
>>> 
```

**Comment by jo-mueller** [comment]
I get the same error message when using cellpose-napari. For me the error occurs when I try to open some of the sample data:

```
File ~\anaconda3\envs\napari_cellpose\lib\site-packages\cellpose_napari\_sample_data.py:15, in _load_cellpose_data(image_name='rgb_3D.tif', dname='Cells (3D+2Ch)')
     13 def _load_cellpose_data(image_name, dname):
     14     # Import when users select one of sample data
---> 15     from cellpose.io import imread
     16     from cellpose.utils import download_url_to_file
     18     cp_dir = pathlib.Path.home().joinpath('.cellpose')

File ~\anaconda3\envs\napari_cellpose\lib\site-packages\cellpose\io.py:9, in <module>
      6 import logging, pathlib, sys
      7 from pathlib import Path
----> 9 from . import utils, plot, transforms
     11 try:
     12     from omnipose.utils import format_labels

File ~\anaconda3\envs\napari_cellpose\lib\site-packages\cellpose\utils.py:13, in <module>
     10 import colorsys
     11 import io
---> 13 from . import metrics
     14 try:
     15     import omnipose, ncolor

File ~\anaconda3\envs\napari_cellpose\lib\site-packages\cellpose\metrics.py:2, in <module>
      1 import numpy as np
----> 2 from . import utils, dynamics
      3 from numba import jit
      4 from scipy.optimize import linear_sum_assignment

File ~\anaconda3\envs\napari_cellpose\lib\site-packages\cellpose\dynamics.py:16, in <module>
     13 dynamics_logger = logging.getLogger(__name__)
     15 from . import utils, metrics, transforms
---> 16 from .io import OMNI_INSTALLED
     18 try:
     19     import torch

ImportError: cannot import name 'OMNI_INSTALLED' from partially initialized module 'cellpose.io' (most likely due to a circular import) (C:\Users\johan\anaconda3\envs\napari_cellpose\lib\site-packages\cellpose\io.py)
Entering debugger. Type 'q' to return to napari.
```

**Comment by jo-mueller** [comment]
The problem has also been mentioned [here](https://github.com/MouseLand/cellpose-napari/issues/21). Downgrading cellpose to 0.6.5 fixed the issue for me:

```
pip install cellpose==0.6.5
```
