### ISSUE TITLE
Training error: AttributeError: 'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by JunMa11** [MouseLand/cellpose#439]
Dear CellPose,

I have checked all the image and ground truth files in the training set by the following code.
```python
for gt_name, img_name in zip(mask_names, img_names):
    gt = io.imread(join(s_path, gt_name))
    img = io.imread(join(s_path, img_names))
    
    assert gt.shape==(256,256), print(name, 'shape error')
    assert img.shape==(256,256,3), print(name, 'shape error')
```

However, I have this weird problem during training. Have you encountered similar problems? Any comments would be highly appreciated.

```
2022-02-10 22:23:53,615 [INFO] WRITING LOG OUTPUT TO /home/jma/.cellpose/run.log
2022-02-10 22:23:58,019 [INFO] ** TORCH CUDA version installed and working. **
2022-02-10 22:23:58,020 [INFO] >>>> using GPU
2022-02-10 22:48:17,027 [CRITICAL] ERROR: could not read file, 'NoneType' object has no attribute 'ndim'
Not all flows are present. Run flow generation again.
2022-02-11 00:50:25,063 [INFO] >>>> training from scratch
2022-02-11 00:50:25,193 [INFO] >>>> during training rescaling images to fixed diameter of 30.0 pixels
2022-02-11 00:50:26,036 [INFO] Training with rescale = 1.00
Traceback (most recent call last):
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/python/3.8.10/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/python/3.8.10/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jma/codes/cellpose2/lib/python3.8/site-packages/cellpose/__main__.py", line 458, in <module>
    main()
  File "/home/jma/codes/cellpose2/lib/python3.8/site-packages/cellpose/__main__.py", line 429, in main
    cpmodel_path = model.train(images, labels, train_files=image_names,
  File "/home/jma/codes/cellpose2/lib/python3.8/site-packages/cellpose/models.py", line 858, in train
    train_data, train_labels, test_data, test_labels, run_test = transforms.reshape_train_test(train_data, train_labels,
  File "/home/jma/codes/cellpose2/lib/python3.8/site-packages/cellpose/transforms.py", line 442, in reshape_train_test
    train_data, test_data, run_test = reshape_and_normalize_data(train_data, test_data=test_data, 
  File "/home/jma/codes/cellpose2/lib/python3.8/site-packages/cellpose/transforms.py", line 499, in reshape_and_normalize_data
    data[i] = move_min_dim(data[i], force=True)
  File "/home/jma/codes/cellpose2/lib/python3.8/site-packages/cellpose/transforms.py", line 225, in move_min_dim
    if len(img.shape) > 2: #only makese sense to do this if channel axis is already present 
AttributeError: 'NoneType' object has no attribute 'shape'
```

**Comment by carsen-stringer** [comment]
sorry I think this is an empty masks issue, did some of your images not have masks? this has been fixed in the latest release `pip install git+https://github.com/mouseland/cellpose.git`. if that's not the issue let me know and I'll reopen the issue
