### ISSUE TITLE
RuntimeError: std::bad_alloc

### ISSUE THREAD

**Issue by saskra** [MouseLand/cellpose#441]
Does anyone have an explanation for this error message?

```shell
python -m cellpose --dir /data/images/ --diameter 0 --savedir cpresults --verbose
2022-02-14 11:11:06,536 [INFO] WRITING LOG OUTPUT TO /home/saskra/.cellpose/run.log
2022-02-14 11:11:06,536 [INFO] >>>> using CPU
2022-02-14 11:11:06,543 [INFO] >>>> running cellpose on 150 images using chan_to_seg GRAY and chan (opt) NONE
2022-02-14 11:11:06,543 [INFO] >>>> using CPU
2022-02-14 11:11:06,639 [INFO] >>>> estimating diameter for each image
2022-02-14 11:11:06,640 [INFO] 0%|          | 0/150 [00:00<?, ?it/s]
2022-02-14 11:11:06,644 [WARNING] TiffPage 0: TypeError: read_bytes() missing 3 required positional arguments: 'dtype', 'count', and 'offsetsize'
2022-02-14 11:11:06,644 [INFO] ~~~ ESTIMATING CELL DIAMETER(S) ~~~
2022-02-14 11:11:07,568 [INFO] 0%|          | 0/150 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/saskra/anaconda3/envs/dead_cells/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/saskra/anaconda3/envs/dead_cells/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/saskra/anaconda3/envs/dead_cells/lib/python3.9/site-packages/cellpose/__main__.py", line 458, in <module>
    main()
  File "/home/saskra/anaconda3/envs/dead_cells/lib/python3.9/site-packages/cellpose/__main__.py", line 317, in main
    out = model.eval(image, channels=channels, diameter=diameter,
  File "/home/saskra/anaconda3/envs/dead_cells/lib/python3.9/site-packages/cellpose/models.py", line 262, in eval
    diams, _ = self.sz.eval(x, channels=channels, channel_axis=channel_axis, invert=invert, batch_size=batch_size, 
  File "/home/saskra/anaconda3/envs/dead_cells/lib/python3.9/site-packages/cellpose/models.py", line 1022, in eval
    masks = self.cp.eval(x, 
  File "/home/saskra/anaconda3/envs/dead_cells/lib/python3.9/site-packages/cellpose/models.py", line 628, in eval
    masks, styles, dP, cellprob, p, bd, tr = self._run_cp(x, 
  File "/home/saskra/anaconda3/envs/dead_cells/lib/python3.9/site-packages/cellpose/models.py", line 694, in _run_cp
    yf, style = self._run_nets(img, net_avg=net_avg,
  File "/home/saskra/anaconda3/envs/dead_cells/lib/python3.9/site-packages/cellpose/core.py", line 398, in _run_nets
    y, style = self._run_net(img, augment=augment, tile=tile, tile_overlap=tile_overlap,
  File "/home/saskra/anaconda3/envs/dead_cells/lib/python3.9/site-packages/cellpose/core.py", line 479, in _run_net
    y, style = self._run_tiled(imgs, augment=augment, bsize=bsize, 
  File "/home/saskra/anaconda3/envs/dead_cells/lib/python3.9/site-packages/cellpose/core.py", line 580, in _run_tiled
    y0, style = self.network(IMG[irange], return_conv=return_conv)
  File "/home/saskra/anaconda3/envs/dead_cells/lib/python3.9/site-packages/cellpose/core.py", line 345, in network
    self.net = mkldnn_utils.to_mkldnn(self.net)
  File "/home/saskra/anaconda3/envs/dead_cells/lib/python3.9/site-packages/torch/utils/mkldnn.py", line 210, in to_mkldnn
    return m_fn_rec(module, dtype)
  File "/home/saskra/anaconda3/envs/dead_cells/lib/python3.9/site-packages/torch/utils/mkldnn.py", line 207, in m_fn_rec
    setattr(new_m, name, m_fn_rec(sub_m, d))
  File "/home/saskra/anaconda3/envs/dead_cells/lib/python3.9/site-packages/torch/utils/mkldnn.py", line 207, in m_fn_rec
    setattr(new_m, name, m_fn_rec(sub_m, d))
  File "/home/saskra/anaconda3/envs/dead_cells/lib/python3.9/site-packages/torch/utils/mkldnn.py", line 207, in m_fn_rec
    setattr(new_m, name, m_fn_rec(sub_m, d))
  [Previous line repeated 3 more times]
  File "/home/saskra/anaconda3/envs/dead_cells/lib/python3.9/site-packages/torch/utils/mkldnn.py", line 205, in m_fn_rec
    new_m = m_fn(m, d)
  File "/home/saskra/anaconda3/envs/dead_cells/lib/python3.9/site-packages/torch/utils/mkldnn.py", line 200, in m_fn
    return MkldnnBatchNorm(m)
  File "/home/saskra/anaconda3/envs/dead_cells/lib/python3.9/site-packages/torch/jit/_script.py", line 265, in init_then_script
    original_init(self, *args, **kwargs)
  File "/home/saskra/anaconda3/envs/dead_cells/lib/python3.9/site-packages/torch/utils/mkldnn.py", line 148, in __init__
    self.register_buffer('weight', dense_module.weight.to_mkldnn())
RuntimeError: std::bad_alloc
```

PS: This only happens with the current version from this Github repository, not with the previous version 1.0.

**Comment by kevinjohncutler** [comment]
Does this happen if you set up an anaconda environment with a different python version, e.g. 3.8.5?

**Comment by saskra** [comment]
In fact, it does not. With Python version 3.8.5, Cellpose 1.0.1 is apparently compatible.

**Comment by kevinjohncutler** [comment]
Ok good, we have run into this issue (or similar) before; I'm guessing the version of pytorch requires 3.8.5. The environment.yml provided configures python to 3.8.5 to avoid these issues. Eventually Carsen or I will get around to updating the dependencies to the latest versions and iron out any bugs that follow. We should also update the install instructions to make this clearer (right now it just says python 3.8).

**Comment by saskra** [comment]
I wanted to use the Cellpose pip package in an existing environment along with other packages, which in turn rely on Python >3.9. But then I try to work around that somehow, e.g. with Snakemake. Thanks in any case for the help.
