### ISSUE TITLE
NameError: name 'step_factor' is not defined

### ISSUE THREAD

**Issue by ElpadoCan** [MouseLand/cellpose#456]
I just installed `cellpose 1.0.1` and I get the following errors when I try to `import models`. I have `numba v0.55.1` with Python 3.8.5. I am on Windows 10 64bit, no GPU.

```
>>> from cellpose import models
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Frank\venvs\acdc\lib\site-packages\cellpose\models.py", line 11, in <module>
    from . import transforms, dynamics, utils, plot
  File "C:\Users\Frank\venvs\acdc\lib\site-packages\cellpose\transforms.py", line 8, in <module>
    from . import dynamics, utils
  File "C:\Users\Frank\venvs\acdc\lib\site-packages\cellpose\dynamics.py", line 488, in <module>
    def steps2D(p, dP, inds, niter, omni=False, calc_trace=False):
  File "C:\Users\Frank\venvs\acdc\lib\site-packages\numba\core\decorators.py", line 219, in wrapper
    disp.compile(sig)
  File "C:\Users\Frank\venvs\acdc\lib\site-packages\numba\core\dispatcher.py", line 965, in compile
    cres = self._compiler.compile(args, return_type)
  File "C:\Users\Frank\venvs\acdc\lib\site-packages\numba\core\dispatcher.py", line 129, in compile
    raise retval
  File "C:\Users\Frank\venvs\acdc\lib\site-packages\numba\core\dispatcher.py", line 139, in _compile_cached
    retval = self._compile_core(args, return_type)
  File "C:\Users\Frank\venvs\acdc\lib\site-packages\numba\core\dispatcher.py", line 152, in _compile_core
    cres = compiler.compile_extra(self.targetdescr.typing_context,
  File "C:\Users\Frank\venvs\acdc\lib\site-packages\numba\core\compiler.py", line 693, in compile_extra
    return pipeline.compile_extra(func)
  File "C:\Users\Frank\venvs\acdc\lib\site-packages\numba\core\compiler.py", line 429, in compile_extra
    return self._compile_bytecode()
  File "C:\Users\Frank\venvs\acdc\lib\site-packages\numba\core\compiler.py", line 497, in _compile_bytecode
    return self._compile_core()
  File "C:\Users\Frank\venvs\acdc\lib\site-packages\numba\core\compiler.py", line 476, in _compile_core
    raise e
  File "C:\Users\Frank\venvs\acdc\lib\site-packages\numba\core\compiler.py", line 463, in _compile_core
    pm.run(self.state)
  File "C:\Users\Frank\venvs\acdc\lib\site-packages\numba\core\compiler_machinery.py", line 353, in run
    raise patched_exception
  File "C:\Users\Frank\venvs\acdc\lib\site-packages\numba\core\compiler_machinery.py", line 341, in run
    self._runPass(idx, pass_inst, state)
  File "C:\Users\Frank\venvs\acdc\lib\site-packages\numba\core\compiler_lock.py", line 35, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "C:\Users\Frank\venvs\acdc\lib\site-packages\numba\core\compiler_machinery.py", line 296, in _runPass
    mutated |= check(pss.run_pass, internal_state)
  File "C:\Users\Frank\venvs\acdc\lib\site-packages\numba\core\compiler_machinery.py", line 269, in check
    mangled = func(compiler_state)
  File "C:\Users\Frank\venvs\acdc\lib\site-packages\numba\core\typed_passes.py", line 105, in run_pass
    typemap, return_type, calltypes, errs = type_inference_stage(
  File "C:\Users\Frank\venvs\acdc\lib\site-packages\numba\core\typed_passes.py", line 81, in type_inference_stage
    infer.build_constraint()
  File "C:\Users\Frank\venvs\acdc\lib\site-packages\numba\core\typeinfer.py", line 1039, in build_constraint
    self.constrain_statement(inst)
  File "C:\Users\Frank\venvs\acdc\lib\site-packages\numba\core\typeinfer.py", line 1386, in constrain_statement
    self.typeof_assign(inst)
  File "C:\Users\Frank\venvs\acdc\lib\site-packages\numba\core\typeinfer.py", line 1459, in typeof_assign
    self.typeof_global(inst, inst.target, value)
  File "C:\Users\Frank\venvs\acdc\lib\site-packages\numba\core\typeinfer.py", line 1559, in typeof_global
    typ = self.resolve_value_type(inst, gvar.value)
  File "C:\Users\Frank\venvs\acdc\lib\site-packages\numba\core\typeinfer.py", line 1480, in resolve_value_type
    raise TypingError(msg, loc=inst.loc)
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
NameError: name 'step_factor' is not defined
```

**Comment by ElpadoCan** [comment]
It seems like the file `dynamics.py` uses a function called `steps_factor` that is not defined right? I did a search in the entire package and it is not defined anywhere.

**Comment by ElpadoCan** [comment]
Found that function on the developer version. Please let me know when you are going to fix the version on PyPi, thanks!
