### ISSUE TITLE
urllib.error.URLError while trying to start cellpose

### ISSUE THREAD

**Issue by Mimi-cracra** [MouseLand/cellpose#459]
Hello, I have been using cellpose on previous computers but just tried now to install it on a new one and after setting-up the environment and downloading as recommended (I use windows), I receive the following error and the GUI doesn't start -I wonder if you could have an idea about how to fix it? I also couldn't find a work around so far. Thank you for the help! :)

`(cellpose) C:\Users\amand>cellpose
2022-03-01 21:34:20,862 [INFO] WRITING LOG OUTPUT TO C:\Users\amand\.cellpose\run.log
downloading logo
Traceback (most recent call last):
  File "C:\Users\amand\.conda\envs\cellpose\lib\urllib\request.py", line 1350, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "C:\Users\amand\.conda\envs\cellpose\lib\http\client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\amand\.conda\envs\cellpose\lib\http\client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\amand\.conda\envs\cellpose\lib\http\client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\amand\.conda\envs\cellpose\lib\http\client.py", line 1010, in _send_output
    self.send(msg)
  File "C:\Users\amand\.conda\envs\cellpose\lib\http\client.py", line 950, in send
    self.connect()
  File "C:\Users\amand\.conda\envs\cellpose\lib\http\client.py", line 1424, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "C:\Users\amand\.conda\envs\cellpose\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Users\amand\.conda\envs\cellpose\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "C:\Users\amand\.conda\envs\cellpose\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\amand\.conda\envs\cellpose\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\amand\.conda\envs\cellpose\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\amand\.conda\envs\cellpose\Scripts\cellpose.exe\__main__.py", line 7, in <module>
  File "C:\Users\amand\.conda\envs\cellpose\lib\site-packages\cellpose\__main__.py", line 168, in main
    gui.run()
  File "C:\Users\amand\.conda\envs\cellpose\lib\site-packages\cellpose\gui\gui.py", line 137, in run
    download_url_to_file('https://www.cellpose.org/static/images/cellpose_transparent.png', icon_path, progress=True)
  File "C:\Users\amand\.conda\envs\cellpose\lib\site-packages\cellpose\utils.py", line 69, in download_url_to_file
    u = urlopen(url)
  File "C:\Users\amand\.conda\envs\cellpose\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\amand\.conda\envs\cellpose\lib\urllib\request.py", line 525, in open
    response = self._open(req, data)
  File "C:\Users\amand\.conda\envs\cellpose\lib\urllib\request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "C:\Users\amand\.conda\envs\cellpose\lib\urllib\request.py", line 502, in _call_chain
    result = func(*args)
  File "C:\Users\amand\.conda\envs\cellpose\lib\urllib\request.py", line 1393, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "C:\Users\amand\.conda\envs\cellpose\lib\urllib\request.py", line 1353, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 2] No such file or directory>`

**Comment by Mimi-cracra** [comment]
This turned out to be simply a firewall issue
