### ISSUE TITLE
Installing Issue with LLVM.

### ISSUE THREAD

**Issue by lambda-science** [MouseLand/cellpose#462]
Hello,

When trying to install cellpose package using pip (via Poetry environnement manager) I get an error during installation due to `llvmlite v0.34.0`
Here are the main errors:
```python-traceback
 FileNotFoundError: [Errno 2] No such file or directory: 'llvm-config'
 RuntimeError: llvm-config failed executing, please point LLVM_CONFIG to the path for llvm-config
```
Do I need to `sudo apt install llvmlite` for Cellpose to work ? It that something that is required ?  
Full traceback is availiable at the end.

Have a nice day,
-Corentin

PS: I'm running Python 3.9.7 and tried installed Cellpose 1.0.2
PPS: Here's my LLVM installed
```
❯ dpkg -l | grep "llvm"
ii  libllvm6.0:amd64                             1:6.0-1ubuntu2                                  amd64        Modular compiler and toolchain technologies, runtime library
ii  libllvm8:amd64                               1:8-3~ubuntu18.04.2                             amd64        Modular compiler and toolchain technologies, runtime library
ii  libllvm9:amd64                               1:9-2~ubuntu18.04.2                             amd64        Modular compiler and toolchain technologies, runtime library
ii  llvm-6.0                                     1:6.0-1ubuntu2                                  amd64        Modular compiler and toolchain technologies
ii  llvm-6.0-dev                                 1:6.0-1ubuntu2                                  amd64        Modular compiler and toolchain technologies, libraries and headers
ii  llvm-6.0-runtime                             1:6.0-1ubuntu2                                  amd64        Modular compiler and toolchain technologies, IR interpreter
```
I guess I need llvm-8-dev or 9-dev ?

Full Trace-back:
```python-traceback
❯ poetry install
Installing dependencies from lock file

Package operations: 10 installs, 0 updates, 0 removals

  • Installing llvmlite (0.34.0): Failed

  EnvCommandError

  Command ['/home/meyer/.cache/pypoetry/virtualenvs/img-explore-dHQUGiWh-py3.9/bin/pip', 'install', '--no-deps', 'file:///home/meyer/.cache/pypoetry/artifacts/49/df/e0/694d912a8276f46ee1f2185bcaff0c82689123b6963fadf3c2f306f7ff/llvmlite-0.34.0.tar.gz'] errored with the following return code 1, and output: 
  Processing /home/meyer/.cache/pypoetry/artifacts/49/df/e0/694d912a8276f46ee1f2185bcaff0c82689123b6963fadf3c2f306f7ff/llvmlite-0.34.0.tar.gz
  Building wheels for collected packages: llvmlite
    Building wheel for llvmlite (setup.py): started
    Building wheel for llvmlite (setup.py): finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /enadisk/maison/genomics18/meyer/.cache/pypoetry/virtualenvs/img-explore-dHQUGiWh-py3.9/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-b_p9vpvr/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-b_p9vpvr/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-bcvq6dnv
         cwd: /tmp/pip-req-build-b_p9vpvr/
    Complete output (26 lines):
    running bdist_wheel
    /enadisk/maison/genomics18/meyer/.cache/pypoetry/virtualenvs/img-explore-dHQUGiWh-py3.9/bin/python /tmp/pip-req-build-b_p9vpvr/ffi/build.py
    LLVM version... Traceback (most recent call last):
      File "/tmp/pip-req-build-b_p9vpvr/ffi/build.py", line 105, in main_posix
        out = subprocess.check_output([llvm_config, '--version'])
      File "/home/meyer/miniconda3/lib/python3.9/subprocess.py", line 424, in check_output
        return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
      File "/home/meyer/miniconda3/lib/python3.9/subprocess.py", line 505, in run
        with Popen(*popenargs, **kwargs) as process:
      File "/home/meyer/miniconda3/lib/python3.9/subprocess.py", line 951, in __init__
        self._execute_child(args, executable, preexec_fn, close_fds,
      File "/home/meyer/miniconda3/lib/python3.9/subprocess.py", line 1821, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: 'llvm-config'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/tmp/pip-req-build-b_p9vpvr/ffi/build.py", line 191, in <module>
        main()
      File "/tmp/pip-req-build-b_p9vpvr/ffi/build.py", line 181, in main
        main_posix('linux', '.so')
      File "/tmp/pip-req-build-b_p9vpvr/ffi/build.py", line 107, in main_posix
        raise RuntimeError("%s failed executing, please point LLVM_CONFIG "
    RuntimeError: llvm-config failed executing, please point LLVM_CONFIG to the path for llvm-config
    error: command '/enadisk/maison/genomics18/meyer/.cache/pypoetry/virtualenvs/img-explore-dHQUGiWh-py3.9/bin/python' failed with exit code 1
    ----------------------------------------
    ERROR: Failed building wheel for llvmlite
    Running setup.py clean for llvmlite
  Failed to build llvmlite
  Installing collected packages: llvmlite
      Running setup.py install for llvmlite: started
      Running setup.py install for llvmlite: finished with status 'error'
      ERROR: Command errored out with exit status 1:
       command: /enadisk/maison/genomics18/meyer/.cache/pypoetry/virtualenvs/img-explore-dHQUGiWh-py3.9/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-b_p9vpvr/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-b_p9vpvr/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-zp5xzdfk/install-record.txt --single-version-externally-managed --compile --install-headers /enadisk/maison/genomics18/meyer/.cache/pypoetry/virtualenvs/img-explore-dHQUGiWh-py3.9/include/site/python3.9/llvmlite
           cwd: /tmp/pip-req-build-b_p9vpvr/
      Complete output (29 lines):
      running install
      running build
      got version from file /tmp/pip-req-build-b_p9vpvr/llvmlite/_version.py {'version': '0.34.0', 'full': 'c5889c9e98c6b19d5d85ebdd982d64a03931f8e2'}
      running build_ext
      /enadisk/maison/genomics18/meyer/.cache/pypoetry/virtualenvs/img-explore-dHQUGiWh-py3.9/bin/python /tmp/pip-req-build-b_p9vpvr/ffi/build.py
      LLVM version... Traceback (most recent call last):
        File "/tmp/pip-req-build-b_p9vpvr/ffi/build.py", line 105, in main_posix
          out = subprocess.check_output([llvm_config, '--version'])
        File "/home/meyer/miniconda3/lib/python3.9/subprocess.py", line 424, in check_output
          return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
        File "/home/meyer/miniconda3/lib/python3.9/subprocess.py", line 505, in run
          with Popen(*popenargs, **kwargs) as process:
        File "/home/meyer/miniconda3/lib/python3.9/subprocess.py", line 951, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "/home/meyer/miniconda3/lib/python3.9/subprocess.py", line 1821, in _execute_child
          raise child_exception_type(errno_num, err_msg, err_filename)
      FileNotFoundError: [Errno 2] No such file or directory: 'llvm-config'
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/tmp/pip-req-build-b_p9vpvr/ffi/build.py", line 191, in <module>
          main()
        File "/tmp/pip-req-build-b_p9vpvr/ffi/build.py", line 181, in main
          main_posix('linux', '.so')
        File "/tmp/pip-req-build-b_p9vpvr/ffi/build.py", line 107, in main_posix
          raise RuntimeError("%s failed executing, please point LLVM_CONFIG "
      RuntimeError: llvm-config failed executing, please point LLVM_CONFIG to the path for llvm-config
      error: command '/enadisk/maison/genomics18/meyer/.cache/pypoetry/virtualenvs/img-explore-dHQUGiWh-py3.9/bin/python' failed with exit code 1
      ----------------------------------------
  ERROR: Command errored out with exit status 1: /enadisk/maison/genomics18/meyer/.cache/pypoetry/virtualenvs/img-explore-dHQUGiWh-py3.9/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-b_p9vpvr/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-b_p9vpvr/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-zp5xzdfk/install-record.txt --single-version-externally-managed --compile --install-headers /enadisk/maison/genomics18/meyer/.cache/pypoetry/virtualenvs/img-explore-dHQUGiWh-py3.9/include/site/python3.9/llvmlite Check the logs for full command output.
  WARNING: You are using pip version 21.1.1; however, version 22.0.3 is available.
  You should consider upgrading via the '/enadisk/maison/genomics18/meyer/.cache/pypoetry/virtualenvs/img-explore-dHQUGiWh-py3.9/bin/python -m pip install --upgrade pip' command.
  

  at ~/miniconda3/lib/python3.9/site-packages/poetry/utils/env.py:1075 in _run
      1071│                 output = subprocess.check_output(
      1072│                     cmd, stderr=subprocess.STDOUT, **kwargs
      1073│                 )
      1074│         except CalledProcessError as e:
    → 1075│             raise EnvCommandError(e, input=input_)
      1076│ 
      1077│         return decode(output)
      1078│ 
      1079│     def execute(self, bin, *args, **kwargs):

```

**Comment by lambda-science** [comment]
It seem's that CellPose rely on `numba 0.51.2` which relies on `llvmlite 0.34.0`
And based on https://github.com/numba/llvmlite `llvmlite 0.34.0` requiers `10.0.x (9.0.x for aarch64 only)`
So I guess I need the `llvm-10` and `llvm-10-dev` installed, I'll try it out !

Thanks

**Comment by lambda-science** [comment]
Well, even with llvm-10 installed it still throw the same error.
```
ii  libllvm10:amd64                              1:10.0.0-4ubuntu1~18.04.2                       amd64        Modular compiler and toolchain technologies, runtime library
ii  libllvm6.0:amd64                             1:6.0-1ubuntu2                                  amd64        Modular compiler and toolchain technologies, runtime library
ii  libllvm8:amd64                               1:8-3~ubuntu18.04.2                             amd64        Modular compiler and toolchain technologies, runtime library
ii  libllvm9:amd64                               1:9-2~ubuntu18.04.2                             amd64        Modular compiler and toolchain technologies, runtime library
ii  llvm-10                                      1:10.0.0-4ubuntu1~18.04.2                       amd64        Modular compiler and toolchain technologies
ii  llvm-10-dev                                  1:10.0.0-4ubuntu1~18.04.2                       amd64        Modular compiler and toolchain technologies, libraries and headers
ii  llvm-10-runtime                              1:10.0.0-4ubuntu1~18.04.2                       amd64        Modular compiler and toolchain technologies, IR interpreter
ii  llvm-10-tools                                1:10.0.0-4ubuntu1~18.04.2                       amd64        Modular compiler and toolchain technologies, tools
ii  llvm-6.0                                     1:6.0-1ubuntu2                                  amd64        Modular compiler and toolchain technologies
ii  llvm-6.0-dev                                 1:6.0-1ubuntu2                                  amd64        Modular compiler and toolchain technologies, libraries and headers
ii  llvm-6.0-runtime                             1:6.0-1ubuntu2                                  amd64        Modular compiler and toolchain technologies, IR interpreter
```

```
FileNotFoundError: [Errno 2] No such file or directory: 'llvm-config'
    RuntimeError: llvm-config failed executing, please point LLVM_CONFIG to the path for llvm-config
    error: command '/maison/genomics18/meyer/.cache/pypoetry/virtualenvs/img-explore-XNQhKc0--py3.9/bin/python' failed with exit code 1
    ----------------------------------------
    ERROR: Failed building wheel for llvmlite
RuntimeError: llvm-config failed executing, please point LLVM_CONFIG to the path for llvm-config
```
