### ISSUE TITLE
unsupported tensor layout: Mkldnn

### ISSUE THREAD

**Issue by arogozhnikov** [MouseLand/cellpose#504]
This happened with task in the cloud during model loading. 

Exception looks like previous files were overwritten in the cloud, and older version of cellpose can't open them.

Even more surprisingly, when I've run the same docker (without rebuilding or reinstalling cellpose), everything went smooth. May be a heisenbug, may be something with downloaded weights. I provide a full log in the end

Used environment:
```
cellpose==0.6.5
torch 1.8
python 3.8
ubuntu 20.04 (docker)
```

Full log:

```
Task 'segment_well[0]': Exception encountered during task execution!
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/prefect/engine/task_runner.py", line 880, in get_task_run_state
    value = prefect.utilities.executors.run_task_with_timeout(
  File "/usr/local/lib/python3.8/dist-packages/prefect/utilities/executors.py", line 468, in run_task_with_timeout
    return task.run(*args, **kwargs)  # type: ignore
  File "/tmp/ipykernel_1446/2901745394.py", line 30, in segment_well
  File "/tmp/ipykernel_1446/3933060375.py", line 18, in segment
  File "/usr/local/lib/python3.8/dist-packages/joblib/parallel.py", line 1046, in __call__
    while self.dispatch_one_batch(iterator):
  File "/usr/local/lib/python3.8/dist-packages/joblib/parallel.py", line 861, in dispatch_one_batch
    self._dispatch(tasks)
  File "/usr/local/lib/python3.8/dist-packages/joblib/parallel.py", line 779, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/usr/local/lib/python3.8/dist-packages/joblib/_parallel_backends.py", line 208, in apply_async
    result = ImmediateResult(func)
  File "/usr/local/lib/python3.8/dist-packages/joblib/_parallel_backends.py", line 572, in __init__
    self.results = batch()
  File "/usr/local/lib/python3.8/dist-packages/joblib/parallel.py", line 262, in __call__
    return [func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/joblib/parallel.py", line 262, in <listcomp>
    return [func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pipeline/analysis/immunofluorescence/modules/Segment.py", line 118, in run
    mask, _flows, _styles, _diams = segmenter.eval(
  File "/usr/local/lib/python3.8/dist-packages/cellpose/models.py", line 257, in eval
    masks, flows, styles = self.cp.eval(x,
  File "/usr/local/lib/python3.8/dist-packages/cellpose/models.py", line 511, in eval
    self.net.load_model(self.pretrained_model[0], cpu=(not self.gpu))
  File "/usr/local/lib/python3.8/dist-packages/cellpose/resnet_torch.py", line 220, in load_model
    self.load_state_dict(torch.load(filename, map_location=torch.device('cpu')))
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1223, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for CPnet:
	Unexpected key(s) in state_dict: "downsample.down.res_down_0.conv.conv_0.0.num_batches_tracked", "downsample.down.res_down_0.conv.conv_1.0.num_batches_tracked", "downsample.down.res_down_0.conv.conv_2.0.num_batches_tracked", "downsample.down.res_down_0.conv.conv_3.0.num_batches_tracked", "downsample.down.res_down_0.proj.0.num_batches_tracked", "downsample.down.res_down_1.conv.conv_0.0.num_batches_tracked", "downsample.down.res_down_1.conv.conv_1.0.num_batches_tracked", "downsample.down.res_down_1.conv.conv_2.0.num_batches_tracked", "downsample.down.res_down_1.conv.conv_3.0.num_batches_tracked", "downsample.down.res_down_1.proj.0.num_batches_tracked", "downsample.down.res_down_2.conv.conv_0.0.num_batches_tracked", "downsample.down.res_down_2.conv.conv_1.0.num_batches_tracked", "downsample.down.res_down_2.conv.conv_2.0.num_batches_tracked", "downsample.down.res_down_2.conv.conv_3.0.num_batches_tracked", "downsample.down.res_down_2.proj.0.num_batches_tracked", "downsample.down.res_down_3.conv.conv_0.0.num_batches_tracked", "downsample.down.res_down_3.conv.conv_1.0.num_batches_tracked", "downsample.down.res_down_3.conv.conv_2.0.num_batches_tracked", "downsample.down.res_down_3.conv.conv_3.0.num_batches_tracked", "downsample.down.res_down_3.proj.0.num_batches_tracked", "upsample.up.res_up_0.conv.conv_0.0.num_batches_tracked", "upsample.up.res_up_0.conv.conv_1.conv.0.num_batches_tracked", "upsample.up.res_up_0.conv.conv_2.conv.0.num_batches_tracked", "upsample.up.res_up_0.conv.conv_3.conv.0.num_batches_tracked", "upsample.up.res_up_0.proj.0.num_batches_tracked", "upsample.up.res_up_1.conv.conv_0.0.num_batches_tracked", "upsample.up.res_up_1.conv.conv_1.conv.0.num_batches_tracked", "upsample.up.res_up_1.conv.conv_2.conv.0.num_batches_tracked", "upsample.up.res_up_1.conv.conv_3.conv.0.num_batches_tracked", "upsample.up.res_up_1.proj.0.num_batches_tracked", "upsample.up.res_up_2.conv.conv_0.0.num_batches_tracked", "upsample.up.res_up_2.conv.conv_1.conv.0.num_batches_tracked", "upsample.up.res_up_2.conv.conv_2.conv.0.num_batches_tracked", "upsample.up.res_up_2.conv.conv_3.conv.0.num_batches_tracked", "upsample.up.res_up_2.proj.0.num_batches_tracked", "upsample.up.res_up_3.conv.conv_0.0.num_batches_tracked", "upsample.up.res_up_3.conv.conv_1.conv.0.num_batches_tracked", "upsample.up.res_up_3.conv.conv_2.conv.0.num_batches_tracked", "upsample.up.res_up_3.conv.conv_3.conv.0.num_batches_tracked", "upsample.up.res_up_3.proj.0.num_batches_tracked", "output.0.num_batches_tracked". 
	While copying the parameter named "downsample.down.res_down_0.conv.conv_0.0.weight", whose dimensions in the model are torch.Size([2]) and whose dimensions in the checkpoint are torch.Size([2]), an exception occurred : ('unsupported tensor layout: Mkldnn',).
	While copying the parameter named "downsample.down.res_down_0.conv.conv_0.0.bias", whose dimensions in the model are torch.Size([2]) and whose dimensions in the checkpoint are torch.Size([2]), an exception occurred : ('unsupported tensor layout: Mkldnn',).
	While copying the parameter named "downsample.down.res_down_0.conv.conv_0.0.running_mean", whose dimensions in the model are torch.Size([2]) and whose dimensions in the checkpoint are torch.Size([2]), an exception occurred : ('unsupported tensor layout: Mkldnn',).
	While copying the parameter named "downsample.down.res_down_0.conv.conv_0.0.running_var", whose dimensions in the model are torch.Size([2]) and whose dimensions in the checkpoint are torch.Size([2]), an exception occurred : ('unsupported tensor layout: Mkldnn',).
	While copying the parameter named "downsample.down.res_down_0.conv.conv_0.2.bias", whose dimensions in the model are torch.Size([32]) and whose dimensions in the checkpoint are torch.Size([32]), an exception occurred : ('unsupported tensor layout: Mkldnn',).
	While copying the parameter named "downsample.down.res_down_0.conv.conv_0.2.weight", whose dimensions in the model are torch.Size([32, 2, 3, 3]) and whose dimensions in the checkpoint are torch.Size([32, 2, 3, 3]), an exception occurred : ('unsupported tensor layout: Mkldnn',).
	While copying the parameter named "downsample.down.res_down_0.conv.conv_1.0.weight", whose dimensions in the model are torch.Size([32]) and whose dimensions in the checkpoint are torch.Size([32]), an exception occurred : ('unsupported tensor layout: Mkldnn',).
	While copying the parameter named "downsample.down.res_down_0.conv.conv_1.0.bias", whose dimensions in the model are torch.Size([32]) and whose dimensions in the checkpoint are torch.Size([32]), an exception occurred : ('unsupported tensor layout: Mkldnn',).
	While copying the parameter named "downsample.down.res_down_0.conv.conv_1.0.running_mean", whose dimensions in the model are torch.Size([32]) and whose dimensions in the checkpoint are torch.Size([32]), an exception occurred : ('unsupported tensor layout: Mkldnn',).
	While copying the parameter named "downsample.down.res_down_0.conv.conv_1.0.running_var", whose dimensions in the model are torch.Size([32]) and whose dimensions in the checkpoint are torch.Size([32]), an exception occurred : ('unsupported tensor layout: Mkldnn',).
	While copying the parameter named "downsample.down.res_down_0.conv.conv_1.2.bias", whose dimensions in the model are torch.Size([32]) and whose dimensions in the checkpoint are torch.Size([32]), an exception occurred : ('unsupported tensor layout: Mkldnn',).
	While copying the parameter named "downsample.down.res_down_0.conv.conv_1.2.weight", whose dimensions in the model are torch.Size([32, 32, 3, 3]) and whose dimensions in the checkpoint are torch.Size([32, 32, 3, 3]), an exception occurred : ('unsupported tensor layout: Mkldnn',).
	While copying the parameter named "downsample.down.res_down_0.conv.conv_2.0.weight", whose dimensions in the model are torch.Size([32]) and whose dimensions in the checkpoint are torch.Size([32]), an exception occurred : ('unsupported tensor layout: Mkldnn',).
	While copying the parameter named "downsample.down.res_down_0.conv.conv_2.0.bias", whose dimensions in the model are torch.Size([32]) and whose dimensions in the checkpoint are torch.Size([32]), an exception occurred : ('unsupported tensor layout: Mkldnn',).
	While copying the parameter named "downsample.down.res_down_0.conv.conv_2.0.running_mean", whose dimensions in the model are torch.Size([32]) and whose dimensions in the checkpoint are torch.Size([32]), an exception occurred : ('unsupported tensor layout: Mkldnn',).
	While copying the parameter named "downsample.down.res_down_0.conv.conv_2.0.running_var", whose dimensions in the model are torch.Size([32]) and whose dimensions in the checkpoint are torch.Size([32]), an exception occurred : ('unsupported tensor layout: Mkldnn',).
	While copying the parameter named "downsample.down.res_down_0.conv.conv_2.2.bias", whose dimensions in the model are torch.Size([32]) and whose dimensions in the checkpoint are torch.Size([32]), an exception occurred : ('unsupported tensor layout: Mkldnn',).
	While copying the parameter named "downsample.down.res_down_0.conv.conv_2.2.weight", whose dimensions in the model are torch.Size([32, 32, 3, 3]) and whose dimensions in the checkpoint are torch.Size([32, 32, 3, 3]), an exception occurred : ('unsupported tensor layout: Mkldnn',).
	While copying the parameter named "downsample.down.res_down_0.conv.conv_3.0.weight", whose dimensions in the model are torch.Size([32]) and whose dimensions in the checkpoint are torch.Size([32]), an exception occurred : ('unsupported tensor layout: Mkldnn',).
	While copying the parameter named "downsample.down.res_down_0.conv.conv_3.0.bias", whose dimensions in the model are torch.Size([32]) and whose dimensions in the checkpoint are torch.Size([32]), an exception occurred : ('unsupported tensor layout: Mkldnn',).
	While copying the parameter named "downsample.down.res_down_0.conv.conv_3.0.running_mean", whose dimensions in the model are torch.Size([32]) and whose dimensions in the checkpoint are torch.Size([32]), an exception occurred : ('unsupported tensor layout: Mkldnn',).
	While copying the parameter named "downsample.down.res_down_0.conv.conv_3.0.running_var", whose dimensions in the model are torch.Size([32]) and whose dimensions in the checkpoint are torch.Size([32]), an exception occurred : ('unsupported tensor layout: Mkldnn',).
	While copying the parameter named "downsample.down.res_down_0.conv.conv_3.2.bias", whose dimensions in the model are torch.Size([32]) and whose dimensions in the checkpoint are torch.Size([32]), an exception occurred : ('unsupported tensor layout: Mkldnn',).
	While copying the parameter named "downsample.down.res_down_0.conv.conv_3.2.weight", whose dimensions in the model are torch.Size([32, 32, 3, 3]) and whose dimensions in the checkpoint are torch.Size([32, 32, 3, 3]), an exception occurred : ('unsupported tensor layout: Mkldnn',).
	While copying the parameter named "downsample.down.res_down_0.proj.0.weight", whose dimensions in the model are torch.Size([2]) and whose dimensions in the checkpoint are torch.Size([2]), an exception occurred : ('unsupported tensor layout: Mkldnn',).
	While copying the parameter named "downsample.down.res_down_0.proj.0.bias", whose dimensions in the model are torch.Size([2]) and whose dimensions in the checkpoint are torch.Size([2]), an exception occurred : ('unsupported tensor layout: Mkldnn',).
	While copying the parameter named "downsample.down.res_down_0.proj.0.running_mean", whose dimensions in the model are torch.Size([2]) and whose dimensions in the checkpoint are torch.Size([2]), an exception occurred : ('unsupported tensor layout: Mkldnn',).
	While copying the parameter named "downsample.down.res_down_0.proj.0.running_var", whose dimensions in the model are torch.Size([2]) and whose dimensions in the checkpoint are torch.Size([2]), an exception occurred : ('unsupported tensor layout: Mkldnn',).
	While copying the parameter named "downsample.down.res_down_0.proj.1.bias", whose dimensions in the model are torch.Size([32]) and whose dimensions in the checkpoint are torch.Size([32]), an exception occurred : ('unsupported tensor layout: Mkldnn',).
	While copying the parameter named "downsample.down.res_down_0.proj.1.weight", whose dimensions in the model are torch.Size([32, 2, 1, 1]) and whose dimensions in the checkpoint are torch.Size([32, 2, 1, 1]), an exception occurred : ('unsupported tensor layout: Mkldnn',).
	While copying the parameter named "downsample.down.res_down_1.conv.conv_0.0.weight", whose dimensions in the model are torch.Size([32]) and whose dimensions in the checkpoint are torch.Size([32]), an exception occurred : ('unsupported tensor layout: Mkldnn',).
	While copying the parameter named "downsample.down.res_down_1.conv.conv_0.0.bias", whose dimensions in the model are torch.Size([32]) and whose dimensions in the checkpoint are torch.Size([32]), an exception occurred : ('unsupported tensor layout: Mkldnn',).
	While copying the parameter named "downsample.down.res_down_1.conv.conv_0.0.running_mean", whose dimensions in the model are torch.Size([32]) and whose dimensions in the checkpoint are torch.Size([32]), an exception occurred : ('unsupported tensor layout: Mkldnn',).
	While copying the parameter named "downsample.down.res_down_1.conv.conv_0.0.running_var", whose dimensions in the model are torch.Size([32]) and whose dimensions in the checkpoint are torch.Size([32]), an exception occurred : ('unsupported tensor layout: Mkldnn',).
	While copying the parameter named "downsample.down.res_down_1.conv.conv_0.2.bias", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('unsupported tensor layout: Mkldnn',).
	While copying the parameter named "downsample.down.res_down_1.conv.conv_0.2.weight", whose dimensions in the model are torch.Size([64, 32, 3, 3]) and whose dimensions in the checkpoint are torch.Size([64, 32, 3, 3]), an exception occurred : ('unsupported tensor layout: Mkldnn',).
	While copying the parameter named "downsample.down.res_down_1.conv.conv_1.0.weight", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('unsupported tensor layout: Mkldnn',).
	While copying the parameter named "downsample.down.res_down_1.conv.conv_1.0.bias", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('unsupported tensor layout: Mkldnn',).
	While copying the parameter named "downsample.down.res_down_1.conv.conv_1.0.running_mean", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('unsupported tensor layout: Mkldnn',).
	While copying the parameter named "downsample.down.res_down_1.conv.conv_1.0.running_var", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('unsupported tensor layout: Mkldnn',).
	While copying the parameter named "downsample.down.res_down_1.conv.conv_1.2.bias", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('unsupported tensor layout: Mkldnn',).
	While copying the parameter named "downsample.down.res_down_1.conv.conv_1.2.weight", whose dimensions in the model are torch.Size([64, 64, 3, 3]) and whose dimensions in the checkpoint are torch.Size([64, 64, 3, 3]), an exception occurred : ('unsupported tensor layout: Mkldnn',).
	While copying the parameter named "downsample.down.res_down_1.conv.conv_2.0.weight", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('unsupported tensor layout: Mkldnn',).
	While copying the parameter named "downsample.down.res_down_1.conv.conv_2.0.bias", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([64]), an exception occurred : ('unsupported tensor layout: Mkldnn',).
	

... skipped many similar lines ....

	While copying the parameter named "upsample.up.res_up_3.proj.0.running_var", whose dimensions in the model are torch.Size([256]) and whose dimensions in the checkpoint are torch.Size([256]), an exception occurred : ('unsupported tensor layout: Mkldnn',).
	While copying the parameter named "upsample.up.res_up_3.proj.1.bias", whose dimensions in the model are torch.Size([256]) and whose dimensions in the checkpoint are torch.Size([256]), an exception occurred : ('unsupported tensor layout: Mkldnn',).
	While copying the parameter named "upsample.up.res_up_3.proj.1.weight", whose dimensions in the model are torch.Size([256, 256, 1, 1]) and whose dimensions in the checkpoint are torch.Size([256, 256, 1, 1]), an exception occurred : ('unsupported tensor layout: Mkldnn',).
	While copying the parameter named "output.0.weight", whose dimensions in the model are torch.Size([32]) and whose dimensions in the checkpoint are torch.Size([32]), an exception occurred : ('unsupported tensor layout: Mkldnn',).
	While copying the parameter named "output.0.bias", whose dimensions in the model are torch.Size([32]) and whose dimensions in the checkpoint are torch.Size([32]), an exception occurred : ('unsupported tensor layout: Mkldnn',).
	While copying the parameter named "output.0.running_mean", whose dimensions in the model are torch.Size([32]) and whose dimensions in the checkpoint are torch.Size([32]), an exception occurred : ('unsupported tensor layout: Mkldnn',).
	While copying the parameter named "output.0.running_var", whose dimensions in the model are torch.Size([32]) and whose dimensions in the checkpoint are torch.Size([32]), an exception occurred : ('unsupported tensor layout: Mkldnn',).
	While copying the parameter named "output.2.bias", whose dimensions in the model are torch.Size([3]) and whose dimensions in the checkpoint are torch.Size([3]), an exception occurred : ('unsupported tensor layout: Mkldnn',).
	While copying the parameter named "output.2.weight", whose dimensions in the model are torch.Size([3, 32, 1, 1]) and whose dimensions in the checkpoint are torch.Size([3, 32, 1, 1]), an exception occurred : ('unsupported tensor layout: Mkldnn',).
```

**Comment by arogozhnikov** [comment]
Potentially relevant torch issue: https://github.com/pytorch/pytorch/issues/32697

**Comment by carsen-stringer** [comment]
sorry I'm not sure what is wrong here, perhaps redeclaring the model would help? this is not an error I've seen before. please upgrade to the latest cellpose version and if it's still giving you trouble reopen the issue

**Comment by arogozhnikov** [comment]
For posterity: I had this issue when running cellpose in threads (multiple cellpose models created independently and evaluated). When limited to a single thread, issue seems to not reappear. 

Yeah, fine with closing this issue.
