### ISSUE TITLE
GPU out of memory

### ISSUE THREAD

**Issue by quentin67100** [MouseLand/cellpose#520]
Hi, 

i run cellpose on a cluster with A100 gpu. I update to the last version. I run the command : 

`python -m cellpose --dir ${images_dir} --pretrained_model cyto --chan 0 --no_npy --save_txt --diameter 80 --use_gpu`

I get the following error :

2022-05-31 19:38:35,098 [INFO] ** TORCH CUDA version installed and working. **
2022-05-31 19:38:35,099 [INFO] >>>> using GPU
2022-05-31 19:38:35,106 [INFO] >>>> running cellpose on 18 images using chan_to_seg GRAY and chan (opt) NONE
2022-05-31 19:38:35,106 [INFO] ** TORCH CUDA version installed and working. **
2022-05-31 19:38:35,106 [INFO] >>>> using GPU
2022-05-31 19:38:35,106 [INFO] >> cyto << model set to be used
2022-05-31 19:38:35,216 [INFO] >>>> model diam_mean =  30.000 (ROIs rescaled to this size during training)
2022-05-31 19:38:35,218 [INFO] >>>> using diameter 80.000 for all images
2022-05-31 19:38:35,223 [INFO] 0%|          | 0/18 [00:00<?, ?it/s]
2022-05-31 19:38:35,297 [INFO] ~~~ FINDING MASKS ~~~
2022-05-31 19:39:50,145 [INFO] 0%|          | 0/18 [01:14<?, ?it/s]
Traceback (most recent call last):
  File "/shared/space2/laporte/labo6_laporte1/Quentin_C/conda/conda_envs/cellpose_2.0/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/shared/space2/laporte/labo6_laporte1/Quentin_C/conda/conda_envs/cellpose_2.0/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/shared/space2/laporte/labo6_laporte1/Quentin_C/conda/conda_envs/cellpose_2.0/lib/python3.8/site-packages/cellpose/__main__.py", line 348, in <module>
    main()
  File "/shared/space2/laporte/labo6_laporte1/Quentin_C/conda/conda_envs/cellpose_2.0/lib/python3.8/site-packages/cellpose/__main__.py", line 232, in main
    out = model.eval(image, channels=channels, diameter=diameter,
  File "/shared/space2/laporte/labo6_laporte1/Quentin_C/conda/conda_envs/cellpose_2.0/lib/python3.8/site-packages/cellpose/models.py", line 238, in eval
    masks, flows, styles = self.cp.eval(x,
  File "/shared/space2/laporte/labo6_laporte1/Quentin_C/conda/conda_envs/cellpose_2.0/lib/python3.8/site-packages/cellpose/models.py", line 551, in eval
    masks, styles, dP, cellprob, p = self._run_cp(x,
  File "/shared/space2/laporte/labo6_laporte1/Quentin_C/conda/conda_envs/cellpose_2.0/lib/python3.8/site-packages/cellpose/models.py", line 651, in _run_cp
    outputs = dynamics.compute_masks(dP[:,i], cellprob[i], niter=niter, cellprob_threshold=cellprob_threshold,
  File "/shared/space2/laporte/labo6_laporte1/Quentin_C/conda/conda_envs/cellpose_2.0/lib/python3.8/site-packages/cellpose/dynamics.py", line 726, in compute_masks
    mask = remove_bad_flow_masks(mask, dP, threshold=flow_threshold, use_gpu=use_gpu, device=device)
  File "/shared/space2/laporte/labo6_laporte1/Quentin_C/conda/conda_envs/cellpose_2.0/lib/python3.8/site-packages/cellpose/dynamics.py", line 581, in remove_bad_flow_masks
    merrors, _ = metrics.flow_error(masks, flows, use_gpu, device)
  File "/shared/space2/laporte/labo6_laporte1/Quentin_C/conda/conda_envs/cellpose_2.0/lib/python3.8/site-packages/cellpose/metrics.py", line 282, in flow_error
    dP_masks = dynamics.masks_to_flows(maski, use_gpu=use_gpu, device=device)
  File "/shared/space2/laporte/labo6_laporte1/Quentin_C/conda/conda_envs/cellpose_2.0/lib/python3.8/site-packages/cellpose/dynamics.py", line 278, in masks_to_flows
    mu, mu_c = masks_to_flows_device(masks, device=device)
  File "/shared/space2/laporte/labo6_laporte1/Quentin_C/conda/conda_envs/cellpose_2.0/lib/python3.8/site-packages/cellpose/dynamics.py", line 153, in masks_to_flows_gpu
    mu = _extend_centers_gpu(neighbors, centers, isneighbor, Ly, Lx,
  File "/shared/space2/laporte/labo6_laporte1/Quentin_C/conda/conda_envs/cellpose_2.0/lib/python3.8/site-packages/cellpose/dynamics.py", line 70, in _extend_centers_gpu
    pt = torch.from_numpy(neighbors).to(device)
RuntimeError: CUDA out of memory. Tried to allocate 13.66 GiB (GPU 0; 19.62 GiB total capacity; 25.27 MiB already allocated; 12.90 GiB free; 28.00 MiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

Any idea to solve the issue ? My images are tiff between 112Mo and 884Mo

**Comment by carsen-stringer** [comment]
it seems like you might have been running something else on the GPU if it can't use the full GPU? but regardless you can decrease the batch size with for example `--batch_size 2`

**Comment by quentin67100** [comment]
I try to use the option --batch_size 2 but i get the same error. Nothing else run on the gpu so i don't understand and i don't know how to fix it.

**Comment by Huimin721** [comment]
> I try to use the option --batch_size 2 but i get the same error. Nothing else run on the gpu so i don't understand and i don't know how to fix it.

Hi did you figure out the issue? I got the same error with the largest GPU on the server but still met the error.

**Comment by quentin67100** [comment]
> > I try to use the option --batch_size 2 but i get the same error. Nothing else run on the gpu so i don't understand and i don't know how to fix it.
> 
> Hi did you figure out the issue? I got the same error with the largest GPU on the server but still met the error.

No. I went back to the cpu version even though it takes much longer.

**Comment by Huimin721** [comment]
> > > I try to use the option --batch_size 2 but i get the same error. Nothing else run on the gpu so i don't understand and i don't know how to fix it.
> > 
> > 
> > Hi did you figure out the issue? I got the same error with the largest GPU on the server but still met the error.
> 
> No. I went back to the cpu version even though it takes much longer.

Jesus. Thanks for the information! Will try GPU for the last time with batch size = 2, otherwise will go with CPU!
By the way for CPU version, is it just delete --use_gpu in my command?

**Comment by lambda-science** [comment]
Hey same issue.
I'm trying to use python to segment a whole slide image. It's an ome.tif file of 20 megabytes (compressed), 450 megabytes uncompressed,  something like 10.000x15.000 pixels.
I tried for several hours to troubleshot the issue but I just don't understand where it comes from.

I'm running a simple:
```python
def run_cellpose(image, model_cellpose, diameter=None):
    channel = [[0, 0]]
    mask_cellpose, _, _, _ = model_cellpose.eval(
        image, diameter=diameter, channels=channel
    )
    return mask_cellpose
```
And I'm getting an error after a few minutes

```python-traceback
RuntimeError: CUDA out of memory. Tried to allocate 3.03 GiB (GPU 0; 10.76 GiB total 
capacity; 7.61 GiB already allocated; 1.90 GiB free; 7.61 GiB reserved in total by 
PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to 
avoid fragmentation.  See documentation for Memory Management and 
PYTORCH_CUDA_ALLOC_CONF
```

**Comment by carsen-stringer** [comment]
I think that if you are running in a notebook, pytorch may be holding onto memory? but I would try `--batch_size 2`

**Comment by yliu7366** [comment]
Same issue on a 2D grayscale image with the size of (37678, 66107)

RuntimeError: CUDA out of memory. Tried to allocate 5.53 GiB (GPU 0; 31.75 GiB total capacity; 29.84 GiB already allocated; 882.50 MiB free; 29.86 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

This was done on a computing node with 320GB system memory and one 32GB VRAM v100x GPU. Given the fact that cellpose does tiling under the hood, this error doesn't make much sense to me. Smaller images such as 20,000 by 20,000 can be processed without issue.

**Comment by chenzhao2016** [comment]
Just want to follow up and see if anyone has solved this issue.

**Comment by lambda-science** [comment]
Tried downgrading from cellpose 2.1.1 to 2.0.5 as I have a friend that use it sucessfully, still the same error.

**Comment by carsen-stringer** [comment]
this is the QC step that's failing (where cellpose throws out masks which don't have flows that are similar to the model's predicted flows), you can turn it off by setting `flow_threshold=0`. 

alternatively, I am setting a check for this that estimates the amount of memory remaining on the GPU to decide whether or not to run the step on the GPU, try it out with `pip install git+https://github.com/mouseland/cellpose.git`

**Comment by eddietheegale** [comment]
Yes I am also getting a similar error of CUDA out of memory even when I limit the batch size, it happens mostly when trying to do 3D analysis
I also have access to a GPU with about 140GB vram so technically this should not be the limiting factor no?
I have tried varying the amount of z-stacks included in the 3D analysis, and for smaller files (~100 MB) the code works fine, but as soon as try the entire Z-stack (~500 MB to 1 GB) it crashes... totally, sometimes even without an error...

Has anyone else experienced a total system crash(not just a script error) when running Cellpose, particularly with large 3D datasets? Could this be related to specific NVIDIA drivers, CUDA versions, or a known interaction with PyTorch memory management? Are there any known workarounds or things to check to prevent the driver/system crash?

Thanks!
