### ISSUE TITLE
Double right clicking causes error state

### ISSUE THREAD

**Issue by karimali34** [MouseLand/cellpose#55]
Accidentally double right-clicking happens to some of our users when trying to draw ROIs, and it causes an error state the program stops functioning essentially, since it's stuck trying to draw the ROI

```
|==============================>>
    |  Traceback (most recent call last):
    |    File "/home/karim/anaconda3/envs/suite2p/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    |      "__main__", mod_spec)
    |    File "/home/karim/anaconda3/envs/suite2p/lib/python3.7/runpy.py", line 85, in _run_code
    |      exec(code, run_globals)
    |    File "/home/karim/anaconda3/envs/suite2p/lib/python3.7/site-packages/cellpose/__main__.py", line 96, in <module>
    |      gui.run()
    |    File "/home/karim/anaconda3/envs/suite2p/lib/python3.7/site-packages/cellpose/gui.py", line 119, in run
    |      ret = app.exec_()
    |    File "/home/karim/anaconda3/envs/suite2p/lib/python3.7/site-packages/pyqtgraph/widgets/GraphicsView.py", line 355, in mouseReleaseEvent
    |      QtGui.QGraphicsView.mouseReleaseEvent(self, ev)
    |    File "/home/karim/anaconda3/envs/suite2p/lib/python3.7/site-packages/pyqtgraph/GraphicsScene/GraphicsScene.py", line 199, in mouseReleaseEvent
    |      if self.sendClickEvent(cev[0]):
    |    File "/home/karim/anaconda3/envs/suite2p/lib/python3.7/site-packages/pyqtgraph/GraphicsScene/GraphicsScene.py", line 335, in sendClickEvent
    |      debug.printExc("Error sending click event:")
    |    --- exception caught here ---
    |    File "/home/karim/anaconda3/envs/suite2p/lib/python3.7/site-packages/pyqtgraph/GraphicsScene/GraphicsScene.py", line 333, in sendClickEvent
    |      acceptedItem.mouseClickEvent(ev)
    |    File "/home/karim/anaconda3/envs/suite2p/lib/python3.7/site-packages/cellpose/guiparts.py", line 247, in mouseClickEvent
    |      self.end_stroke()
    |    File "/home/karim/anaconda3/envs/suite2p/lib/python3.7/site-packages/cellpose/guiparts.py", line 322, in end_stroke
    |      self.parent.add_set()
    |    File "/home/karim/anaconda3/envs/suite2p/lib/python3.7/site-packages/cellpose/gui.py", line 944, in add_set
    |      median = self.add_mask(points=self.current_point_set, color=color)
    |    File "/home/karim/anaconda3/envs/suite2p/lib/python3.7/site-packages/cellpose/gui.py", line 975, in add_mask
    |      vr, vc = draw.polygon_perimeter(vr, vc, self.layers[z].shape[:2])
    |    File "/home/karim/anaconda3/envs/suite2p/lib/python3.7/site-packages/skimage/draw/draw.py", line 241, in polygon_perimeter
    |      r, c = polygon_clip(r, c, *clip_box)
    |    File "/home/karim/anaconda3/envs/suite2p/lib/python3.7/site-packages/skimage/_shared/_geometry.py", line 31, in polygon_clip
    |      poly_clipped = poly.clip_to_bbox(clip_rect).to_polygons()[0]
    |  IndexError: list index out of range
    |==============================<<
```

**Comment by carsen-stringer** [comment]
thanks for reporting this bug it's been fixed
~~~
pip install cellpose --upgrade
~~~
please comment if you're still having problems
