### ISSUE TITLE
Conflicting requirements !

### ISSUE THREAD

**Issue by ajay1685** [MouseLand/cellpose#57]
I created conda environment with provided yml file, then installed Cellpose using `pip install cellpose[gui]`  command. When I try to launch Cellpose gui I get the following error. 

```(cellpose-v1) C:\Users\zalavaa>python -m cellpose
Downloading: "http://www.cellpose.org/models/cyto_0" to C:\Users\zalavaa\.cellpose\models\cyto_0
Traceback (most recent call last):
  File "C:\Users\zalavaa\.conda\envs\cellpose-v1\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\zalavaa\.conda\envs\cellpose-v1\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\zalavaa\.conda\envs\cellpose-v1\lib\site-packages\cellpose\__main__.py", line 96, in <module>
    gui.run()
  File "C:\Users\zalavaa\.conda\envs\cellpose-v1\lib\site-packages\cellpose\gui.py", line 117, in run
    models.download_model_weights()
  File "C:\Users\zalavaa\.conda\envs\cellpose-v1\lib\site-packages\cellpose\models.py", line 854, in download_model_weights
    utils.download_url_to_file(url, cached_file, progress=True)
  File "C:\Users\zalavaa\.conda\envs\cellpose-v1\lib\site-packages\cellpose\utils.py", line 30, in download_url_to_file
    u = urlopen(url)
  File "C:\Users\zalavaa\.conda\envs\cellpose-v1\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\zalavaa\.conda\envs\cellpose-v1\lib\urllib\request.py", line 531, in open
    response = meth(req, response)
  File "C:\Users\zalavaa\.conda\envs\cellpose-v1\lib\urllib\request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Users\zalavaa\.conda\envs\cellpose-v1\lib\urllib\request.py", line 563, in error
    result = self._call_chain(*args)
  File "C:\Users\zalavaa\.conda\envs\cellpose-v1\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "C:\Users\zalavaa\.conda\envs\cellpose-v1\lib\urllib\request.py", line 755, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "C:\Users\zalavaa\.conda\envs\cellpose-v1\lib\urllib\request.py", line 531, in open
    response = meth(req, response)
  File "C:\Users\zalavaa\.conda\envs\cellpose-v1\lib\urllib\request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Users\zalavaa\.conda\envs\cellpose-v1\lib\urllib\request.py", line 569, in error
    return self._call_chain(*args)
  File "C:\Users\zalavaa\.conda\envs\cellpose-v1\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "C:\Users\zalavaa\.conda\envs\cellpose-v1\lib\urllib\request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 401: Unauthorized
```
What is a correct way of installing cellpose.

**Comment by ajay1685** [comment]
And, here are the errors I got when I tried to install correct version of requests :

```ERROR: mxnet-mkl 1.5.0 has requirement requests<2.19.0,>=2.18.4, but you'll have requests 2.23.0 which is incompatible.```

then if I install(downgrade to) 2.18.4, i see the following error

```ERROR: tensorboard 2.1.1 has requirement requests<3,>=2.21.0, but you'll have requests 2.18.4 which is incompatible.```

**Comment by carsen-stringer** [comment]
I haven't seen this issue before. But that second error is fine - we don't use tensorflow/tensorboard. My requests version after creating the environment.yml environment is `requests==2.18.4` and `urllib3==1.22`

you can also directly download and move the models into the `$HOME/.cellpose/models` folder (the models are `cyto_j` and `nuclei_j` where j is 0-3 and are at www.cellpose.org/models/ (e.g. [www.cellpose.org/models/cyto_0](www.cellpose.org/models/cyto_0))

**Comment by carsen-stringer** [comment]
was this resolved? it seems like the tensorboard error is not a problem, did you try to run it after that?
