### ISSUE TITLE
Can't load livecell model

### ISSUE THREAD

**Issue by constantinpape** [MouseLand/cellpose#570]
I am trying to load the [livecell model](https://github.com/MouseLand/cellpose/blob/72217a59d30020cd5c4272d6d49c8fc160535654/docs/models.rst#livecell-models), but it fails with an HTTP error (the same code works for the cyto and nuclei models):
```py
from cellpose import models
device, gpu = models.assign_device(True, False)

# loading the cyto model: works
# model = models.Cellpose(gpu=gpu, model_type="cyto", device=device)

# loading the livecell model: fails with HTTP error
model = models.Cellpose(gpu=gpu, model_type="livecell", device=device)
```
fails with the following traceback:
```
Traceback (most recent call last):
  File "cellpose_livecell.py", line 6, in <module>
    model = models.Cellpose(gpu=gpu, model_type="blub", device=device)
  File "/home/pape/software/conda/miniconda3/envs/cellpose/lib/python3.8/site-packages/cellpose/models.py", line 92, in __init__
    self.cp = CellposeModel(device=self.device, gpu=self.gpu,
  File "/home/pape/software/conda/miniconda3/envs/cellpose/lib/python3.8/site-packages/cellpose/models.py", line 345, in __init__
    pretrained_model = [model_path(pretrained_model_string, j, self.torch) for j in model_range]
  File "/home/pape/software/conda/miniconda3/envs/cellpose/lib/python3.8/site-packages/cellpose/models.py", line 345, in <listcomp>
    pretrained_model = [model_path(pretrained_model_string, j, self.torch) for j in model_range]
  File "/home/pape/software/conda/miniconda3/envs/cellpose/lib/python3.8/site-packages/cellpose/models.py", line 28, in model_path
    return cache_model_path(basename)
  File "/home/pape/software/conda/miniconda3/envs/cellpose/lib/python3.8/site-packages/cellpose/models.py", line 41, in cache_model_path
    utils.download_url_to_file(url, cached_file, progress=True)
  File "/home/pape/software/conda/miniconda3/envs/cellpose/lib/python3.8/site-packages/cellpose/utils.py", line 64, in download_url_to_file
    u = urlopen(url)
  File "/home/pape/software/conda/miniconda3/envs/cellpose/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/home/pape/software/conda/miniconda3/envs/cellpose/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/home/pape/software/conda/miniconda3/envs/cellpose/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/home/pape/software/conda/miniconda3/envs/cellpose/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/home/pape/software/conda/miniconda3/envs/cellpose/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/home/pape/software/conda/miniconda3/envs/cellpose/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 500: INTERNAL SERVER ERROR
```
It would be very helpful if this could be fixed to use cellpose for phase-contrast data, as the current `cyto` model is working poorly on it. I have cellpose version 2.1.0 installed.

**Comment by carsen-stringer** [comment]
sorry for the confusion. the `Cellpose` class is only for models with size models. to use livecell please use `CellposeModel`, please see more info here: https://cellpose.readthedocs.io/en/latest/models.html#other-built-in-models

**Comment by constantinpape** [comment]
Thanks that works!
