### ISSUE TITLE
AttributeError: type object 'QPalette' has no attribute 'Base'.

### ISSUE THREAD

**Issue by ElpadoCan** [MouseLand/cellpose#592]
I installed cellpose with `pip install cellpose[gui]` in a `venv` environment and Python 3.10. I have `PyQt5.15.7`. I get the following error 

```
2022-10-25 20:39:18,513 [INFO] WRITING LOG OUTPUT TO C:\Users\Frank\.cellpose\run.log
[qdarktheme.main] [INFO] The caches(C:\Users\Frank\.qdarktheme) has been deleted
Traceback (most recent call last):
  File "C:\Users\Frank\.pyenv\pyenv-win\versions\3.10.7\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Frank\.pyenv\pyenv-win\versions\3.10.7\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Frank\.virtualenvs\cellpose\Scripts\cellpose.exe\__main__.py", line 7, in <module>
  File "C:\Users\Frank\.virtualenvs\cellpose\lib\site-packages\cellpose\__main__.py", line 184, in main
    gui.run()
  File "C:\Users\Frank\.virtualenvs\cellpose\lib\site-packages\cellpose\gui\gui.py", line 207, in run
    win = MainW(size, clipboard, image=image)
  File "C:\Users\Frank\.virtualenvs\cellpose\lib\site-packages\cellpose\gui\gui.py", line 277, in __init__
    c = self.palette().brush(QPalette.Base).color()
AttributeError: type object 'QPalette' has no attribute 'Base'. Did you mean: 'base'?
```

**Comment by ElpadoCan** [comment]
I reinstalled from scratch in Python 3.9 and it works. Is Python 3.10 not supported? Thanks!

**Comment by carsen-stringer** [comment]
yes currently only python 3.8 is officially supported, but python 3.9 should work

**Comment by carsen-stringer** [comment]
fyi in anaconda (not venv) in python 3.10.6 I did not receive this error

**Comment by ElpadoCan** [comment]
Ok cool good to know, thank you very much for the response. PS: I was on Windows
