### ISSUE TITLE
Unable to launch cellpose 2.0 GUI on Mac OS 10.14.6 (Mojave)

### ISSUE THREAD

**Issue by jelstrott** [MouseLand/cellpose#630]
I was able to install Cellpose 2.0 following the recommended terminal commands below:

>> conda create --name cellpose python=3.8
>> conda activate cellpose
>> python -m pip install cellpose[gui]

However, when I attempt to launch the gui I get error below. Any thoughts how to troubleshoot this? 

best,
Justin

======
(cellpose) elstrotj-6CJGH7:~ elstrotj$ python -m cellpose
Traceback (most recent call last):
  File "/Users/elstrotj/opt/anaconda3/envs/cellpose/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/elstrotj/opt/anaconda3/envs/cellpose/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/elstrotj/opt/anaconda3/envs/cellpose/lib/python3.8/site-packages/cellpose/__main__.py", line 7, in <module>
    from cellpose import utils, models, io, core
  File "/Users/elstrotj/opt/anaconda3/envs/cellpose/lib/python3.8/site-packages/cellpose/utils.py", line 5, in <module>
    import cv2
  File "/Users/elstrotj/opt/anaconda3/envs/cellpose/lib/python3.8/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/Users/elstrotj/opt/anaconda3/envs/cellpose/lib/python3.8/site-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
  File "/Users/elstrotj/opt/anaconda3/envs/cellpose/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: dlopen(/Users/elstrotj/opt/anaconda3/envs/cellpose/lib/python3.8/site-packages/cv2/cv2.abi3.so, 2): Symbol not found: ___darwin_check_fd_set_overflow
  Referenced from: /Users/elstrotj/opt/anaconda3/envs/cellpose/lib/python3.8/site-packages/cv2/.dylibs/libX11.6.dylib (which was built for Mac OS X 11.0)
  Expected in: /usr/lib/libSystem.B.dylib
 in /Users/elstrotj/opt/anaconda3/envs/cellpose/lib/python3.8/site-packages/cv2/.dylibs/libX11.6.dylib

**Comment by carsen-stringer** [comment]
hmm it looks like python 3.9 or 3.10, might work, please try that? https://opencv.org/opencv-python-for-apples-m1-chip-a-detective-story-with-a-happy-ending/

if it works let us know and we'll add the info
