### ISSUE TITLE
Omnipose 0.3.6 install bug while cellpose works fine

### ISSUE THREAD

**Issue by derekthirstrup** [MouseLand/cellpose#633]
I am trying to compare the 2D & 3D segmentation performance of both omnipose and cellpose.  However, currently I can't get omnipose 0.3.6 to run due to an install bug.  Here is the traceback message.  Does anyone know of a workaround for this issue?

(omnipose) D:\>python -m omnipose
creating new log file
2023-01-06 10:58:30,660 [INFO] WRITING LOG OUTPUT TO C:\Users\derekt\.cellpose\run.log
[qdarktheme.main] [INFO] There is no caches
Traceback (most recent call last):
  File "C:\Users\derekt\Anaconda3\envs\omnipose\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\derekt\Anaconda3\envs\omnipose\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\derekt\Anaconda3\envs\omnipose\lib\site-packages\omnipose\__main__.py", line 3, in <module>
    main(omni_CLI=True)
  File "C:\Users\derekt\Anaconda3\envs\omnipose\lib\site-packages\cellpose\__main__.py", line 184, in main
    gui.run()
  File "C:\Users\derekt\Anaconda3\envs\omnipose\lib\site-packages\cellpose\gui\gui.py", line 207, in run
    win = MainW(size, clipboard, image=image)
  File "C:\Users\derekt\Anaconda3\envs\omnipose\lib\site-packages\cellpose\gui\gui.py", line 253, in __init__
    self.darkmode = darkdetect.theme().lower() == 'dark' # have to initialize
AttributeError: 'NoneType' object has no attribute 'lower'

**Comment by carsen-stringer** [comment]
sorry for using omnipose, please post github issues here: https://github.com/kevinjohncutler/omnipose
