### ISSUE TITLE
[BUG] Trying to Open Cellpose results in this error message. 

### ISSUE THREAD

**Issue by jamnickn** [MouseLand/cellpose#654]
(cellpose) PS C:\Users\jamnickn> python -m cellpose
Traceback (most recent call last):
  File "C:\Users\jamnickn\Anaconda3\envs\cellpose\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\jamnickn\Anaconda3\envs\cellpose\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\jamnickn\Anaconda3\envs\cellpose\lib\site-packages\cellpose\__main__.py", line 5, in <module>
    from cellpose import utils, models, io, core, version_str
  File "C:\Users\jamnickn\Anaconda3\envs\cellpose\lib\site-packages\cellpose\utils.py", line 5, in <module>
    import cv2
  File "C:\Users\jamnickn\Anaconda3\envs\cellpose\lib\site-packages\cv2\__init__.py", line 181, in <module>
    bootstrap()
  File "C:\Users\jamnickn\Anaconda3\envs\cellpose\lib\site-packages\cv2\__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
  File "C:\Users\jamnickn\Anaconda3\envs\cellpose\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: DLL load failed while importing cv2: The specified module could not be found.

**Comment by carsen-stringer** [comment]
can you please provide info on how you installed cellpose?

**Comment by jamnickn** [comment]
**(cellpose) C:\Users\jamnickn>python -m pip install cellpose[gui]**


These are the commands I ran in order. 

(base) C:\Users\jamnickn>conda env remove --name cellpose

Remove all packages in environment C:\Users\jamnickn\Anaconda3\envs\cellpose:

(base) C:\Users\jamnickn>conda create --name cellpose python=3.8

(cellpose) C:\Users\jamnickn>python -m pip install cellpose[gui]

(cellpose) C:\Users\jamnickn>python -m cellpose
Traceback (most recent call last):
  File "C:\Users\jamnickn\Anaconda3\envs\cellpose\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\jamnickn\Anaconda3\envs\cellpose\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\jamnickn\Anaconda3\envs\cellpose\lib\site-packages\cellpose\__main__.py", line 5, in <module>
    from cellpose import utils, models, io, core, version_str
  File "C:\Users\jamnickn\Anaconda3\envs\cellpose\lib\site-packages\cellpose\utils.py", line 5, in <module>
    import cv2
  File "C:\Users\jamnickn\Anaconda3\envs\cellpose\lib\site-packages\cv2\__init__.py", line 181, in <module>
    bootstrap()
  File "C:\Users\jamnickn\Anaconda3\envs\cellpose\lib\site-packages\cv2\__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
  File "C:\Users\jamnickn\Anaconda3\envs\cellpose\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: DLL load failed while importing cv2: The specified module could not be found.

(cellpose) C:\Users\jamnickn>

**Comment by mrariden** [comment]
Does your message from `python -m pip install cellpose[gui]` show an error?

Also, sometimes it is necessary to deactivate the `base` environment before activating or installing the `cellpose` environment. Do this with the `conda deactivate` command when the `(base)` environment is prefixed to your command line path. Then, `conda activate cellpose` and finally `python -m cellpose`.

**Comment by carsen-stringer** [comment]
closing for now due to inactivity

**Comment by anjisingh08** [comment]
Hello, I am also facing a similar issue. I am currently on a Windows 11 Enterprise N and we have tried the suggestions given by mrariden.

Our code statements were as follows:
>conda install openjdk=11
>conda -n imaging python=3.10
>conda activate imaging
>python -m pip install cellpose[gui]==3.1.1.2
(there was no issue when we tried the above code)
>pip install jupyterlab geopandas seaborn

```bash
(imaging) C:\Users\asingh08>python -m cellpose
Traceback (most recent call last):
  File "C:\Users\asingh08\AppData\Local\anaconda3\anaconda\envs\imaging\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\asingh08\AppData\Local\anaconda3\anaconda\envs\imaging\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\asingh08\AppData\Local\anaconda3\anaconda\envs\imaging\lib\site-packages\cellpose\__main__.py", line 9, in <module>
    from cellpose import utils, models, io, version_str, train, denoise
  File "C:\Users\asingh08\AppData\Local\anaconda3\anaconda\envs\imaging\lib\site-packages\cellpose\utils.py", line 8, in <module>
    import cv2
  File "C:\Users\asingh08\AppData\Local\anaconda3\anaconda\envs\imaging\lib\site-packages\cv2\__init__.py", line 181, in <module>
    bootstrap()
  File "C:\Users\asingh08\AppData\Local\anaconda3\anaconda\envs\imaging\lib\site-packages\cv2\__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
  File "C:\Users\asingh08\AppData\Local\anaconda3\anaconda\envs\imaging\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
**ImportError: DLL load failed while importing cv2: The specified module could not be found.**

**(imaging) C:\Users\asingh08>conda deactivate

(base) C:\Users\asingh08>conda deactivate
```

(this is where we encountered the error and tried troubleshooting by deactivating the imaging/base environment and using cellpose instead)**

```bash
C:\Users\asingh08>conda activate cellpose

(cellpose) C:\Users\asingh08>python -m cellpose
Traceback (most recent call last):
  File "C:\Users\asingh08\AppData\Local\anaconda3\anaconda\envs\cellpose\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\asingh08\AppData\Local\anaconda3\anaconda\envs\cellpose\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\asingh08\AppData\Local\anaconda3\anaconda\envs\cellpose\lib\site-packages\cellpose\__main__.py", line 7, in <module>
    from cellpose import utils, models, io, train
  File "C:\Users\asingh08\AppData\Local\anaconda3\anaconda\envs\cellpose\lib\site-packages\cellpose\utils.py", line 8, in <module>
    import cv2
  File "C:\Users\asingh08\AppData\Local\anaconda3\anaconda\envs\cellpose\lib\site-packages\cv2\__init__.py", line 181, in <module>
    bootstrap()
  File "C:\Users\asingh08\AppData\Local\anaconda3\anaconda\envs\cellpose\lib\site-packages\cv2\__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
  File "C:\Users\asingh08\AppData\Local\anaconda3\anaconda\envs\cellpose\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: DLL load failed while importing cv2: The specified module could not be found.

(cellpose) C:\Users\asingh08>
```

It still did not end up working.

**Comment by mrariden** [comment]
Hi @anjisingh08, please try to reinstall in the activated conda environment using: `conda install --force-reinstall cellpose`. This should resolve the missing cv2 dependency.

**Comment by anjisingh08** [comment]
hello, this ended up working. thank you for your help @mrariden !
