### ISSUE TITLE
[BUG] numpy.core._exceptions.MemoryError

### ISSUE THREAD

**Issue by josenimo** [MouseLand/cellpose#661]
**Describe the bug**
Dear Cellpose devs,

I am trying to segment the cytoplasm of my multiplex imaging experiment. It had 10 channels, and using numpy I created a two channel image, with the first channel being DAPI, and the second channel being a maximum projection of all membrane markers `np.max(membrane_channels, axis=0)`.
I stacked with `cellpose_ready = p.stack([nuclear_channel,single_membrane_channel],axis=0)`

These are some statistics from my stack:
Shape: (2, 63146, 59938)
Dtype: uint16
Min: 0
Max: 17273
Which I thought were completely normal, besides the great size.

*Stack Trace*
```(cellpose_GPU) PS C:\Users\Administrator> python -m cellpose --verbose --image_path E:/Jose/Slide2/cellpose_stack/slide2_cellpose_nuclei1_membrane2.ome.tif --use_gpu --pretrained_model cyto --diameter 25 --chan 2 --chan2 1 --no_npy --save_tif --flow_threshold 0 --cellprob_threshold -0.4
2023-02-13 19:43:12,132 [INFO] WRITING LOG OUTPUT TO C:\Users\Administrator\.cellpose\run.log
2023-02-13 19:43:12,132 [INFO]
cellpose version:       2.2
platform:               win32
python version:         3.8.16
torch version:          1.13.1
2023-02-13 19:43:12,350 [INFO] ** TORCH CUDA version installed and working. **
2023-02-13 19:43:12,351 [INFO] >>>> using GPU
2023-02-13 19:43:12,352 [INFO] >>>> running cellpose on 1 images using chan_to_seg GREEN and chan (opt) RED
2023-02-13 19:43:12,352 [INFO] ** TORCH CUDA version installed and working. **
2023-02-13 19:43:12,353 [INFO] >>>> using GPU
2023-02-13 19:43:12,353 [INFO] >> cyto << model set to be used
2023-02-13 19:43:12,863 [INFO] >>>> model diam_mean =  30.000 (ROIs rescaled to this size during training)
2023-02-13 19:43:12,866 [INFO] >>>> using diameter 25.000 for all images
2023-02-13 19:43:12,868 [INFO] 0%|          | 0/1 [00:00<?, ?it/s]
2023-02-13 19:43:16,846 [INFO] ~~~ FINDING MASKS ~~~
2023-02-13 19:47:32,200 [INFO] 0%|          | 0/1 [04:19<?, ?it/s]
Traceback (most recent call last):
  File "C:\Users\Administrator\Jose_BI\Anaconda\envs\cellpose_GPU\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Administrator\Jose_BI\Anaconda\envs\cellpose_GPU\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator\Jose_BI\Anaconda\envs\cellpose_GPU\lib\site-packages\cellpose\__main__.py", line 368, in <module>
    main()
  File "C:\Users\Administrator\Jose_BI\Anaconda\envs\cellpose_GPU\lib\site-packages\cellpose\__main__.py", line 251, in main
    out = model.eval(image, channels=channels, diameter=diameter,
  File "C:\Users\Administrator\Jose_BI\Anaconda\envs\cellpose_GPU\lib\site-packages\cellpose\models.py", line 239, in eval
    masks, flows, styles = self.cp.eval(x,
  File "C:\Users\Administrator\Jose_BI\Anaconda\envs\cellpose_GPU\lib\site-packages\cellpose\models.py", line 552, in eval
    masks, styles, dP, cellprob, p = self._run_cp(x,
  File "C:\Users\Administrator\Jose_BI\Anaconda\envs\cellpose_GPU\lib\site-packages\cellpose\models.py", line 616, in _run_cp
    yf, style = self._run_nets(img, net_avg=net_avg,
  File "C:\Users\Administrator\Jose_BI\Anaconda\envs\cellpose_GPU\lib\site-packages\cellpose\core.py", line 368, in _run_nets
    y0, style = self._run_net(img, augment=augment, tile=tile,
  File "C:\Users\Administrator\Jose_BI\Anaconda\envs\cellpose_GPU\lib\site-packages\cellpose\core.py", line 442, in _run_net
    y, style = self._run_tiled(imgs, augment=augment, bsize=bsize,
  File "C:\Users\Administrator\Jose_BI\Anaconda\envs\cellpose_GPU\lib\site-packages\cellpose\core.py", line 540, in _run_tiled
    y = np.zeros((IMG.shape[0], nout, ly, lx))
numpy.core._exceptions.MemoryError: Unable to allocate 176. GiB for an array with shape (157102, 3, 224, 224) and data type float64
```
**Environment details**
<details>
<summary>Conda list</summary>

```
(cellpose_GPU) PS C:\Users\Administrator> conda list
# packages in environment at C:\Users\Administrator\Jose_BI\Anaconda\envs\cellpose_GPU:
#
# Name                    Version                   Build  Channel
blas                      2.116                       mkl    conda-forge
blas-devel                3.9.0              16_win64_mkl    conda-forge
bzip2                     1.0.8                h8ffe710_4    conda-forge
ca-certificates           2022.12.7            h5b45459_0    conda-forge
cachetools                5.3.0                    pypi_0    pypi
cellpose                  2.2                      pypi_0    pypi
certifi                   2022.12.7                pypi_0    pypi
charset-normalizer        3.0.1                    pypi_0    pypi
colorama                  0.4.6                    pypi_0    pypi
cuda                      11.7.1                        0    nvidia
cuda-cccl                 11.7.91                       0    nvidia
cuda-command-line-tools   11.7.1                        0    nvidia
cuda-compiler             11.7.1                        0    nvidia
cuda-cudart               11.7.99                       0    nvidia
cuda-cudart-dev           11.7.99                       0    nvidia
cuda-cuobjdump            11.7.91                       0    nvidia
cuda-cupti                11.7.101                      0    nvidia
cuda-cuxxfilt             11.7.91                       0    nvidia
cuda-demo-suite           12.0.140                      0    nvidia
cuda-documentation        12.0.140                      0    nvidia
cuda-libraries            11.7.1                        0    nvidia
cuda-libraries-dev        11.7.1                        0    nvidia
cuda-memcheck             11.8.86                       0    nvidia
cuda-nsight-compute       12.0.1                        0    nvidia
cuda-nvcc                 11.7.99                       0    nvidia
cuda-nvdisasm             12.0.140                      0    nvidia
cuda-nvml-dev             11.7.91                       0    nvidia
cuda-nvprof               12.0.146                      0    nvidia
cuda-nvprune              11.7.91                       0    nvidia
cuda-nvrtc                11.7.99                       0    nvidia
cuda-nvrtc-dev            11.7.99                       0    nvidia
cuda-nvtx                 11.7.91                       0    nvidia
cuda-nvvp                 12.0.146                      0    nvidia
cuda-runtime              11.7.1                        0    nvidia
cuda-sanitizer-api        12.0.140                      0    nvidia
cuda-toolkit              11.7.1                        0    nvidia
cuda-tools                11.7.1                        0    nvidia
cuda-visual-tools         11.7.1                        0    nvidia
cudatoolkit               11.7.0              h74894db_11    conda-forge
fastremap                 1.13.3                   pypi_0    pypi
google-api-core           2.11.0                   pypi_0    pypi
google-auth               2.16.0                   pypi_0    pypi
google-cloud-core         2.3.2                    pypi_0    pypi
google-cloud-storage      2.7.0                    pypi_0    pypi
google-crc32c             1.5.0                    pypi_0    pypi
google-resumable-media    2.4.1                    pypi_0    pypi
googleapis-common-protos  1.58.0                   pypi_0    pypi
idna                      3.4                      pypi_0    pypi
imagecodecs               2023.1.23                pypi_0    pypi
importlib-metadata        6.0.0                    pypi_0    pypi
intel-openmp              2023.0.0         h57928b3_25922    conda-forge
libblas                   3.9.0              16_win64_mkl    conda-forge
libcblas                  3.9.0              16_win64_mkl    conda-forge
libcublas                 12.0.2.224                    0    nvidia
libcublas-dev             12.0.2.224                    0    nvidia
libcufft                  11.0.1.95                     0    nvidia
libcufft-dev              11.0.1.95                     0    nvidia
libcurand                 10.3.1.124                    0    nvidia
libcurand-dev             10.3.1.124                    0    nvidia
libcusolver               11.4.3.1                      0    nvidia
libcusolver-dev           11.4.3.1                      0    nvidia
libcusparse               12.0.1.140                    0    nvidia
libcusparse-dev           12.0.1.140                    0    nvidia
libffi                    3.4.2                h8ffe710_5    conda-forge
libhwloc                  2.8.0                h039e092_1    conda-forge
libiconv                  1.17                 h8ffe710_0    conda-forge
liblapack                 3.9.0              16_win64_mkl    conda-forge
liblapacke                3.9.0              16_win64_mkl    conda-forge
libnpp                    12.0.1.104                    0    nvidia
libnpp-dev                12.0.1.104                    0    nvidia
libnvjpeg                 12.0.1.102                    0    nvidia
libnvjpeg-dev             12.0.1.102                    0    nvidia
libsqlite                 3.40.0               hcfcfb64_0    conda-forge
libuv                     1.44.2               h8ffe710_0    conda-forge
libxml2                   2.10.3               hc3477c8_0    conda-forge
libzlib                   1.2.13               hcfcfb64_4    conda-forge
llvmlite                  0.39.1                   pypi_0    pypi
m2w64-gcc-libgfortran     5.3.0                         6    conda-forge
m2w64-gcc-libs            5.3.0                         7    conda-forge
m2w64-gcc-libs-core       5.3.0                         7    conda-forge
m2w64-gmp                 6.1.0                         2    conda-forge
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge
mkl                       2022.1.0           h6a75c08_874    conda-forge
mkl-devel                 2022.1.0           h57928b3_875    conda-forge
mkl-include               2022.1.0           h6a75c08_874    conda-forge
msys2-conda-epoch         20160418                      1    conda-forge
natsort                   8.2.0                    pypi_0    pypi
nsight-compute            2022.4.1.6                    0    nvidia
numba                     0.56.4                   pypi_0    pypi
numpy                     1.23.5                   pypi_0    pypi
opencv-python-headless    4.7.0.68                 pypi_0    pypi
openssl                   3.0.7                hcfcfb64_2    conda-forge
packaging                 23.0                     pypi_0    pypi
pip                       23.0               pyhd8ed1ab_0    conda-forge
protobuf                  4.21.12                  pypi_0    pypi
pthreads-win32            2.9.1                hfa6e2cd_3    conda-forge
pyasn1                    0.4.8                    pypi_0    pypi
pyasn1-modules            0.2.8                    pypi_0    pypi
pygments                  2.14.0                   pypi_0    pypi
pyqt5                     5.15.9                   pypi_0    pypi
pyqt5-qt5                 5.15.2                   pypi_0    pypi
pyqt5-sip                 12.11.1                  pypi_0    pypi
pyqtgraph                 0.13.1                   pypi_0    pypi
python                    3.8.16          h4de0772_1_cpython    conda-forge
pytorch                   1.13.1          py3.8_cuda11.7_cudnn8_0    pytorch
pytorch-cuda              11.7                 h67b0de4_0    pytorch
pytorch-mutex             1.0                        cuda    pytorch
qtpy                      2.3.0                    pypi_0    pypi
requests                  2.28.2                   pypi_0    pypi
rsa                       4.9                      pypi_0    pypi
scipy                     1.10.0                   pypi_0    pypi
setuptools                67.1.0             pyhd8ed1ab_0    conda-forge
six                       1.16.0                   pypi_0    pypi
superqt                   0.4.1                    pypi_0    pypi
tbb                       2021.7.0             h91493d7_1    conda-forge
tifffile                  2023.2.3                 pypi_0    pypi
tk                        8.6.12               h8ffe710_0    conda-forge
tqdm                      4.64.1                   pypi_0    pypi
typing_extensions         4.4.0              pyha770c72_0    conda-forge
ucrt                      10.0.22621.0         h57928b3_0    conda-forge
urllib3                   1.26.14                  pypi_0    pypi
vc                        14.3                hb6edc58_10    conda-forge
vs2015_runtime            14.34.31931         h4c5c07a_10    conda-forge
wheel                     0.38.4             pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h8d14728_0    conda-forge
zipp                      3.12.1                   pypi_0    pypi
```
</details>

<details>
<summary>nvcc --version </summary>

```
(cellpose_GPU) PS C:\Users\Administrator> nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Jun__8_16:59:34_Pacific_Daylight_Time_2022
Cuda compilation tools, release 11.7, V11.7.99
Build cuda_11.7.r11.7/compiler.31442593_0
```
</details>

<details>
<summary> nvidia-smi </summary>

```
josenimo@CMP04801:~$ nvidia-smi
Mon Feb 13 20:00:19 2023
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.60.02    Driver Version: 526.98       CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  On   | 00000000:41:00.0  On |                  N/A |
| 35%   55C    P8    22W / 350W |   2107MiB / 24576MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```
</details>

<details>
<summary> PC details </summary>

```
Device name	CMP04801
Full device name	
Processor	AMD Ryzen Threadripper PRO 3995WX 64-Cores        2.70 GHz
Installed RAM	256 GB (256 GB usable)
Device ID	
Product ID	
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display
```
</details>

Is the image just too big?
Is there any way to batch it without manually tiling the image?
Thank you in advance
Best, 
Jose

Edit:
I have tried to run only the nuclei segmentation model and it also failed with a different error, I have seen this error in other gihub issues but the solution escapes me, I will reread them to try to figure it out.

<details>
<summary> GPU out of memory </summary>

```
(cellpose_GPU) PS C:\Users\Administrator> python -m cellpose --verbose --image_path E:/Jose/Slide2/cellpose_stack/slide2_cellpose_nuclei1_membrane2.ome.tif --use_gpu --pretrained_model nuclei --diameter 25 --chan 2 --no_npy --save_tif --flow_threshold 0.8 --cellprob_threshold -0.4
2023-02-13 19:49:14,651 [INFO] WRITING LOG OUTPUT TO C:\Users\Administrator\.cellpose\run.log
2023-02-13 19:49:14,651 [INFO]
cellpose version:       2.2
platform:               win32
python version:         3.8.16
torch version:          1.13.1
2023-02-13 19:49:14,869 [INFO] ** TORCH CUDA version installed and working. **
2023-02-13 19:49:14,870 [INFO] >>>> using GPU
2023-02-13 19:49:14,871 [INFO] >>>> running cellpose on 1 images using chan_to_seg GREEN and chan (opt) NONE
2023-02-13 19:49:14,871 [INFO] ** TORCH CUDA version installed and working. **
2023-02-13 19:49:14,872 [INFO] >>>> using GPU
2023-02-13 19:49:14,872 [INFO] >> nuclei << model set to be used
2023-02-13 19:49:15,427 [INFO] >>>> model diam_mean =  17.000 (ROIs rescaled to this size during training)
2023-02-13 19:49:15,432 [INFO] >>>> using diameter 25.000 for all images
2023-02-13 19:49:15,434 [INFO] 0%|          | 0/1 [00:00<?, ?it/s]
2023-02-13 19:49:19,512 [INFO] ~~~ FINDING MASKS ~~~
2023-02-13 20:12:24,790 [INFO] 0%|          | 0/1 [23:09<?, ?it/s]
Traceback (most recent call last):
  File "C:\Users\Administrator\Jose_BI\Anaconda\envs\cellpose_GPU\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Administrator\Jose_BI\Anaconda\envs\cellpose_GPU\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator\Jose_BI\Anaconda\envs\cellpose_GPU\lib\site-packages\cellpose\__main__.py", line 368, in <module>
    main()
  File "C:\Users\Administrator\Jose_BI\Anaconda\envs\cellpose_GPU\lib\site-packages\cellpose\__main__.py", line 251, in main
    out = model.eval(image, channels=channels, diameter=diameter,
  File "C:\Users\Administrator\Jose_BI\Anaconda\envs\cellpose_GPU\lib\site-packages\cellpose\models.py", line 239, in eval
    masks, flows, styles = self.cp.eval(x,
  File "C:\Users\Administrator\Jose_BI\Anaconda\envs\cellpose_GPU\lib\site-packages\cellpose\models.py", line 552, in eval
    masks, styles, dP, cellprob, p = self._run_cp(x,
  File "C:\Users\Administrator\Jose_BI\Anaconda\envs\cellpose_GPU\lib\site-packages\cellpose\models.py", line 652, in _run_cp
    outputs = dynamics.compute_masks(dP[:,i], cellprob[i], niter=niter, cellprob_threshold=cellprob_threshold,
  File "C:\Users\Administrator\Jose_BI\Anaconda\envs\cellpose_GPU\lib\site-packages\cellpose\dynamics.py", line 714, in compute_masks
    p, inds = follow_flows(dP * cp_mask / 5., niter=niter, interp=interp,
  File "C:\Users\Administrator\Jose_BI\Anaconda\envs\cellpose_GPU\lib\site-packages\cellpose\dynamics.py", line 547, in follow_flows
    p_interp = steps2D_interp(p[:,inds[:,0], inds[:,1]], dP, niter, use_gpu=use_gpu, device=device)
  File "C:\Users\Administrator\Jose_BI\Anaconda\envs\cellpose_GPU\lib\site-packages\cellpose\dynamics.py", line 371, in steps2D_interp
    im = torch.from_numpy(dP[[1,0]]).float().to(device).unsqueeze(0) #covert flow numpy array to tensor on GPU, add dimension
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 28.20 GiB (GPU 0; 24.00 GiB total capacity; 439.40 MiB already allocated; 22.28 GiB free; 444.00 MiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```
</details>

**Comment by xrzhang-source** [comment]
I have the same error. Have you managed to find a solution yet?

**Comment by carsen-stringer** [comment]
sorry yes you need more RAM on your computer to run this without stitching afterwards. you can either tile the image yourself and stitch (example code that does that here: https://github.com/MouseLand/cellpose/blob/main/cellpose/contrib/distributed_segmentation.py). or run on a computing cluster with a lot of RAM
