### ISSUE TITLE
[INSTALL] Install cellpose[gui] and napari in same environment fails

### ISSUE THREAD

**Issue by manerotoni** [MouseLand/cellpose#677]
**Install problem**
I do encounter incompatibilities when trying to install cellpose[gui] and napari and the GPU-torch capabilities. 
It seems to depend on the order of install. 

I tried different order of install, for instance first napari then cellpose[gui] or vice-versa. Also tried python=3.8 and 3.9

Here some examples:

## Install cellpose[gui] with torch GPU - works
```
conda create -y -n cellpose-env -c conda-forge python=3.9
conda activate cellpose-env
python -m pip install cellpose[gui]
pip uninstall torch
conda install pytorch==1.13.1 pytorch-cuda=11.6 -c pytorch -c nvidia
```
Works and CUDA is active

## Install napari, then cellpose with torch GPU (no GUI)- works
```
conda create -y -n napari-cellpose-env -c conda-forge python=3.9
conda activate napari-cellpose-env
python -m pip install "napari[all]"
python -m pip install cellpose
pip uninstall torch
conda install pytorch==1.13.1 pytorch-cuda=11.6 -c pytorch -c nvidia
```

## Install first napari then cellpose[gui] (no torch-GPU) - Fails
Install first `napari` then `cellpose`  
```
conda create -y -n napari-cellpose-env -c conda-forge python=3.9
conda activate napari-cellpose-env
python -m pip install "napari[all]"
python -m pip install cellpose[gui]
```

start cellpose GUI gives following error 
```
2023-03-20 11:38:55,725 [INFO] WRITING LOG OUTPUT TO C:\Users\apoliti\.cellpose\run.log
2023-03-20 11:38:55,725 [INFO]
cellpose version:       2.2
platform:               win32
python version:         3.9.16
torch version:          2.0.0+cpu
2023-03-20 11:38:56,210 [INFO] TORCH CUDA version not installed/working.
Traceback (most recent call last):
  File "C:\Users\apoliti\Miniconda3\envs\napari-cellpose-env\lib\site-packages\superqt\sliders\_generic_slider.py", line 291, in paintEvent
    painter = QStylePainter(self)
RuntimeError: wrapped C/C++ object of type QRangeSlider has been deleted
```

## Install first cellpose[gui] then napari (no torch-GPU) - Works

Install cellpose

```
conda create -y -n napari-cellpose-gui-env -c conda-forge python=3.9
conda activate napari-cellpose-gui-env
python -m pip install cellpose[gui]
```

Install napari

```
python -m pip install "napari[all]"
```

Both cellpose GUI and Napari works.

## Install first cellpose[gui] then napari then torch torch-GPU  - Fails
```
conda create -y -n napari-cellpose-gui-env -c conda-forge python=3.9
conda activate napari-cellpose-gui-env
python -m pip install cellpose[gui]
python -m pip install "napari[all]"
```

Install GPU-Torch

```
pip uninstall torch
conda install pytorch==1.13.1 pytorch-cuda=11.6 -c pytorch -c nvidia
```

Napari fails with following error

```
Traceback (most recent call last):
  File "C:\Users\apoliti\Miniconda3\envs\cellpose-gui-napari-env\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\apoliti\Miniconda3\envs\cellpose-gui-napari-env\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\apoliti\Miniconda3\envs\cellpose-gui-napari-env\Scripts\napari.exe\__main__.py", line 4, in <module>
  File "C:\Users\apoliti\Miniconda3\envs\cellpose-gui-napari-env\lib\site-packages\napari\__main__.py", line 16, in <module>
    from .utils.translations import trans
  File "C:\Users\apoliti\Miniconda3\envs\cellpose-gui-napari-env\lib\site-packages\napari\utils\__init__.py", line 2, in <module>
    from .colormaps import Colormap
  File "C:\Users\apoliti\Miniconda3\envs\cellpose-gui-napari-env\lib\site-packages\napari\utils\colormaps\__init__.py", line 2, in <module>
    from .colormap import Colormap
  File "C:\Users\apoliti\Miniconda3\envs\cellpose-gui-napari-env\lib\site-packages\napari\utils\colormaps\colormap.py", line 7, in <module>
    from napari.utils.color import ColorArray
  File "C:\Users\apoliti\Miniconda3\envs\cellpose-gui-napari-env\lib\site-packages\napari\utils\color.py", line 7, in <module>
    from napari.utils.colormaps.standardize_color import transform_color
  File "C:\Users\apoliti\Miniconda3\envs\cellpose-gui-napari-env\lib\site-packages\napari\utils\colormaps\standardize_color.py", line 27, in <module>
    from vispy.color import ColorArray, get_color_dict, get_color_names
  File "C:\Users\apoliti\Miniconda3\envs\cellpose-gui-napari-env\lib\site-packages\vispy\color\__init__.py", line 12, in <module>
    from .colormap import (Colormap, BaseColormap,  # noqa
  File "C:\Users\apoliti\Miniconda3\envs\cellpose-gui-napari-env\lib\site-packages\vispy\color\colormap.py", line 14, in <module>
    import vispy.gloo
  File "C:\Users\apoliti\Miniconda3\envs\cellpose-gui-napari-env\lib\site-packages\vispy\gloo\__init__.py", line 47, in <module>
    from . import gl  # noqa
  File "C:\Users\apoliti\Miniconda3\envs\cellpose-gui-napari-env\lib\site-packages\vispy\gloo\gl\__init__.py", line 34, in <module>
    from ._constants import *  # noqa
  File "C:\Users\apoliti\Miniconda3\envs\cellpose-gui-napari-env\lib\site-packages\vispy\gloo\gl\_constants.py", line 330, in <module>
    if repr(ob).startswith('GL_'):
  File "C:\Users\apoliti\Miniconda3\envs\cellpose-gui-napari-env\lib\_sitebuiltins.py", line 61, in __repr__
    self.__setup()
  File "C:\Users\apoliti\Miniconda3\envs\cellpose-gui-napari-env\lib\_sitebuiltins.py", line 51, in __setup
    data = fp.read()
  File "C:\Users\apoliti\Miniconda3\envs\cellpose-gui-napari-env\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 2575: character maps to <undefined>
```

**Comment by mrariden** [comment]
Can you motivate the use case for why you need to install napari and cellpose in the same env? The purpose of environments is to compartmentalize installations, especially when conflicts like these occur. My first reaction is to use separate envs for napari and cellpose for the different steps you have in your workflow. 

[Here's an example](https://unix.stackexchange.com/questions/689163/launch-terminal-and-conda-activate-env-from-bash-script) of how to activate envs from within a unix script.

**Comment by manerotoni** [comment]
Sorry for not replying to the your answer. I think it totally passed my attention. I am doing anyway what you suggest. I have different environments and process the data sequentially so it is not a major issue. I guess this is python and you have to have an environment for each application. 

I use the cellpose-GUI to do a first refinement of the model and some processing. I run cellpose from a python notebook in batch on the 3D images. Typically with the stitching option on. 

I do use napari to check the data and eventually correct the results. These corrected 3D masks can be used to create a XY, XZ, YZ dataset to further train a cellpose model, or be used for training 3D models such as stardist.
