### ISSUE TITLE
[BUG] issues with pyqt5 on Mac m1

### ISSUE THREAD

**Issue by robbrad** [MouseLand/cellpose#732]
**Describe the bug**
Im getting an error with pyqt5

**To Reproduce**
On a MacBook Pro 13-inch, M1, 2020

When I do pip install cellpose[gui]

I get an error about pyqt5 (5.15.2) 

Is it an option to move to pyqt6 ?

```

Package operations: 2 installs, 0 updates, 0 removals

  • Installing pyqt5-sip (12.12.1)
  • Installing pyqt5 (5.15.2): Failed

  CalledProcessError

  Command '['/Users/rbradaws/Projects/repos/cellpose_repo/.venv/bin/python', '-m', 'pip', 'install', '--use-pep517', '--disable-pip-version-check', '--prefix', '/Users/rbradaws/Projects/repos/cellpose_repo/.venv', '--no-deps', '/Users/rbradaws/Library/Caches/pypoetry/artifacts/8f/1f/56/caadc6d31854d3971644dfef7c828d86710532609dd67e50395ac5f713/PyQt5-5.15.0.tar.gz']' returned non-zero exit status 1.

  at /opt/homebrew/Cellar/python@3.10/3.10.12/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py:526 in run
       522│             # We don't call process.wait() as .__exit__ does that for us.
       523│             raise
       524│         retcode = process.poll()
       525│         if check and retcode:
    →  526│             raise CalledProcessError(retcode, process.args,
       527│                                      output=stdout, stderr=stderr)
       528│     return CompletedProcess(process.args, retcode, stdout, stderr)
       529│ 
       530│ 

The following error occurred when trying to handle this error:


  EnvCommandError

  Command ['/Users/rbradaws/Projects/repos/cellpose_repo/.venv/bin/python', '-m', 'pip', 'install', '--use-pep517', '--disable-pip-version-check', '--prefix', '/Users/rbradaws/Projects/repos/cellpose_repo/.venv', '--no-deps', '/Users/rbradaws/Library/Caches/pypoetry/artifacts/8f/1f/56/caadc6d31854d3971644dfef7c828d86710532609dd67e50395ac5f713/PyQt5-5.15.0.tar.gz'] errored with the following return code 1, and output: 
  Processing /Users/rbradaws/Library/Caches/pypoetry/artifacts/8f/1f/56/caadc6d31854d3971644dfef7c828d86710532609dd67e50395ac5f713/PyQt5-5.15.0.tar.gz
    Installing build dependencies: started
    Installing build dependencies: finished with status 'done'
    Getting requirements to build wheel: started
    Getting requirements to build wheel: finished with status 'done'
    Preparing metadata (pyproject.toml): started
    Preparing metadata (pyproject.toml): finished with status 'error'
    error: subprocess-exited-with-error
    
    × Preparing metadata (pyproject.toml) did not run successfully.
    │ exit code: 1
    ╰─> [29 lines of output]
        Traceback (most recent call last):
          File "/Users/rbradaws/Projects/repos/cellpose_repo/.venv/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 156, in prepare_metadata_for_build_wheel
            hook = backend.prepare_metadata_for_build_wheel
        AttributeError: module 'sipbuild.api' has no attribute 'prepare_metadata_for_build_wheel'
        
        During handling of the above exception, another exception occurred:
        
        Traceback (most recent call last):
          File "/Users/rbradaws/Projects/repos/cellpose_repo/.venv/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
            main()
          File "/Users/rbradaws/Projects/repos/cellpose_repo/.venv/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
            json_out['return_val'] = hook(**hook_input['kwargs'])
          File "/Users/rbradaws/Projects/repos/cellpose_repo/.venv/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 160, in prepare_metadata_for_build_wheel
            whl_basename = backend.build_wheel(metadata_directory, config_settings)
          File "/private/var/folders/dg/_kqt_vcj4m37_151_j8l4vd40000gr/T/pip-build-env-lqm6rgxt/overlay/lib/python3.8/site-packages/sipbuild/api.py", line 46, in build_wheel
            project = AbstractProject.bootstrap('wheel',
          File "/private/var/folders/dg/_kqt_vcj4m37_151_j8l4vd40000gr/T/pip-build-env-lqm6rgxt/overlay/lib/python3.8/site-packages/sipbuild/abstract_project.py", line 87, in bootstrap
            project.setup(pyproject, tool, tool_description)
          File "/private/var/folders/dg/_kqt_vcj4m37_151_j8l4vd40000gr/T/pip-build-env-lqm6rgxt/overlay/lib/python3.8/site-packages/sipbuild/project.py", line 586, in setup
            self.apply_user_defaults(tool)
          File "project.py", line 62, in apply_user_defaults
            super().apply_user_defaults(tool)
          File "/private/var/folders/dg/_kqt_vcj4m37_151_j8l4vd40000gr/T/pip-build-env-lqm6rgxt/overlay/lib/python3.8/site-packages/pyqtbuild/project.py", line 70, in apply_user_defaults
            super().apply_user_defaults(tool)
          File "/private/var/folders/dg/_kqt_vcj4m37_151_j8l4vd40000gr/T/pip-build-env-lqm6rgxt/overlay/lib/python3.8/site-packages/sipbuild/project.py", line 237, in apply_user_defaults
            self.builder.apply_user_defaults(tool)
          File "/private/var/folders/dg/_kqt_vcj4m37_151_j8l4vd40000gr/T/pip-build-env-lqm6rgxt/overlay/lib/python3.8/site-packages/pyqtbuild/builder.py", line 69, in apply_user_defaults
            raise PyProjectOptionException('qmake',
        sipbuild.pyproject.PyProjectOptionException
        [end of output]
    
    note: This error originates from a subprocess, and is likely not a problem with pip.
  error: metadata-generation-failed
  
  × Encountered error while generating package metadata.
  ╰─> See above for output.
  
  note: This is an issue with the package mentioned above, not pip.
  hint: See above for details.
  

  at /opt/homebrew/lib/python3.10/site-packages/poetry/utils/env.py:1476 in _run
      1472│                 output = subprocess.check_output(
      1473│                     command, stderr=subprocess.STDOUT, env=env, **kwargs
      1474│                 )
      1475│         except CalledProcessError as e:
    → 1476│             raise EnvCommandError(e, input=input_)
      1477│ 
      1478│         return decode(output)
      1479│ 
      1480│     def execute(self, bin: str, *args: str, **kwargs: Any) -> int:

```

**Comment by mrariden** [comment]
@robbrad can you pip install the latest commits and see if that works for you? There were changes to the Qt dependencies recently. 

In your conda env:
`pip install git+https://github.com/mouseland/cellpose`

**Comment by psobolewskiPhD** [comment]
FYI:
```
mamba create -n test-cellpose python=3.10
mamba activate test-cellpose
pip install cellpose[gui]
cellpose
```
JustWorks(tm) as of 2.2.3 on my arm64 macOS (not using MPS though as far as I can tell though)

**Comment by mrariden** [comment]
I'm going to close this since v2.2.3 should resolve this.
