### ISSUE TITLE
[BUG] Can't save _seg.npy file after frech install on Windows 10

### ISSUE THREAD

**Issue by tquigleygithub** [MouseLand/cellpose#747]
I just installed cellpose for the first time on a windows 10 machine.  The installation went fine, and I can run the GUI and run models on my image.  However, when I try to save my image+masks as a _seg.npy file, nothing happens and I see this error in the console:

Traceback (most recent call last):
  File "C:\Users\Staff\anaconda3\envs\cellpose\lib\site-packages\cellpose\gui\menus.py", line 33, in <lambda>
    parent.saveSet.triggered.connect(lambda: io._save_sets(parent))
  File "C:\Users\Staff\anaconda3\envs\cellpose\lib\site-packages\cellpose\gui\io.py", line 498, in _save_sets
    np.save(base + '_seg.npy',
  File "<__array_function__ internals>", line 200, in save
  File "C:\Users\Staff\anaconda3\envs\cellpose\lib\site-packages\numpy\lib\npyio.py", line 518, in save
    file_ctx = open(file, "wb")
FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/Staff/Desktop/axon_dim_2023/B-m-60x_seg.npy'

If it helps, here is the preceding set of messages in the console:

(cellpose) C:\Users\Staff>python -m cellpose
2023-07-10 16:02:29,037 [INFO] WRITING LOG OUTPUT TO C:\Users\Staff\.cellpose\run.log
2023-07-10 16:02:29,037 [INFO]
cellpose version:       2.2.2
platform:               win32
python version:         3.8.17
torch version:          2.0.1+cpu
2023-07-10 16:02:29,422 [INFO] TORCH CUDA version not installed/working.
GUI_INFO: loading image: C:/Users/Staff/Desktop/axon_dim_2023/B-m-60x.tif
(1920, 2560, 4)
GUI_INFO: auto-adjust enabled, computing saturation levels
2023-07-10 16:03:10,706 [INFO] >> cyto2 << model set to be used
2023-07-10 16:03:10,706 [INFO] >>>> using CPU
2023-07-10 16:03:10,877 [INFO] >>>> model diam_mean =  30.000 (ROIs rescaled to this size during training)
2023-07-10 16:04:11,311 [INFO] 257 cells found with model in 60.636 sec
GUI_INFO: 257 masks found
GUI_INFO: creating cellcolors and drawing masks

**Comment by mrariden** [comment]
Do you get the same result if you edit the segmentation at all before saving? I think there is a test for this case which is currently passing

**Comment by tquigleygithub** [comment]
I get the same result when I edit, or do not edit, when I open the file by drag and drop, or via the menu, and also for both .jpg and .tif files.

**Comment by tquigleygithub** [comment]
I just installed on another windows 10 machine and it works, so this is probably my issue, not yours, and prob not worth chasing down.  If you do, the windows version that works is 10.0.17763.4377 and the one that does not is 10.0.17763.4499.  I'll let you guys close.
