### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by madhavitippani** [MouseLand/cellpose#769]
**Describe the bug**
Trying to save masks using the "Save masks as PNG" tab, but the following error pops up. Using version 2.0, it ran fine and I saved the images fine until yesterday. it suddenly started throwing error.

GUI_INFO: saving 2D masks to png
Traceback (most recent call last):
  File "/jhpce/shared/jhpce/libd/cellpose/2.0/cellpose_env/lib/python3.8/site-packages/cellpose/gui/menus.py", line 38, in <lambda>
    parent.savePNG.triggered.connect(lambda: io._save_png(parent))
  File "/jhpce/shared/jhpce/libd/cellpose/2.0/cellpose_env/lib/python3.8/site-packages/cellpose/gui/io.py", line 460, in _save_png
    imsave(base + '_cp_masks.png', parent.cellpix[0])
  File "/jhpce/shared/jhpce/libd/cellpose/2.0/cellpose_env/lib/python3.8/site-packages/cellpose/io.py", line 119, in imsave
    cv2.imwrite(filename, arr)
cv2.error: OpenCV(4.5.5) :-1: error: (-5:Bad argument) in function 'imwrite'
> Overload resolution failed:
>  - img data type = 6 is not supported
>  - Expected Ptr<cv::UMat> for argument 'img'

**Comment by mrariden** [comment]
@madhavitippani can you provide the steps necessary to reproduce this error, the cellpose version, and the output of `conda list`
