### ISSUE TITLE
I run the file cli.py ,but have something wrong like this:

### ISSUE THREAD

**Issue by FCgogogo** [MouseLand/cellpose#783]
I run the file cli.py ,but have something wrong like this,who can help me?

```
Traceback (most recent call last):
  File "D:\DL\Segment\cellpose-main\cellpose\gui\gui.py", line 838, in calibrate_size
    diams, _ = self.model.sz.eval(self.stack[self.currentZ].copy(),
  File "D:\DL\Segment\cellpose-main\cellpose\models.py", line 522, in eval
    styles = self.cp.eval(x, 
  File "D:\DL\Segment\cellpose-main\cellpose\models.py", line 297, in eval
    masks, styles, dP, cellprob, p = self._run_cp(x, 
  File "D:\DL\Segment\cellpose-main\cellpose\models.py", line 361, in _run_cp
    yf, style = self._run_nets(img, net_avg=net_avg,
  File "D:\DL\Segment\cellpose-main\cellpose\core.py", line 367, in _run_nets
    y, style = self._run_net(img, augment=augment, tile=tile, tile_overlap=tile_overlap,
  File "D:\DL\Segment\cellpose-main\cellpose\core.py", line 446, in _run_net
    y, style = self._run_tiled(imgs, augment=augment, bsize=bsize, 
  File "D:\DL\Segment\cellpose-main\cellpose\core.py", line 547, in _run_tiled
    y0, style = self.network(IMG[irange], return_conv=return_conv)
  File "D:\DL\Segment\cellpose-main\cellpose\core.py", line 319, in network
    y, style = self.net(X)
  File "C:\Anaconda\envs\fengchong\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\DL\Segment\cellpose-main\cellpose\resnet_torch.py", line 260, in forward
    T0 = self.upsample(style, T0, self.mkldnn)
  File "C:\Anaconda\envs\fengchong\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\DL\Segment\cellpose-main\cellpose\resnet_torch.py", line 210, in forward
    x = self.up[-1](xd[-1], xd[-1], style, mkldnn=mkldnn)
  File "C:\Anaconda\envs\fengchong\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\DL\Segment\cellpose-main\cellpose\resnet_torch.py", line 162, in forward
    x = self.proj(x) + self.conv[1](style, self.conv[0](x), y=y, mkldnn=mkldnn)
  File "C:\Anaconda\envs\fengchong\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\DL\Segment\cellpose-main\cellpose\resnet_torch.py", line 129, in forward
    feat = self.full(style)
  File "C:\Anaconda\envs\fengchong\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Anaconda\envs\fengchong\lib\site-packages\torch\nn\modules\linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
TypeError: linear(): argument 'input' (position 1) must be Tensor, not NoneType
```

**Comment by mrariden** [comment]
Hi @FCgogogo , can you provide the exact command you used to run cellpose? 

For reference running cellpose via the CLI, here are the [command line arguments](https://cellpose.readthedocs.io/en/latest/cli.html) and here are [examples of running the CLI](https://cellpose.readthedocs.io/en/latest/command.html#command-line-examples).

**Comment by mrariden** [comment]
I'm closing this for now. For more help using the CLI, please refer to image.sc forum [here](https://forum.image.sc/tag/cellpose).
