### ISSUE TITLE
install cellpose on ubiuntu 18.04

### ISSUE THREAD

**Issue by olatarkowska** [MouseLand/cellpose#79]
I am facing issues with installaing cellpose on default https://mxnet.apache.org/get_started/validate_mxnet#docker-with-cpu container

```
Step 1/5 : FROM mxnet/python:latest
latest: Pulling from mxnet/python
0a01a72a686c: Pull complete 
cc899a5544da: Pull complete 
19197c550755: Pull complete 
716d454e56b6: Pull complete 
f001a21ec4c9: Pull complete 
735c6460a04c: Pull complete 
5ef019fbc840: Pull complete 
82cb81df15a8: Pull complete 
Digest: sha256:443180535a8cd3d01ce9de89983535c1b86dd1bbfdef1e5506477a3b0dcc0dec
Status: Downloaded newer image for mxnet/python:latest
 ---> e1a3a7d79c7e
Step 2/5 : RUN useradd -u 1000 -ms /bin/bash user
 ---> Running in 4529ebd0483b
Removing intermediate container 4529ebd0483b
 ---> c4f68551ffa6
Step 3/5 : RUN pip install cellpose
 ---> Running in 4dc86c5b1a28
Collecting cellpose
  Downloading cellpose-0.0.2.8-py3-none-any.whl (92 kB)
Collecting Pillow<=7.0.0
  Downloading Pillow-7.0.0-cp35-cp35m-manylinux1_x86_64.whl (2.1 MB)
Collecting scipy
  Downloading scipy-1.4.1-cp35-cp35m-manylinux1_x86_64.whl (26.0 MB)
Requirement already satisfied: numpy in /usr/local/lib/python3.5/dist-packages (from cellpose) (1.18.1)
Collecting scikit-image
  Downloading scikit_image-0.15.0-cp35-cp35m-manylinux1_x86_64.whl (26.2 MB)
Collecting numba
  Downloading numba-0.47.0-cp35-cp35m-manylinux1_x86_64.whl (3.7 MB)
Collecting tqdm
  Downloading tqdm-4.46.0-py2.py3-none-any.whl (63 kB)
Collecting opencv-python
  Downloading opencv_python-4.2.0.34-cp35-cp35m-manylinux1_x86_64.whl (28.2 MB)
Collecting natsort
  Downloading natsort-7.0.1-py3-none-any.whl (33 kB)
Collecting mxnet-mkl
  Downloading mxnet_mkl-1.6.0-py2.py3-none-manylinux1_x86_64.whl (76.7 MB)
Collecting matplotlib
  Downloading matplotlib-3.0.3-cp35-cp35m-manylinux1_x86_64.whl (13.0 MB)
Collecting imageio>=2.0.1
  Downloading imageio-2.8.0-py3-none-any.whl (3.3 MB)
Collecting PyWavelets>=0.4.0
  Downloading PyWavelets-1.1.1-cp35-cp35m-manylinux1_x86_64.whl (4.4 MB)
Collecting networkx>=2.0
  Downloading networkx-2.4-py3-none-any.whl (1.6 MB)
Requirement already satisfied: setuptools in /usr/local/lib/python3.5/dist-packages (from numba->cellpose) (45.2.0)
Collecting llvmlite>=0.31.0dev0
  Downloading llvmlite-0.32.1.tar.gz (104 kB)
Requirement already satisfied: requests<3,>=2.20.0 in /usr/local/lib/python3.5/dist-packages (from mxnet-mkl->cellpose) (2.22.0)
Requirement already satisfied: graphviz<0.9.0,>=0.8.1 in /usr/local/lib/python3.5/dist-packages (from mxnet-mkl->cellpose) (0.8.4)
Collecting kiwisolver>=1.0.1
  Downloading kiwisolver-1.1.0-cp35-cp35m-manylinux1_x86_64.whl (90 kB)
Collecting python-dateutil>=2.1
  Downloading python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
Collecting cycler>=0.10
  Downloading cycler-0.10.0-py2.py3-none-any.whl (6.5 kB)
Collecting pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1
  Downloading pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
Collecting decorator>=4.3.0
  Downloading decorator-4.4.2-py2.py3-none-any.whl (9.2 kB)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.5/dist-packages (from requests<3,>=2.20.0->mxnet-mkl->cellpose) (2019.11.28)
Requirement already satisfied: idna<2.9,>=2.5 in /usr/local/lib/python3.5/dist-packages (from requests<3,>=2.20.0->mxnet-mkl->cellpose) (2.8)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.5/dist-packages (from requests<3,>=2.20.0->mxnet-mkl->cellpose) (1.25.8)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python3.5/dist-packages (from requests<3,>=2.20.0->mxnet-mkl->cellpose) (3.0.4)
Collecting six>=1.5
  Downloading six-1.15.0-py2.py3-none-any.whl (10 kB)
Building wheels for collected packages: llvmlite
  Building wheel for llvmlite (setup.py): started
  Building wheel for llvmlite (setup.py): finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-42_hpshv/llvmlite/setup.py'"'"'; __file__='"'"'/tmp/pip-install-42_hpshv/llvmlite/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-r7xptxbo
       cwd: /tmp/pip-install-42_hpshv/llvmlite/
  Complete output (26 lines):
  running bdist_wheel
  /usr/bin/python3 /tmp/pip-install-42_hpshv/llvmlite/ffi/build.py
  LLVM version... Traceback (most recent call last):
    File "/tmp/pip-install-42_hpshv/llvmlite/ffi/build.py", line 106, in main_posix
      out = subprocess.check_output([llvm_config, '--version'])
    File "/usr/lib/python3.5/subprocess.py", line 626, in check_output
      **kwargs).stdout
    File "/usr/lib/python3.5/subprocess.py", line 693, in run
      with Popen(*popenargs, **kwargs) as process:
    File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
      restore_signals, start_new_session)
    File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
      raise child_exception_type(errno_num, err_msg)
  FileNotFoundError: [Errno 2] No such file or directory: 'llvm-config'
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/tmp/pip-install-42_hpshv/llvmlite/ffi/build.py", line 192, in <module>
      main()
    File "/tmp/pip-install-42_hpshv/llvmlite/ffi/build.py", line 182, in main
      main_posix('linux', '.so')
    File "/tmp/pip-install-42_hpshv/llvmlite/ffi/build.py", line 109, in main_posix
      "to the path for llvm-config" % (llvm_config,))
  RuntimeError: llvm-config failed executing, please point LLVM_CONFIG to the path for llvm-config
  error: command '/usr/bin/python3' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for llvmlite
  Running setup.py clean for llvmlite
Failed to build llvmlite
Installing collected packages: Pillow, scipy, imageio, PyWavelets, kiwisolver, six, python-dateutil, cycler, pyparsing, matplotlib, decorator, networkx, scikit-image, llvmlite, numba, tqdm, opencv-python, natsort, mxnet-mkl, cellpose
    Running setup.py install for llvmlite: started
    Running setup.py install for llvmlite: finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-42_hpshv/llvmlite/setup.py'"'"'; __file__='"'"'/tmp/pip-install-42_hpshv/llvmlite/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-wybepq31/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.5/llvmlite
         cwd: /tmp/pip-install-42_hpshv/llvmlite/
    Complete output (29 lines):
    running install
    running build
    got version from file /tmp/pip-install-42_hpshv/llvmlite/llvmlite/_version.py {'full': 'aa11b129c0b55973067422397821ae6d44fa5e70', 'version': '0.32.1'}
    running build_ext
    /usr/bin/python3 /tmp/pip-install-42_hpshv/llvmlite/ffi/build.py
    LLVM version... Traceback (most recent call last):
      File "/tmp/pip-install-42_hpshv/llvmlite/ffi/build.py", line 106, in main_posix
        out = subprocess.check_output([llvm_config, '--version'])
      File "/usr/lib/python3.5/subprocess.py", line 626, in check_output
        **kwargs).stdout
      File "/usr/lib/python3.5/subprocess.py", line 693, in run
        with Popen(*popenargs, **kwargs) as process:
      File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
        restore_signals, start_new_session)
      File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
        raise child_exception_type(errno_num, err_msg)
    FileNotFoundError: [Errno 2] No such file or directory: 'llvm-config'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/tmp/pip-install-42_hpshv/llvmlite/ffi/build.py", line 192, in <module>
        main()
      File "/tmp/pip-install-42_hpshv/llvmlite/ffi/build.py", line 182, in main
        main_posix('linux', '.so')
      File "/tmp/pip-install-42_hpshv/llvmlite/ffi/build.py", line 109, in main_posix
        "to the path for llvm-config" % (llvm_config,))
    RuntimeError: llvm-config failed executing, please point LLVM_CONFIG to the path for llvm-config
    error: command '/usr/bin/python3' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-42_hpshv/llvmlite/setup.py'"'"'; __file__='"'"'/tmp/pip-install-42_hpshv/llvmlite/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-wybepq31/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.5/llvmlite Check the logs for full command output.
WARNING: You are using pip version 20.0.2; however, version 20.1.1 is available.
You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.
The command '/bin/sh -c pip install cellpose' returned a non-zero code: 1
```

Do you have requrement.txt with appropriate wheels that installer won't compine dependences? It would help me to reduce size of the container

**Comment by Czaki** [comment]
last version of llvmlite provide wheels only for python 3.6+. Use newer python or install `pip install llvmlite==0.31.0`

**Comment by carsen-stringer** [comment]
I recommend using conda instead of pip if running into install issues using our environment.yml file. if that doesn't work please let me know
