### ISSUE TITLE
failed to install cellpose[GUI]

### ISSUE THREAD

**Issue by limin321** [MouseLand/cellpose#819]
**Install problem**
I have no issue running cellpose in script, however, it failed to install the "cellpose[GUI]".

**Environment info**
Here is what I got after running `conda list`.
(cellpose) [lchen@localhost cellpose]$ conda list
# packages in environment at /home/lchen/miniconda3/envs/cellpose:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main
_openmp_mutex             5.1                       1_gnu
anyio                     4.0.0                    pypi_0    pypi
argon2-cffi               23.1.0                   pypi_0    pypi
argon2-cffi-bindings      21.2.0                   pypi_0    pypi
arrow                     1.3.0                    pypi_0    pypi
asttokens                 2.4.0                    pypi_0    pypi
async-lru                 2.0.4                    pypi_0    pypi
attrs                     23.1.0                   pypi_0    pypi
babel                     2.13.1                   pypi_0    pypi
backcall                  0.2.0                    pypi_0    pypi
beautifulsoup4            4.12.2                   pypi_0    pypi
bleach                    6.1.0                    pypi_0    pypi
ca-certificates           2023.08.22           h06a4308_0
caer                      2.0.8                    pypi_0    pypi
cellpose                  2.2.3                    pypi_0    pypi
certifi                   2023.7.22                pypi_0    pypi
cffi                      1.16.0                   pypi_0    pypi
charset-normalizer        3.3.1                    pypi_0    pypi
comm                      0.1.4                    pypi_0    pypi
contourpy                 1.1.1                    pypi_0    pypi
cycler                    0.12.1                   pypi_0    pypi
debugpy                   1.8.0                    pypi_0    pypi
decorator                 5.1.1                    pypi_0    pypi
defusedxml                0.7.1                    pypi_0    pypi
exceptiongroup            1.1.3                    pypi_0    pypi
executing                 2.0.0                    pypi_0    pypi
fastjsonschema            2.18.1                   pypi_0    pypi
fastremap                 1.14.0                   pypi_0    pypi
filelock                  3.12.4                   pypi_0    pypi
fonttools                 4.43.1                   pypi_0    pypi
fqdn                      1.5.1                    pypi_0    pypi
fsspec                    2023.10.0                pypi_0    pypi
idna                      3.4                      pypi_0    pypi
imagecodecs               2023.3.16                pypi_0    pypi
importlib-metadata        6.8.0                    pypi_0    pypi
importlib-resources       6.1.0                    pypi_0    pypi
ipykernel                 6.26.0                   pypi_0    pypi
ipython                   8.12.3                   pypi_0    pypi
isoduration               20.11.0                  pypi_0    pypi
jedi                      0.19.1                   pypi_0    pypi
jinja2                    3.1.2                    pypi_0    pypi
json5                     0.9.14                   pypi_0    pypi
jsonpointer               2.4                      pypi_0    pypi
jsonschema                4.19.1                   pypi_0    pypi
jsonschema-specifications 2023.7.1                 pypi_0    pypi
jupyter-client            8.5.0                    pypi_0    pypi
jupyter-core              5.4.0                    pypi_0    pypi
jupyter-events            0.8.0                    pypi_0    pypi
jupyter-lsp               2.2.0                    pypi_0    pypi
jupyter-server            2.9.1                    pypi_0    pypi
jupyter-server-terminals  0.4.4                    pypi_0    pypi
jupyterlab                4.0.7                    pypi_0    pypi
jupyterlab-pygments       0.2.2                    pypi_0    pypi
jupyterlab-server         2.25.0                   pypi_0    pypi
kiwisolver                1.4.5                    pypi_0    pypi
ld_impl_linux-64          2.38                 h1181459_1
libffi                    3.4.4                h6a678d5_0
libgcc-ng                 11.2.0               h1234567_1
libgomp                   11.2.0               h1234567_1
libstdcxx-ng              11.2.0               h1234567_1
llvmlite                  0.41.1                   pypi_0    pypi
markupsafe                2.1.3                    pypi_0    pypi
matplotlib                3.7.3                    pypi_0    pypi
matplotlib-inline         0.1.6                    pypi_0    pypi
mistune                   3.0.2                    pypi_0    pypi
mpmath                    1.3.0                    pypi_0    pypi
mypy                      1.6.1                    pypi_0    pypi
mypy-extensions           1.0.0                    pypi_0    pypi
natsort                   8.4.0                    pypi_0    pypi
nbclient                  0.8.0                    pypi_0    pypi
nbconvert                 7.9.2                    pypi_0    pypi
nbformat                  5.9.2                    pypi_0    pypi
ncurses                   6.4                  h6a678d5_0
nest-asyncio              1.5.8                    pypi_0    pypi
networkx                  3.1                      pypi_0    pypi
notebook                  7.0.6                    pypi_0    pypi
notebook-shim             0.2.3                    pypi_0    pypi
numba                     0.58.1                   pypi_0    pypi
numpy                     1.24.4                   pypi_0    pypi
nvidia-cublas-cu12        12.1.3.1                 pypi_0    pypi
nvidia-cuda-cupti-cu12    12.1.105                 pypi_0    pypi
nvidia-cuda-nvrtc-cu12    12.1.105                 pypi_0    pypi
nvidia-cuda-runtime-cu12  12.1.105                 pypi_0    pypi
nvidia-cudnn-cu12         8.9.2.26                 pypi_0    pypi
nvidia-cufft-cu12         11.0.2.54                pypi_0    pypi
nvidia-curand-cu12        10.3.2.106               pypi_0    pypi
nvidia-cusolver-cu12      11.4.5.107               pypi_0    pypi
nvidia-cusparse-cu12      12.1.0.106               pypi_0    pypi
nvidia-nccl-cu12          2.18.1                   pypi_0    pypi
nvidia-nvjitlink-cu12     12.3.52                  pypi_0    pypi
nvidia-nvtx-cu12          12.1.105                 pypi_0    pypi
opencv-contrib-python     4.8.1.78                 pypi_0    pypi
opencv-python-headless    4.8.1.78                 pypi_0    pypi
openssl                   3.0.11               h7f8727e_2
overrides                 7.4.0                    pypi_0    pypi
packaging                 23.2                     pypi_0    pypi
pandocfilters             1.5.0                    pypi_0    pypi
parso                     0.8.3                    pypi_0    pypi
pexpect                   4.8.0                    pypi_0    pypi
pickleshare               0.7.5                    pypi_0    pypi
pillow                    10.1.0                   pypi_0    pypi
pip                       23.3.1                   pypi_0    pypi
pkgutil-resolve-name      1.3.10                   pypi_0    pypi
platformdirs              3.11.0                   pypi_0    pypi
prometheus-client         0.17.1                   pypi_0    pypi
prompt-toolkit            3.0.39                   pypi_0    pypi
psutil                    5.9.6                    pypi_0    pypi
ptyprocess                0.7.0                    pypi_0    pypi
pure-eval                 0.2.2                    pypi_0    pypi
pycparser                 2.21                     pypi_0    pypi
pygments                  2.16.1                   pypi_0    pypi
pyparsing                 3.1.1                    pypi_0    pypi
python                    3.8.18               h955ad1f_0
python-dateutil           2.8.2                    pypi_0    pypi
python-json-logger        2.0.7                    pypi_0    pypi
pytz                      2023.3.post1             pypi_0    pypi
pyyaml                    6.0.1                    pypi_0    pypi
pyzmq                     25.1.1                   pypi_0    pypi
qtpy                      2.4.1                    pypi_0    pypi
readline                  8.2                  h5eee18b_0
referencing               0.30.2                   pypi_0    pypi
requests                  2.31.0                   pypi_0    pypi
rfc3339-validator         0.1.4                    pypi_0    pypi
rfc3986-validator         0.1.1                    pypi_0    pypi
roifile                   2023.5.12                pypi_0    pypi
rpds-py                   0.10.6                   pypi_0    pypi
scipy                     1.10.1                   pypi_0    pypi
send2trash                1.8.2                    pypi_0    pypi
setuptools                68.2.2                   pypi_0    pypi
six                       1.16.0                   pypi_0    pypi
sniffio                   1.3.0                    pypi_0    pypi
soupsieve                 2.5                      pypi_0    pypi
sqlite                    3.41.2               h5eee18b_0
stack-data                0.6.3                    pypi_0    pypi
sympy                     1.12                     pypi_0    pypi
terminado                 0.17.1                   pypi_0    pypi
tifffile                  2023.7.10                pypi_0    pypi
tinycss2                  1.2.1                    pypi_0    pypi
tk                        8.6.12               h1ccaba5_0
tomli                     2.0.1                    pypi_0    pypi
torch                     2.1.0                    pypi_0    pypi
tornado                   6.3.3                    pypi_0    pypi
tqdm                      4.66.1                   pypi_0    pypi
traitlets                 5.12.0                   pypi_0    pypi
triton                    2.1.0                    pypi_0    pypi
types-python-dateutil     2.8.19.14                pypi_0    pypi
typing-extensions         4.8.0                    pypi_0    pypi
uri-template              1.3.0                    pypi_0    pypi
urllib3                   2.0.7                    pypi_0    pypi
wcwidth                   0.2.8                    pypi_0    pypi
webcolors                 1.13                     pypi_0    pypi
webencodings              0.5.1                    pypi_0    pypi
websocket-client          1.6.4                    pypi_0    pypi
wheel                     0.41.2           py38h06a4308_0
xz                        5.4.2                h5eee18b_0
zipp                      3.17.0                   pypi_0    pypi
zlib                      1.2.13               h5eee18b_0

**Run log**
(cellpose) [lchen@localhost cellpose]$ pip install "cellpose[gui]"
Requirement already satisfied: cellpose[gui] in /home/lchen/miniconda3/envs/cellpose/lib/python3.8/site-packages (2.2.3)
Requirement already satisfied: numpy>=1.20.0 in /home/lchen/miniconda3/envs/cellpose/lib/python3.8/site-packages (from cellpose[gui]) (1.24.4)
Requirement already satisfied: scipy in /home/lchen/miniconda3/envs/cellpose/lib/python3.8/site-packages (from cellpose[gui]) (1.10.1)
Requirement already satisfied: natsort in /home/lchen/miniconda3/envs/cellpose/lib/python3.8/site-packages (from cellpose[gui]) (8.4.0)
Requirement already satisfied: tifffile in /home/lchen/miniconda3/envs/cellpose/lib/python3.8/site-packages (from cellpose[gui]) (2023.7.10)
Requirement already satisfied: tqdm in /home/lchen/miniconda3/envs/cellpose/lib/python3.8/site-packages (from cellpose[gui]) (4.66.1)
Requirement already satisfied: numba>=0.53.0 in /home/lchen/miniconda3/envs/cellpose/lib/python3.8/site-packages (from cellpose[gui]) (0.58.1)
Requirement already satisfied: llvmlite in /home/lchen/miniconda3/envs/cellpose/lib/python3.8/site-packages (from cellpose[gui]) (0.41.1)
Requirement already satisfied: torch>=1.6 in /home/lchen/miniconda3/envs/cellpose/lib/python3.8/site-packages (from cellpose[gui]) (2.1.0)
Requirement already satisfied: opencv-python-headless in /home/lchen/miniconda3/envs/cellpose/lib/python3.8/site-packages (from cellpose[gui]) (4.8.1.78)
Requirement already satisfied: fastremap in /home/lchen/miniconda3/envs/cellpose/lib/python3.8/site-packages (from cellpose[gui]) (1.14.0)
Requirement already satisfied: imagecodecs in /home/lchen/miniconda3/envs/cellpose/lib/python3.8/site-packages (from cellpose[gui]) (2023.3.16)
Requirement already satisfied: roifile in /home/lchen/miniconda3/envs/cellpose/lib/python3.8/site-packages (from cellpose[gui]) (2023.5.12)
Collecting pyqtgraph>=0.11.0rc0 (from cellpose[gui])
  Using cached pyqtgraph-0.13.3-py3-none-any.whl (960 kB)
Collecting pyqt6 (from cellpose[gui])
  Using cached PyQt6-6.6.0.tar.gz (1.0 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [22 lines of output]
      Traceback (most recent call last):
        File "/home/lchen/miniconda3/envs/cellpose/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/lchen/miniconda3/envs/cellpose/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/lchen/miniconda3/envs/cellpose/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 152, in prepare_metadata_for_build_wheel
          whl_basename = backend.build_wheel(metadata_directory, config_settings)
        File "/tmp/pip-build-env-ho7d6y2n/overlay/lib/python3.8/site-packages/sipbuild/api.py", line 46, in build_wheel
          project = AbstractProject.bootstrap('wheel',
        File "/tmp/pip-build-env-ho7d6y2n/overlay/lib/python3.8/site-packages/sipbuild/abstract_project.py", line 87, in bootstrap
          project.setup(pyproject, tool, tool_description)
        File "/tmp/pip-build-env-ho7d6y2n/overlay/lib/python3.8/site-packages/sipbuild/project.py", line 586, in setup
          self.apply_user_defaults(tool)
        File "project.py", line 66, in apply_user_defaults
          super().apply_user_defaults(tool)
        File "/tmp/pip-build-env-ho7d6y2n/overlay/lib/python3.8/site-packages/pyqtbuild/project.py", line 70, in apply_user_defaults
          super().apply_user_defaults(tool)
        File "/tmp/pip-build-env-ho7d6y2n/overlay/lib/python3.8/site-packages/sipbuild/project.py", line 237, in apply_user_defaults
          self.builder.apply_user_defaults(tool)
        File "/tmp/pip-build-env-ho7d6y2n/overlay/lib/python3.8/site-packages/pyqtbuild/builder.py", line 69, in apply_user_defaults
          raise PyProjectOptionException('qmake',
      sipbuild.pyproject.PyProjectOptionException
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by mrariden** [comment]
Does `conda install pyqt5` in that same environment help?

**Comment by carsen-stringer** [comment]
closing due to inactivity
