### ISSUE TITLE
[BUG] GUI Fails to Open 

### ISSUE THREAD

**Issue by naboughali** [MouseLand/cellpose#830]
**Describe the bug**
GUI fails to open after "python -m cellpose" command. 

**Run log**
(base) nairaaboughali@MAC209438 ~ % conda activate cellpose
(cellpose) nairaaboughali@MAC209438 ~ % python -m cellpose
Traceback (most recent call last):
  File "/Users/nairaaboughali/opt/anaconda3/envs/cellpose/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/Users/nairaaboughali/opt/anaconda3/envs/cellpose/lib/python3.8/runpy.py", line 144, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/Users/nairaaboughali/opt/anaconda3/envs/cellpose/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/Users/nairaaboughali/opt/anaconda3/envs/cellpose/lib/python3.8/site-packages/cellpose/__init__.py", line 1, in <module>
    from cellpose.version import version, version_str
  File "/Users/nairaaboughali/opt/anaconda3/envs/cellpose/lib/python3.8/site-packages/cellpose/version.py", line 8, in <module>
    import torch 
  File "/Users/nairaaboughali/opt/anaconda3/envs/cellpose/lib/python3.8/site-packages/torch/__init__.py", line 229, in <module>
    from torch._C import *  # noqa: F403
ImportError: dlopen(/Users/nairaaboughali/opt/anaconda3/envs/cellpose/lib/python3.8/site-packages/torch/_C.cpython-38-darwin.so, 0x0002): Library not loaded: @loader_path/libtorch_cpu.dylib
  Referenced from: <31789A94-823C-3787-992E-9F28A088AE0E> /Users/nairaaboughali/opt/anaconda3/envs/cellpose/lib/python3.8/site-packages/torch/lib/libtorch_python.dylib
  Reason: tried: '/Users/nairaaboughali/opt/anaconda3/envs/cellpose/lib/python3.8/site-packages/torch/lib/libtorch_cpu.dylib' (no such file), '/usr/local/lib/libtorch_cpu.dylib' (no such file), '/usr/lib/libtorch_cpu.dylib' (no such file, not in dyld cache)

**Comment by carsen-stringer** [comment]
closing due to inactivity
