### ISSUE TITLE
[BUG] ssl error behind institue proxy

### ISSUE THREAD

**Issue by anstamh** [MouseLand/cellpose#844]
Hey everyone,

I'm trying to run cellpose behind a proxy of an institute and have trouble with an ssl error. The PC uses windows 10 and the conda version is 23.11.0.
I'm aware that this is not necessarily an issue with cellpose itself, but would be greatful for any feedback you could offer anyway.
To install cellpose itself I deposited the proxy information in a pip.ini file. Setting the proxy in the cellpose conda environment didn't help with the following error.

(base) PS C:\windows\system32> conda activate cellpose
(cellpose) PS C:\windows\system32> cellpose
2023-12-15 15:22:40,602 [INFO] WRITING LOG OUTPUT TO C:\Users\xxx\.cellpose\run.log
2023-12-15 15:22:40,602 [INFO]
cellpose version:       2.2.3
platform:               win32
python version:         3.8.18
torch version:          2.1.1+cpu
downloading logo
Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\envs\cellpose\lib\urllib\request.py", line 1354, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "C:\ProgramData\anaconda3\envs\cellpose\lib\http\client.py", line 1256, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\ProgramData\anaconda3\envs\cellpose\lib\http\client.py", line 1302, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\ProgramData\anaconda3\envs\cellpose\lib\http\client.py", line 1251, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\ProgramData\anaconda3\envs\cellpose\lib\http\client.py", line 1011, in _send_output
    self.send(msg)
  File "C:\ProgramData\anaconda3\envs\cellpose\lib\http\client.py", line 951, in send
    self.connect()
  File "C:\ProgramData\anaconda3\envs\cellpose\lib\http\client.py", line 1418, in connect
    super().connect()
  File "C:\ProgramData\anaconda3\envs\cellpose\lib\http\client.py", line 922, in connect
    self.sock = self._create_connection(
  File "C:\ProgramData\anaconda3\envs\cellpose\lib\socket.py", line 808, in create_connection
    raise err
  File "C:\ProgramData\anaconda3\envs\cellpose\lib\socket.py", line 796, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] Ein Verbindungsversuch ist fehlgeschlagen, da die Gegenstelle nach einer bestimmten Zeitspanne nicht richtig reagiert hat, oder die hergestellte Verbindung war fehlerhaft, da der verbundene Host nicht reagiert hat

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\envs\cellpose\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\ProgramData\anaconda3\envs\cellpose\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\anaconda3\envs\cellpose\Scripts\cellpose.exe\__main__.py", line 7, in <module>
  File "C:\ProgramData\anaconda3\envs\cellpose\lib\site-packages\cellpose\__main__.py", line 53, in main
    gui.run()
  File "C:\ProgramData\anaconda3\envs\cellpose\lib\site-packages\cellpose\gui\gui.py", line 139, in run
    download_url_to_file('https://www.cellpose.org/static/images/cellpose_transparent.png', icon_path, progress=True)
  File "C:\ProgramData\anaconda3\envs\cellpose\lib\site-packages\cellpose\utils.py", line 69, in download_url_to_file
    u = urlopen(url)
  File "C:\ProgramData\anaconda3\envs\cellpose\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:\ProgramData\anaconda3\envs\cellpose\lib\urllib\request.py", line 525, in open
    response = self._open(req, data)
  File "C:\ProgramData\anaconda3\envs\cellpose\lib\urllib\request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "C:\ProgramData\anaconda3\envs\cellpose\lib\urllib\request.py", line 502, in _call_chain
    result = func(*args)
  File "C:\ProgramData\anaconda3\envs\cellpose\lib\urllib\request.py", line 1397, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "C:\ProgramData\anaconda3\envs\cellpose\lib\urllib\request.py", line 1357, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [WinError 10060] Ein Verbindungsversuch ist fehlgeschlagen, da die Gegenstelle nach einer bestimmten Zeitspanne nicht richtig reagiert hat, oder die hergestellte Verbindung war fehlerhaft, da der verbundene Host nicht reagiert hat>

If further information is needed please let me know.
Thanks in advance for taking a look.

**Comment by mrariden** [comment]
The error you're getting looks like a timeout when connecting to the cellpose.org domain. That is where a few assets for the gui and models are located. Maybe whitelist this URL in your proxy?

This is outside the scope of the cellpose project, so I'm going to close the issue. Reopen if necessary
