### ISSUE TITLE
Cellpose 3.0.1 can not save mask as npy file anymore

### ISSUE THREAD

**Issue by marnixwkoops** [MouseLand/cellpose#860]
When you save masks and image as seg_npy (ctrl s)

Traceback (most recent call last):
  File "C:\AppData\Local\anaconda3\envs\cellpose\lib\site-packages\cellpose\gui\menus.py", line 41, in <lambda>
    parent.saveSet.triggered.connect(lambda: io._save_sets(parent))
  File "C:\\AppData\Local\anaconda3\envs\cellpose\lib\site-packages\cellpose\gui\io.py", line 595, in _save_sets
    'ratio': parent.ratio,
AttributeError: 'MainW' object has no attribute 'ratio'

**Comment by marnixwkoops** [comment]
What do you mean with wait a bit?

**Comment by mrariden** [comment]
@marnixwkoops When a new cellpose version is released, `pip install cellpose --upgrade` will install the released version. If you want the fix immediately use the pip with git command above. Expect new updates available to pip on the timeline of a few weeks.
