### ISSUE TITLE
[BUG] Training on iMac M1 - KeyError: 'normalize'

### ISSUE THREAD

**Issue by superwormz** [MouseLand/cellpose#861]
I am having problems running Cellpose on Apple M1 chip. Everything works fine on my MacBook Pro 2017 (Intel) but on MacBook with M1 chip, I had to try various ways of installing and had lots off issues which I think I have overcome. However, when I try to train a new model it runs the epochs, but then I get the following:

```
/Users/Hannah/Downloads/D1 ORG Cellpose/processed/models/test copied to models folder /Users/Hannah/.cellpose/models
2024-02-15 17:26:17,366 [INFO] >>>> diameter set to diam_labels ( =  30.000 )
Traceback (most recent call last):
  File "/Users/Hannah/anaconda3/envs/cellpose/lib/python3.8/site-packages/cellpose/gui/gui.py", line 1957, in new_model
    self.train_model(restore=restore, normalize_params=normalize_params)
  File "/Users/Hannah/anaconda3/envs/cellpose/lib/python3.8/site-packages/cellpose/gui/gui.py", line 2007, in train_model
    self.set_normalize_params(normalize_params)
  File "/Users/Hannah/anaconda3/envs/cellpose/lib/python3.8/site-packages/cellpose/gui/gui.py", line 1736, in set_normalize_params
    percentile = self.check_percentile_params(normalize_params["percentile"])
  File "/Users/Hannah/anaconda3/envs/cellpose/lib/python3.8/site-packages/cellpose/gui/gui.py", line 1745, in check_percentile_params
    if not (percentile[0] >= 0 and percentile[1] > 0 and percentile[0] < 100 and percentile[1] <= 100
TypeError: 'NoneType' object is not subscriptable
GUI_INFO: selected model test, loading now
2024-02-15 17:26:37,371 [INFO] >> test << model set to be used
2024-02-15 17:26:37,372 [INFO] >>>> using CPU
2024-02-15 17:26:37,372 [INFO] WARNING: MKL version on torch not working/installed - CPU version will be slightly slower.
2024-02-15 17:26:37,372 [INFO] see https://pytorch.org/docs/stable/backends.html?highlight=mkl
2024-02-15 17:26:37,456 [INFO] >>>> model diam_mean =  30.000 (ROIs rescaled to this size during training)
2024-02-15 17:26:37,456 [INFO] >>>> model diam_labels =  30.000 (mean diameter of training ROIs)
GUI_INFO: diameter set to  30.00 (but can be changed)
2024-02-15 17:26:39,099 [INFO] >>>> loading model /Users/Hannah/.cellpose/models/test
2024-02-15 17:26:39,099 [INFO] >>>> using CPU
2024-02-15 17:26:39,100 [INFO] WARNING: MKL version on torch not working/installed - CPU version will be slightly slower.
2024-02-15 17:26:39,100 [INFO] see https://pytorch.org/docs/stable/backends.html?highlight=mkl
2024-02-15 17:26:39,174 [INFO] >>>> model diam_mean =  30.000 (ROIs rescaled to this size during training)
2024-02-15 17:26:39,175 [INFO] >>>> model diam_labels =  30.000 (mean diameter of training ROIs)
{'percentile': [1.0, 99.0]}
Traceback (most recent call last):
  File "/Users/Hannah/anaconda3/envs/cellpose/lib/python3.8/site-packages/cellpose/gui/gui.py", line 591, in <lambda>
    self.ModelButtonC.clicked.connect(lambda: self.compute_segmentation(custom=True))
  File "/Users/Hannah/anaconda3/envs/cellpose/lib/python3.8/site-packages/cellpose/gui/gui.py", line 2201, in compute_segmentation
    masks, flows = self.model.eval(data, 
  File "/Users/Hannah/anaconda3/envs/cellpose/lib/python3.8/site-packages/cellpose/models.py", line 501, in eval
    masks, styles, dP, cellprob, p = self._run_cp(x, 
  File "/Users/Hannah/anaconda3/envs/cellpose/lib/python3.8/site-packages/cellpose/models.py", line 549, in _run_cp
    do_normalization = True if normalize_params['normalize'] else False
KeyError: 'normalize'
```

Eventually I would like to be able to use the GPU but for now the idea is to use the iMac rather than MacBook Pro as its really slow.

Thanks for any help, I'm a coding noob who loves Cellpose but struggling with the bugs.

**Comment by carsen-stringer** [comment]
thank you for reporting this, this is a bug from us not your mac, I fixed it. please `pip install git+https://github.com/mouseland/cellpose.git` or wait a bit and `pip install cellpose --upgrade`

**Comment by carsen-stringer** [comment]
PS if you have any advice for installing on M1 we're happy to add it to the repo

**Comment by superwormz** [comment]
Thank you for fixing this so quickly! Yes, I will do. I am also going to have an M3 arriving soon, borrowing M1 for now. Will see how that goes and give you information there too.
