### ISSUE TITLE
[BUG] Cellpose 3 GUI cannot load 3d stack

### ISSUE THREAD

**Issue by Math7914** [MouseLand/cellpose#863]
When I try to import 3d images in the Cellpose 3 GUI, this following error appears :

raise ValueError("cannot load 3D stack, run 'python -m cellpose --Zstack' for 3D GUI")

The suggested command line doesn't work when starting the Cellpose GUI
How can I importe 3d stack within Cellpose GUI ?

Mathieu

**Comment by gillescourtand** [comment]
I tried "cellpose --Zstack " and it raised a different error : 
```
(cellpose) C:\Users\courtand>python -m cellpose --Zstack
2024-02-16 16:58:31,945 [INFO] WRITING LOG OUTPUT TO C:\Users\courtand\.cellpose\run.log
2024-02-16 16:58:31,945 [INFO]
cellpose version:       3.0.3
platform:               win32
python version:         3.8.13
torch version:          1.12.1+cpu
Traceback (most recent call last):
  File "C:\Anaconda\envs\cellpose\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Anaconda\envs\cellpose\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Anaconda\envs\cellpose\lib\site-packages\cellpose\__main__.py", line 257, in <module>
    main()
  File "C:\Anaconda\envs\cellpose\lib\site-packages\cellpose\__main__.py", line 54, in main
    gui3d.run()
  File "C:\Anaconda\envs\cellpose\lib\site-packages\cellpose\gui\gui3d.py", line 108, in run
    app.setPalette(guiparts_old.DarkPalette())
NameError: name 'guiparts_old' is not defined
```

**Comment by carsen-stringer** [comment]
I'm sorry, I fixed this now. But please note the 3D GUI does not yet support the denoising, it will soon

**Comment by derekthirstrup** [comment]
@carsen-stringer I just installed cellpose 3.0.4 and it seems to have issues detecting the z dim of a single channel 3d tif stack.  The tif reader step seems to correctly detect the z stack as having 21 planes but it thinks this single channel tif grayscale image has more than 3 channels so I think the dimension order detection step is a bit off in the new version.  The z stack selector also does not show up at the bottom as it does in CP2.  Here is a screenshot to demo what I found.  
![image](https://github.com/MouseLand/cellpose/assets/20077409/1dfe5ba7-d073-4389-ad53-bddd81c4ec65)

**Comment by Math7914** [comment]
@derekthirstrup You have to launch the following command line : python -m cellpose --Zstack
This should work with your stacked images

**Comment by gillescourtand** [comment]
ok, version 3.0.4 works for me (cellpose --Zstack)
thank you

**Comment by derekthirstrup** [comment]
I can now see the z slider if I open cellpose with "cellpose --Zstack" but I get the following error when trying to use any model to segment a z 1 channel z stack. 

2024-02-19 08:02:08,793 [INFO] network run in 67.71s
2024-02-19 08:02:39,648 [INFO] masks created in 30.86s
2024-02-19 08:02:49,053 [INFO] >>>> TOTAL TIME 108.52 sec
Traceback (most recent call last):
  File "C:\Users\derekt\.conda\envs\cellpose3\Lib\site-packages\cellpose\gui\guiparts.py", line 139, in <lambda>
    self.clicked.connect(lambda: self.press(parent))
                                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\derekt\.conda\envs\cellpose3\Lib\site-packages\cellpose\gui\guiparts.py", line 143, in press
    parent.compute_segmentation(model_name=self.model_name)
  File "C:\Users\derekt\.conda\envs\cellpose3\Lib\site-packages\cellpose\gui\gui.py", line 2228, in compute_segmentation
    self.flows.append(resize_image(self.flows[j], Ly=self.Ly,
                                   ~~~~~~~~~~^^^
IndexError: list index out of range
