### ISSUE TITLE
[BUG] training  with all channels, augment and RGB images leads to incorrect nchan

### ISSUE THREAD

**Issue by josegcpa** [MouseLand/cellpose#869]
**Describe the bug**
When training with the CLI with RGB images and `--all_channels`, the inferred `nchan` in `transforms.random_rotate_and_resize` ([here](https://github.com/MouseLand/cellpose/blob/aeb8bc82f04ef1b68983e0e92fe342d77ea8bb53/cellpose/transforms.py#L799)) is equivalent to the image height (the first element of the shape).

**To Reproduce**
Run on the command line with RGB data

```
 python -m cellpose --use_gpu --verbose --train --dir train_dir --n_epochs 1000 --learning_rate 0.01 --weight_decay 0.01 --mask_filter "_labels" --model_name_out cellpose_from_scratch  --augment --pretrained None --all_channels --channel_axis 2
```

**Run log**

```
Traceback (most recent call last):
  File "C:\Users\mmont\.conda\envs\cellpose\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\mmont\.conda\envs\cellpose\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\mmont\.conda\envs\cellpose\lib\site-packages\cellpose\__main__.py", line 257, in <module>
    main()
  File "C:\Users\mmont\.conda\envs\cellpose\lib\site-packages\cellpose\__main__.py", line 223, in main
    cpmodel_path = train.train_seg([model.net](http://model.net/), images, labels, train_files=image_names,
  File "C:\Users\mmont\.conda\envs\cellpose\lib\site-packages\cellpose\train.py", line 381, in train_seg
    y = net(X)[0]
  File "C:\Users\mmont\.conda\envs\cellpose\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\mmont\.conda\envs\cellpose\lib\site-packages\cellpose\resnet_torch.py", line 179, in forward
    T0    = self.downsample(data)
  File "C:\Users\mmont\.conda\envs\cellpose\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\mmont\.conda\envs\cellpose\lib\site-packages\cellpose\resnet_torch.py", line 66, in forward
    xd.append(self.down[n](y))
  File "C:\Users\mmont\.conda\envs\cellpose\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\mmont\.conda\envs\cellpose\lib\site-packages\cellpose\resnet_torch.py", line 44, in forward
    x = self.proj(x) + self.conv[1](self.conv[0](x))
  File "C:\Users\mmont\.conda\envs\cellpose\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\mmont\.conda\envs\cellpose\lib\site-packages\torch\nn\modules\container.py", line 139, in forward
    input = module(input)
  File "C:\Users\mmont\.conda\envs\cellpose\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\mmont\.conda\envs\cellpose\lib\site-packages\torch\nn\modules\batchnorm.py", line 168, in forward
    return F.batch_norm(
  File "C:\Users\mmont\.conda\envs\cellpose\lib\site-packages\torch\nn\functional.py", line 2438, in batch_norm
    return torch.batch_norm(
RuntimeError: running_mean should contain 535 elements not 3
```

**Fix that worked for us**

We simply changed L799 to extract the minimum of the shape (`nchan = min(X[0].shape)`) as this is in the vast majority of cases the _actual_ number of channels. I can write a PR if necessary, let me know how this would work for you.

**Comment by carsen-stringer** [comment]
ah no this was a bug with the latest train refactor, thanks for the detailed error message. please `pip install git+https://github.com/mouseland/cellpose.git` to try the fix, and let me know if it's still not working
