### ISSUE TITLE
[BUG] Error on downloading `cyto2_cp3` model

### ISSUE THREAD

**Issue by ElpadoCan** [MouseLand/cellpose#871]
**Describe the bug**
When I try to use the model `cyto2_cp3` it fails to download the model. I think the correct URL should be https://www.cellpose.org/models/cyto2_cp3 and not `https://www.cellpose.org/models/cellpose (cyto2_cp3)`

**To Reproduce**
1. Select `cellpose (cyto2_cp3)` model in the Other models box (cellpose GUI)
3. See error 

**Run log**
```
2024-02-22 14:14:41,528 [INFO] Downloading: "https://www.cellpose.org/models/cellpose (cyto2_cp3)" to C:\Users\elpad\.cellpose\models\cellpose (cyto2_cp3)

Traceback (most recent call last):
  File "D:\OneDrive\01_Postdoc_HMGU\GitHub\cellpose\cellpose\gui\gui.py", line 615, in <lambda>
    self.ModelChooseB.activated.connect(lambda: self.model_choose(custom=False))
  File "D:\OneDrive\01_Postdoc_HMGU\GitHub\cellpose\cellpose\gui\gui.py", line 858, in model_choose
    self.initialize_model(model_name=model_name, custom=custom)
  File "D:\OneDrive\01_Postdoc_HMGU\GitHub\cellpose\cellpose\gui\gui.py", line 1930, in initialize_model
    self.model = models.CellposeModel(gpu=self.useGPU.isChecked(), diam_mean=diam_mean,
  File "D:\OneDrive\01_Postdoc_HMGU\GitHub\cellpose\cellpose\models.py", line 294, in __init__
    pretrained_model = model_path(pretrained_model_string)
  File "D:\OneDrive\01_Postdoc_HMGU\GitHub\cellpose\cellpose\models.py", line 44, in model_path
    return cache_model_path(basename)
  File "D:\OneDrive\01_Postdoc_HMGU\GitHub\cellpose\cellpose\models.py", line 60, in cache_model_path
    utils.download_url_to_file(url, cached_file, progress=True)
  File "D:\OneDrive\01_Postdoc_HMGU\GitHub\cellpose\cellpose\utils.py", line 67, in download_url_to_file
    u = urlopen(url)
  File "C:\Users\elpad\.pyenv\pyenv-win\versions\3.10.10\lib\urllib\request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\elpad\.pyenv\pyenv-win\versions\3.10.10\lib\urllib\request.py", line 519, in open
    response = self._open(req, data)
  File "C:\Users\elpad\.pyenv\pyenv-win\versions\3.10.10\lib\urllib\request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "C:\Users\elpad\.pyenv\pyenv-win\versions\3.10.10\lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
  File "C:\Users\elpad\.pyenv\pyenv-win\versions\3.10.10\lib\urllib\request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "C:\Users\elpad\.pyenv\pyenv-win\versions\3.10.10\lib\urllib\request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "C:\Users\elpad\.pyenv\pyenv-win\versions\3.10.10\lib\http\client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\elpad\.pyenv\pyenv-win\versions\3.10.10\lib\http\client.py", line 1293, in _send_request
    self.putrequest(method, url, **skips)
  File "C:\Users\elpad\.pyenv\pyenv-win\versions\3.10.10\lib\http\client.py", line 1127, in putrequest
    self._validate_path(url)
  File "C:\Users\elpad\.pyenv\pyenv-win\versions\3.10.10\lib\http\client.py", line 1227, in _validate_path
    raise InvalidURL(f"URL can't contain control characters. {url!r} "
http.client.InvalidURL: URL can't contain control characters. '/models/cellpose (cyto2_cp3)' (found at least ' ')
```

**Comment by carsen-stringer** [comment]
thanks fixed this now in the git `pip install git+https://github.com/mouseland/cellpose.git`

**Comment by ElpadoCan** [comment]
Fantastic, thank you very much!
