### ISSUE TITLE
[BUG] Loading cyto3-model throws error due to non-existing url for size model

### ISSUE THREAD

**Issue by bevoorrading** [MouseLand/cellpose#891]
**Describe the bug**
When loading the cyto3 model, as in the example on readthedocs, an error get thrown: `HTTPError: INTERNAL SERVER ERROR`.

**To Reproduce**
```
from cellpose import models
model = models.Cellpose(model_type='cyto3')
```

This seems to be caused, when the code tries to download the size-model from the url [https://www.cellpose.org/models/size_cyto3torch_0.npy](https://www.cellpose.org/models/size_cyto3torch_0.npy), which does not exist.

This model (as well as cyto3 itself) don't seem to be included in the models zip-file on the Google Drive [linked on the Github-page](https://github.com/MouseLand/cellpose?tab=readme-ov-file#download-of-pretrained-models) either.

**Comment by mrariden** [comment]
I cannot reproduce this error. My install successfully installs the size model pointing to the url https://www.cellpose.org/models/size_cyto3.npy. Can you make sure you're using Cellpose 3? 

`pip install cellpose --upgrade`

**Comment by bevoorrading** [comment]
You are right, I had Cellpose 2.2.3 (installed with conda from conda-forge). Apologies. With Cellpose 3 (installed with pip) I didn't get the error. Thank you.

**Comment by hupo376787** [comment]
I'm facing the same problem, but I'm using cellpose 3.1.0.
`model = models.Cellpose(model_type="cyto3",gpu=True)`

```
\model\cellpose\resnet_torch.py:225: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state_dict = torch.load(filename, map_location=device)
Traceback (most recent call last):
  File "\model\model-cyto3.py", line 108, in <module>
    model = models.Cellpose(model_type="cyto3",gpu=True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\model\cellpose\models.py", line 104, in __init__
    self.pretrained_size = size_model_path(model_type, self.torch)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\model\cellpose\models.py", line 39, in size_model_path
    return cache_model_path(basename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\model\cellpose\models.py", line 47, in cache_model_path
    utils.download_url_to_file(url, cached_file, progress=True)
  File "\model\cellpose\utils.py", line 69, in download_url_to_file
    u = urlopen(url)
        ^^^^^^^^^^^^
  File "C:\Users\SFDeveloper-01\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 215, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SFDeveloper-01\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 521, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SFDeveloper-01\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 630, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\SFDeveloper-01\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 559, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SFDeveloper-01\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 492, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "C:\Users\SFDeveloper-01\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 639, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 500: INTERNAL SERVER ERROR

```

![image](https://github.com/user-attachments/assets/e952f0be-b534-4de2-900b-5a30c637bfc3)
