### ISSUE TITLE
Error in starting GUI Interface for Cellpose

### ISSUE THREAD

**Issue by Shrishtee-kandoi** [MouseLand/cellpose#907]
Dear Developers,

I am encountering an issue while attempting to utilize the GUI using the command-line command `python -m cellpose`

I successfully installed both cellpose and cellpose[gui] using pip. However, upon trying to initiate the GUI from the command-line terminal, I encountered the following error:

```
 python -m cellpose
Traceback (most recent call last):
  File "/Users/shrishteekandoi/opt/anaconda3/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/shrishteekandoi/opt/anaconda3/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/shrishteekandoi/opt/anaconda3/lib/python3.9/site-packages/cellpose/__main__.py", line 13, in <module>
    from cellpose.gui import gui3d, gui
  File "/Users/shrishteekandoi/opt/anaconda3/lib/python3.9/site-packages/cellpose/gui/gui3d.py", line 8, in <module>
    from superqt import QRangeSlider
  File "/Users/shrishteekandoi/opt/anaconda3/lib/python3.9/site-packages/superqt/__init__.py", line 25, in <module>
    from .spinbox import QLargeIntSpinBox
  File "/Users/shrishteekandoi/opt/anaconda3/lib/python3.9/site-packages/superqt/spinbox/__init__.py", line 1, in <module>
    from ._intspin import QLargeIntSpinBox
  File "/Users/shrishteekandoi/opt/anaconda3/lib/python3.9/site-packages/superqt/spinbox/_intspin.py", line 27, in <module>
    class QLargeIntSpinBox(QAbstractSpinBox):
  File "/Users/shrishteekandoi/opt/anaconda3/lib/python3.9/site-packages/superqt/spinbox/_intspin.py", line 91, in **QLargeIntSpinBox
    def setStepType(self, stepType: QAbstractSpinBox.StepType) -> None:
AttributeError: type object 'QAbstractSpinBox' has no attribute 'StepType'**
```

Your help is appreciated!

Thanks,
Shrishtee

**Comment by mrariden** [comment]
After activating your environment, can you try `pip install cellpose 2.*` for cellpose2 or `pip install cellpose --upgrade` for cellpose3, and check if these work?

**Comment by carsen-stringer** [comment]
closing due to inactivity
