### ISSUE TITLE
ValueError when exporting masks to ImageJ ROIs [BUG]

### ISSUE THREAD

**Issue by LenaGschossmann** [MouseLand/cellpose#913]
When I try to save masks after manual refinement (addition/deletion of masks) of cyto3 segmentation results as an ImageJ ROI zip file, I get following error: "ValueError: zero-size array to reduction operation minimum which has no identity".

The traceback information is:
Traceback (most recent call last):
  File "C:\Users\lenajg\AppData\Local\miniconda3\envs\cellpose\lib\site-packages\cellpose\gui\menus.py", line 63, in <lambda>
    parent.saveROIs.triggered.connect(lambda: io._save_rois(parent))
  File "C:\Users\lenajg\AppData\Local\miniconda3\envs\cellpose\lib\site-packages\cellpose\gui\io.py", line 587, in _save_rois
    save_rois(parent.cellpix[0], parent.filename)
  File "C:\Users\lenajg\AppData\Local\miniconda3\envs\cellpose\lib\site-packages\cellpose\io.py", line 583, in save_rois
    rois = [ImagejRoi.frompoints(outline) for outline in outlines]
  File "C:\Users\lenajg\AppData\Local\miniconda3\envs\cellpose\lib\site-packages\cellpose\io.py", line 583, in <listcomp>
    rois = [ImagejRoi.frompoints(outline) for outline in outlines]
  File "C:\Users\lenajg\AppData\Local\miniconda3\envs\cellpose\lib\site-packages\roifile\roifile.py", line 455, in frompoints
    left_top = coords.min(axis=0)
  File "C:\Users\lenajg\AppData\Local\miniconda3\envs\cellpose\lib\site-packages\numpy\core\_methods.py", line 45, in _amin
    return umr_minimum(a, axis, None, out, keepdims, initial, where)

**Comment by carsen-stringer** [comment]
I think this should be fixed `pip install git+https://github.com/mouseland/cellpose.git` but let us know if not
