### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by TAN-epic** [MouseLand/cellpose#958]
**Describe the bug**
Image cannot be exported

**To Reproduce**
1. Go to 'FILE'
2. Click on 'save Flows and cellprob as tif'
3. See error 

**Run log**
GUI_INFO: creating cellcolors and drawing masks
Traceback (most recent call last):
  File "C:\APP\cellspose\envs\cellpose\lib\site-packages\cellpose\gui\menus.py", line 68, in <lambda>
    parent.saveFlows.triggered.connect(lambda: io._save_flows(parent))
  File "C:\APP\cellspose\envs\cellpose\lib\site-packages\cellpose\gui\io.py", line 580, in _save_flows
    imsave(base + "_cp_flows.tif", parent.flows[4][:-1])
IndexError: list index out of range

**Screenshots**
![image](https://github.com/MouseLand/cellpose/assets/172631346/3d647823-f141-4c6d-9470-bcea5be16dd8)

**Comment by jbaronas-lab** [comment]
Having this same exact error on the most recent version of cellpose.
