### ISSUE TITLE
[BUG] OverflowError with large image

### ISSUE THREAD

**Issue by z5ouyang** [MouseLand/cellpose#968]
**Describe the bug**
When apply to a large image, the error message:
```
Traceback (most recent call last):
  File ".../tools/cellpose/NF_Pilot.py", line 16, in <module>
    io.masks_flows_to_seg([img], masks, flows, [strF], channels=[0,0], diams=diams)
  File ".../cellpose/lib/python3.9/site-packages/cellpose/io.py", line 507, in masks_flows_to_seg
    masks_flows_to_seg(image, mask, flow, file_name, diams=diam,
  File ".../cellpose/lib/python3.9/site-packages/cellpose/io.py", line 563, in masks_flows_to_seg
    np.save(base + "_seg.npy", dat)
  File ".../cellpose/lib/python3.9/site-packages/numpy/lib/npyio.py", line 546, in save
    format.write_array(fid, arr, allow_pickle=allow_pickle,
  File ".../cellpose/lib/python3.9/site-packages/numpy/lib/format.py", line 719, in write_array
    pickle.dump(array, fp, protocol=4, **pickle_kwargs)
OverflowError: serializing a bytes object larger than 4 GiB requires pickle protocol 4 or higher
```

Related to #468 
 Seems like numpy [v2.0.0](https://github.com/numpy/numpy/releases) using 4 now, but cellpose require numpy<2.0.0.

Thank you for this wonderful (gold standard) cell segmentation tool!

**Comment by carsen-stringer** [comment]
ah thanks for letting us know! we were waiting for pytorch support in windows to be 100% for numpy 2.0 but I think it should be working now. we will change the setup.py in the next release, in the meantime you can upgrade your numpy and everything should still work, let us know if not, I'd recommend `pip install numpy==2.0.2` for compatibility with numba
