### ISSUE TITLE
Problem Opening Cellpose: ModuleNotFoundError: No module named 'cv2.cv2'

### ISSUE THREAD

**Issue by hmapodac** [MouseLand/cellpose#985]
(cellpose) C:\Users\user_name>python -m cellpose
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\\user_name\AppData\Local\anaconda3\envs\cellpose\Lib\site-packages\cellpose\__main__.py", line 9, in <module>
    from cellpose import utils, models, io, version_str, train, denoise
  File "C:\Users\\user_name\AppData\Local\anaconda3\envs\cellpose\Lib\site-packages\cellpose\utils.py", line 8, in <module>
    import cv2
  File "C:\Users\\user_name\AppData\Local\anaconda3\envs\cellpose\Lib\site-packages\cv2\__init__.py", line 5, in <module>
    from .cv2 import *
ModuleNotFoundError: No module named 'cv2.cv2'

**Comment by carsen-stringer** [comment]
please try `pip install opencv-python-headless --upgrade`, and try making an environment with python=3.10 instead of 3.8. If this doesn't work I'll re-open the issue
