### ISSUE TITLE
Error saving segmentation results as PNG/TIFF from command line

### ISSUE THREAD

**Issue by athulrv** [MouseLand/cellpose#99]
I was running cellpose in command line for a 3d image stack, it finished and saved the results as seg.npy. It had error in saving as PNG. Now i have to open the seg.npy files in cellpose GUI and saved the segmentation mask separately as png. What is a better solution to this? 

**"Error: ValueError: Image must be 2D (grayscale, RGB, or RGBA)."**

Here is the complete terminal window

```
(cellpose) snz@snz-comp-morph-1:~/cellpose$ python -m cellpose --dir '/media/snz/Datadrive/membrane image test' --use_gpu --do_3D --pretrained_model cyto --diameter 0. --save_png
>>>> using GPU
>>>> estimating diameter for each image
running cellpose on 1 images using chan_to_seg GRAY and chan (opt) NONE
multi-stack tiff read in as having 218 planes 1 channels
processing 1 image(s)
  0%|                                                   | 0/218 [00:00<?, ?it/s]
 running XY (160, 345) 


[08:54:44] src/operator/nn/./cudnn/./cudnn_algoreg-inl.h:97: Running performance tests to find the best convolution algorithm, this can take a while... (set the environment variable MXNET_CUDNN_AUTOTUNE_DEFAULT to 0 to disable)
100%|█████████████████████████████████████████| 218/218 [02:59<00:00,  1.21it/s]
  0%|                                                   | 0/160 [00:00<?, ?it/s]
 running XZ (218, 345) 


100%|█████████████████████████████████████████| 160/160 [02:23<00:00,  1.11it/s]
  0%|                                                   | 0/345 [00:00<?, ?it/s]
 running YZ (218, 160) 


[09:00:08] src/operator/nn/./cudnn/./cudnn_algoreg-inl.h:97: Running performance tests to find the best convolution algorithm, this can take a while... (set the environment variable MXNET_CUDNN_AUTOTUNE_DEFAULT to 0 to disable)
100%|█████████████████████████████████████████| 345/345 [03:46<00:0ValueError: Image must be 2D (grayscale, RGB, or RGBA).0,  1.53it/s]
flows computed 550.08s
dynamics computed 571.31s
masks computed 575.85s
>>>> saving results
Traceback (most recent call last):
  File "/home/snz/anaconda3/envs/cellpose/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/snz/anaconda3/envs/cellpose/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/snz/anaconda3/envs/cellpose/lib/python3.8/site-packages/cellpose/__main__.py", line 181, in <module>
    io.save_to_png(images, masks, flows, image_names)
  File "/home/snz/anaconda3/envs/cellpose/lib/python3.8/site-packages/cellpose/io.py", line 115, in save_to_png
    skimage.io.imsave(base+'_cp_masks.png', masks[n].astype(np.uint16))
  File "/home/snz/anaconda3/envs/cellpose/lib/python3.8/site-packages/skimage/io/_io.py", line 131, in imsave
    return call_plugin('imsave', fname, arr, plugin=plugin, **plugin_args)
  File "/home/snz/anaconda3/envs/cellpose/lib/python3.8/site-packages/skimage/io/manage_plugins.py", line 210, in call_plugin
    return func(*args, **kwargs)
  File "/home/snz/anaconda3/envs/cellpose/lib/python3.8/site-packages/imageio/core/functions.py", line 300, in imwrite
    raise ValueError("Image must be 2D (grayscale, RGB, or RGBA).")
ValueError: Image must be 2D (grayscale, RGB, or RGBA).

```

**Comment by marius10p** [comment]
This seems like a bug. We probably need to save this as tiff series. @carsen-stringer

**Comment by carsen-stringer** [comment]
3D masks cannot be saved as a PNG, now you can save them as a tif from the command line with the `--save_tif` flag. apologies for the delay. please
```
pip install cellpose --upgrade
```
