### ISSUE TITLE
cellpose train size ValueError: train data and labels not same length

### ISSUE THREAD

**Issue by hahia** [MouseLand/cellpose#998]
Hello, i can train cellpose from scratch

```
python -m cellpose --train --dir /hsfscqjf1/ST_CQ/P22Z10200N0618/huanghuaqiang/project/fine_tune_cellpose/from_scratch/train --pretrained_model None --gpu_device 1 --use_gpu --test_dir /hsfscqjf1/ST_CQ/P22Z10200N0618/huanghuaqiang/project/fine_tune_cellpose/from_scratch/val --n_epochs 500 --learning_rate 0.1 --batch_size 8 --chan 0 --verbose --augment --train_size --model_name_out cellpose_three_image_from_scratch
```

the output is 
````
2024-08-15 15:45:29,628 [INFO] 440, train_loss=0.8523, test_loss=0.8864, LR=0.0031, time 16010.48s
2024-08-15 15:51:31,723 [INFO] 450, train_loss=0.8442, test_loss=0.8865, LR=0.0016, time 16372.57s
2024-08-15 15:57:34,139 [INFO] 460, train_loss=0.8446, test_loss=0.8845, LR=0.0008, time 16734.99s
2024-08-15 16:03:35,817 [INFO] 470, train_loss=0.8403, test_loss=0.8849, LR=0.0004, time 17096.67s
2024-08-15 16:09:37,954 [INFO] 480, train_loss=0.8420, test_loss=0.8845, LR=0.0002, time 17458.80s
2024-08-15 16:15:39,999 [INFO] 490, train_loss=0.8432, test_loss=0.8839, LR=0.0001, time 17820.85s
2024-08-15 16:21:02,515 [INFO] >>>> model trained and saved to /hsfscqjf1/ST_CQ/P22Z10200N0618/huanghuaqiang/project/fine_tune_cellpose/from_scratch/train/models/cellpose_three_image_from_scratch
2024-08-15 16:21:02,517 [CRITICAL] train data and labels not same length

Traceback (most recent call last):
  File "/hsfscqjf1/ST_CQ/P22Z10200N0618/huanghuaqiang/envs/cellpose/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/hsfscqjf1/ST_CQ/P22Z10200N0618/huanghuaqiang/envs/cellpose/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/hsfscqjf1/ST_CQ/P22Z10200N0618/huanghuaqiang/envs/cellpose/lib/python3.8/site-packages/cellpose/__main__.py", line 308, in <module>
    main()
  File "/hsfscqjf1/ST_CQ/P22Z10200N0618/huanghuaqiang/envs/cellpose/lib/python3.8/site-packages/cellpose/__main__.py", line 281, in main
    sz_model.params = train.train_size(model.net, model.pretrained_model,
  File "/hsfscqjf1/ST_CQ/P22Z10200N0618/huanghuaqiang/envs/cellpose/lib/python3.8/site-packages/cellpose/train.py", line 527, in train_size
    out = _process_train_test(
  File "/hsfscqjf1/ST_CQ/P22Z10200N0618/huanghuaqiang/envs/cellpose/lib/python3.8/site-packages/cellpose/train.py", line 186, in _process_train_test
    raise ValueError(error_message)
ValueError: train data and labels not same length
````
train_seg is ok but train_size raise an error

train data and labels is like 

![image](https://github.com/user-attachments/assets/d83c5607-fd19-4fbb-a41a-fd9d0f9c9c38)

**Comment by carsen-stringer** [comment]
sorry I can't replicate this with the latest version of cellpose, can you please upgrade? if you still get an error I'll reopen the issue
